#98 into release@3.2.0 ☄ interceptors examples
siberiacancode/mock-config-server pull request #100
Opened 2023-08-25 14:38 UTC by debabin

2023-09-23 11:11 UTC, RiceWithMeat approved these changes

2023-10-01 07:09 UTC, anv296 approved these changes

2023-12-13 15:31 UTC, MiaInturi requested changes

2023-12-13 15:31 UTC, MiaInturi commented on tsconfig.dev.json
> +      "mock-config-server/*": ["./dist"],
Второй alias бесполезный - первый же по сути то же самое, т.к. оба ведут на ./dist

2023-12-13 15:31 UTC, MiaInturi commented on examples/interceptors/graphql/database.ts
> +    request: async (params) => params.setDelay(1000)
await перед setDelay?

2023-12-13 15:31 UTC, MiaInturi commented on examples/interceptors/graphql/database.ts
> +import type { MockServerConfig } from 'mock-config-server';
Название файла как-то не сходится с контентом файла

2023-12-13 15:31 UTC, MiaInturi commented on examples/interceptors/graphql/request/api-layer.ts
> +import type { MockServerConfig } from 'mock-config-server';
Думаю лучше в названии файла еще добавить что-то про interceptor

2023-12-13 15:31 UTC, MiaInturi commented on examples/interceptors/graphql/response/route-layer.ts
> +export const mockServerConfig: MockServerConfig = {
Этот файл идентичен файлу `examples/interceptors/graphql/response/request-layer.ts`

2023-12-13 15:31 UTC, MiaInturi commented on examples/interceptors/rest/database.ts
> +import type { MockServerConfig } from 'mock-config-server';
Название файла как-то не сходится с контентом файла x2

2023-12-13 15:31 UTC, MiaInturi commented on examples/interceptors/rest/response/route-layer.ts
> +import { createMockServer, startMockServer } from 'mock-config-server';
Опять же файл идентичен `examples/interceptors/rest/response/request-layer.ts`

2023-12-13 16:03 UTC, debabin commented on examples/interceptors/graphql/database.ts
> +import type { MockServerConfig } from 'mock-config-server';
это вариант database простой на интерцепторах

2023-12-13 16:10 UTC, MiaInturi commented on examples/interceptors/graphql/database.ts
> +import type { MockServerConfig } from 'mock-config-server';
А есть ли в этом смысл, если существует отдельная фича под это? Тут же буквально костыль описан, который может быть решен использованием database

2023-12-13 18:18 UTC, debabin commented on examples/interceptors/graphql/database.ts
> +import type { MockServerConfig } from 'mock-config-server';
Ну вообще это полезная история, потому-что я буквально словил кейс когда я не могу решить что-то через датабез, если нет id, то датабейз работает не на 100 процентов, плюс с помощью этого примеры люди больше понимают, а как с interceptors можно работать. В доке конечно же будет описано, что мы рекомендуем database из библы

2023-12-16 10:44 UTC, debabin commented on examples/interceptors/graphql/database.ts
> +    request: async (params) => params.setDelay(1000)
нужно удалить async, у нас js же умный и там в коде стоит уже await, а возвращается у нас промис, короче говоря все и так работает

2023-12-16 10:45 UTC, debabin commented on examples/interceptors/graphql/request/api-layer.ts
> +import type { MockServerConfig } from 'mock-config-server';
Думаю что это масло, но на самом деле вай нот, добавил -interceptor

2023-12-17 06:55 UTC, MiaInturi approved these changes

2023-12-17 09:23 UTC, merged