#109 into release@3.2.0 ☄ filter function for database
siberiacancode/mock-config-server pull request #110
Opened 2023-08-28 16:01 UTC by debabin

2023-08-29 15:58 UTC, debabin commented
не стал писать тесты чисто для filter, ведь они буду совпадать с тестами уже существующими

2023-09-08 18:00 UTC, MiaInturi requested changes

2023-09-08 18:00 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +    });
Можно сделать не через отрицания some, а через every - так будет понятнее, т.к. сейчас по сути отрицание, так еще и внутри коллбэка отрицание. + использовать не `.toString`, а шаблонные строки для приведения к string (шаблонные строки не выкинут ошибку при использовании c null или undefined)

2023-09-09 13:22 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +      if (!flattenedElelement[key]) return false;
есть идеи как лучше сделать ? 

const obj = {}

console.log(obj['name']) -> будет undefined и тут вопрос если чел в фильтре укажет null или undefined как мы поступаем

2023-09-23 10:05 UTC, MiaInturi approved these changes

2023-09-23 10:05 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +    test('Should return filtered array by same queries', async () => {
Я не очень понял почему в названии неаписано `by same queries`?

2023-09-23 10:49 UTC, RiceWithMeat approved these changes

2023-09-23 10:49 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +    const flattenedElelement = flatten<any, any>(element);
Elelement -> Element

2023-09-23 10:49 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +    test('Should return filtered array by same queries', async () => {
значит что будет работать если указать одинаковые квери несколько раз. там id два раза написан

2023-09-23 11:06 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +    test('Should return filtered array by same queries', async () => {
думаю, тут стоить переформулировать на "Should return filtered array by identical queries names" @MiaInturi

2023-09-23 14:45 UTC, merged