#111 into release@3.2.0 ☄ slice query for nested database
siberiacancode/mock-config-server pull request #112
Opened 2023-08-29 15:50 UTC by debabin

2023-09-08 17:06 UTC, MiaInturi requested changes

2023-09-08 17:06 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +        response.set('Cache-control', 'max-age=0, must-revalidate');
Это вроде бы бесполезная строчка, т.к. этот header ставится ниже

2023-09-08 17:06 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +    });
Я думаю, что тут внутри `toStrictEqual` писать не сами объекты, а вызывать nestedDatabase.users.slice - за счет этого можно будет менять nestedDatabase.users без изменения тестов + покажет, что slice в query === slice в массиве

2023-09-23 09:34 UTC, MiaInturi commented
Ат тут запушены изменения? Потому что комменты закрыты а изменений нет

2023-09-23 10:44 UTC, RiceWithMeat approved these changes

2023-09-23 11:16 UTC, debabin commented
> Ат тут запушены изменения? Потому что комменты закрыты а изменений нет

Забыл запушить

2023-09-23 14:54 UTC, MiaInturi approved these changes

2023-10-01 06:51 UTC, anv296 approved these changes

2023-11-18 10:12 UTC, merged