#113 into release@3.2.0 👹 fix graphql types and validation
siberiacancode/mock-config-server pull request #114
Opened 2023-09-08 16:35 UTC by MiaInturi

Большое изменение в первую очередь типизации graphql.
Из основного:
1. Если для variables использовался top level descriptor, то при checkMode=equals была возможность писать в value объекты любой вложенности. Теперь возможны объекты только 1 уровня вложенности.
2. Если variables был простым объектом, то была возможность писать в value объекты любой вложенности. Теперь возможны объекты только 1 уровня вложенности.
3. Если для какого-либо свойства объекта variables использовался descriptor, то в value можно было писать объекты. Теперь можно писать только примитивы.

Основная причина багов типизации заключалась в том, что top level descriptor и descriptor для свойств объекта были одним типом, хотя их семантика очень сильно различается - по итогу данные типы были разделены на GraphQLTopLevelPlainEntityDescriptor и GraphQLPropertyLevelPlainEntityDescriptor.

2023-09-10 03:37 UTC, debabin commented
1. Про первый пункт, так же и было задумано ? там же всегда flat делается 
2. same 1 
3. тут тоже момент, а разве мы не поддерживаем обьекты ? например для checkMode=equals ? 
4. гуд

2023-09-15 15:43 UTC, MiaInturi commented
> 1. Про первый пункт, так же и было задумано ? там же всегда flat делается
> 2. same 1
> 3. тут тоже момент, а разве мы не поддерживаем обьекты ? например для checkMode=equals ?
> 4. гуд

Короче думаю отвечу сразу про первые 3 пункта. Мы позволяем писать в descriptor объекты только 1 уровня вложенности, т.к. если этого не делать, то свойства latten-объекта будут выглядеть примерно так: `key1.key2....descriptor.keyN.keyN+1....` т.е. появляется descriptor, а очевидно, что его не будет в большинстве случаев в реальных variables. Просто убирать из ключа descriptor мы не можем, т.к. все же иногда реальные variables будут содержать это поле.

2023-09-17 06:24 UTC, MiaInturi commented
Исправил по замечаниям - теперь для variables можно делать вложенные объекты в любых ситуциях кроме descriptor (для тех случаев, когда descriptor относится не ко всему объекту variables, а к какому-то его свойству).

2023-09-23 09:13 UTC, MiaInturi commented
Изменил валидацию graphql - теперь checkMode `equals | notEquals` проверяются отдельно от checkMode для строк `includes | notIncludes | ...`. Основная причина такой переработки - equals и notEquals могут проверять вложенные объекты, в то время как includes и т.п. работают только с примитивами.

2023-09-23 10:24 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>            }
можно убрать else так как throw энивей остановит выполнение функции. либо перенести условие `!isDescriptorValueValid(checkMode, element, false)` в верхний if `if (( isVariables &&
            !isDescriptorValueValid(checkMode, element, true) &&
            !isDescriptorValueValid(checkMode, element, false)) || !isDescriptorValueValid(checkMode, element, false))`. Ошибка же одинаковая выбрасывается

2023-09-23 10:24 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>        }
тоже самое

2023-09-23 10:24 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +          new RegExp(requestConfig.operationName).test(query.operationName!) &&
тут точно `!` нужен? выше же есть ретёрн если !query.operationName

2023-09-23 11:09 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>            }
`esle if` нужен для того, чтобы `!isDescriptorValueValid(checkMode, element, false)` два раза для variables не вызывался

2023-09-23 11:10 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>        }
Ответил выше

2023-09-23 11:16 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>            }
так isDescriptorValueValid не будет вызываться два раза, в моём условии по сути описано "если isVariables и !isDescriptorValueValid или если !isVariables и !isDescriptorValueValid". если первая часть у `OR` будет истинной, то дальше код не будет вызываться

2023-09-23 11:17 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>            }
или даже можно так написать if ((isVariables && !isDescriptorValueValid(checkMode, element, true)) || !isDescriptorValueValid(checkMode, element, false))

2023-09-23 11:22 UTC, RiceWithMeat approved these changes

2023-09-23 12:37 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>            }
Я запутался уже немного. Так мы в условие после `||` добавляем `!isVariables`? Если да, то вопросов нет, если не добавляем, то при условии, что variables будет валидным, то будет лишний вызов проверки.
Я задаю этот вопрос, т.к. в коде, который ты привел как пример нет условия `!isVariables`

2023-09-23 13:54 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>            }
да, ты прав, надо добавлять `!isVariables`, иначе будут такие кейсы. проще тогда оставить как сейчас и убрать else как сначала предлагал

2023-09-23 14:07 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>            }
а без else точно такая же проблема будет - первый блок if пройдет если конфиг валидный и вызовется второй if

2023-09-23 14:27 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +          new RegExp(requestConfig.operationName).test(query.operationName!) &&
гляну, мб и не нужен

2023-09-23 14:39 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>            }
по фактам, резолв конверсатион получаеца

2023-09-23 14:41 UTC, debabin requested changes

2023-09-23 14:41 UTC, debabin commented on src/utils/helpers/graphql/getGraphQLInput/getGraphQLInput.ts
> +    // if 'variables' was sent as encoded uri component then it already decoded into object and we do not need to use JSON.parse
а можешь привести такой кейс, просто в query же всегда будет стринг, хоть что туда не кидай

2023-09-23 14:41 UTC, debabin commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +      return isValueValidOnTopLevel && isObjectOrArrayValid(value);
опять же для меня не понятно, зачем добавлять еще 1 параметр в данную функцию, мы можем считать это внутри функции и не добавлять параметр

2023-09-23 14:41 UTC, debabin commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +      const isValueValidOnTopLevel = isPlainObject(value) || Array.isArray(value);
isValueObject ?

2023-09-23 14:41 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> -      const incorrectMappedEntityValues = [null, {}, () => {}, /\d/];
а почему null ушел ?

2023-09-23 14:41 UTC, debabin commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.test.ts
>    });
как раз добавилась проверка, хотя можно ее сделать автоматизированной

2023-09-23 14:41 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +    const { checkMode: topLevelCheckMode, value: topLevelValue } = entity;
вообще не понял зачем тут данные строчки, почему просто ниже нельзя сделать entity.checkMode и entity.value

2023-09-23 14:41 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
>          }
предыдущие название мне было более понятно, plain object, также у нас одинаковый нейминг для rest и там например body plain, если менять то там и там

2023-09-23 14:41 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +        >;
тот же вопрос с неймингом, раньше было более понятно и такой же нейминг в rest api

2023-09-23 14:41 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +            entityName === 'variables' ? graphQLInput.variables ?? {} : request[entityName]
вот отсюда и вопрос, мб уже в функции выше делать не undefined а {}, чтобы не писать уже тут, ведь по факту для нас пустой обьект тоже самое, что если бы там ничего не было бы

2023-09-23 14:41 UTC, debabin commented on src/utils/types/graphql.ts
> +type GraphQLMappedEntityName = Exclude<GraphQLEntityName, 'variables'>;
а не нужно ли опять же такое промутить и с rest ?

2023-09-23 14:41 UTC, debabin commented on src/utils/types/graphql.ts
> -  : Check extends Extract<CalculateByDescriptorValueCheckMode, 'regExp'>
почему мы убрали зависимость от типа ?

2023-09-23 15:00 UTC, MiaInturi commented on src/utils/helpers/graphql/getGraphQLInput/getGraphQLInput.ts
> +    // if 'variables' was sent as encoded uri component then it already decoded into object and we do not need to use JSON.parse
qs внутри себя вызывает decodeURLComponent - то есть если объект передали в урле через encodeURLComponent. то вернется объект, а не строка

2023-09-23 15:00 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> -      const incorrectMappedEntityValues = [null, {}, () => {}, /\d/];
Потому что в body, variables можно передать объект вида { a: null, b: null }

2023-09-23 15:01 UTC, MiaInturi commented on src/utils/types/graphql.ts
> -  : Check extends Extract<CalculateByDescriptorValueCheckMode, 'regExp'>
Потому что extract не предоставляет никакой безопасности с точки зрения типов - во второй аргумент можно передать что угодно.

2023-09-23 15:02 UTC, MiaInturi commented on src/utils/types/graphql.ts
> +type GraphQLMappedEntityName = Exclude<GraphQLEntityName, 'variables'>;
Да, надо бы, но тут так много исправлений, что для rest это еще день нужен

2023-09-23 15:07 UTC, debabin commented on src/utils/helpers/graphql/getGraphQLInput/getGraphQLInput.ts
> +    // if 'variables' was sent as encoded uri component then it already decoded into object and we do not need to use JSON.parse
реально ? есть пример кода

2023-09-23 15:31 UTC, MiaInturi commented on src/utils/helpers/graphql/getGraphQLInput/getGraphQLInput.ts
> +    // if 'variables' was sent as encoded uri component then it already decoded into object and we do not need to use JSON.parse
![Uploading Безымянный.png…]()

2023-09-23 15:32 UTC, MiaInturi commented on src/utils/helpers/graphql/getGraphQLInput/getGraphQLInput.ts
> +    // if 'variables' was sent as encoded uri component then it already decoded into object and we do not need to use JSON.parse
![Безымянный](https://github.com/siberiacancode/mock-config-server/assets/39031929/771e4be6-6c39-4899-b477-bfa660fad6d7)

2023-09-23 15:42 UTC, MiaInturi commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +      return isValueValidOnTopLevel && isObjectOrArrayValid(value);
`isCheckAsObject` не посчитать внутри функции. Этот параметр по сути определяет как нужно проверять value дескриптора - как объект или как примитив. 
Когда нужно проверять value дескриптора как объект?
1. Когда используется дескриптор для всей entity
```typescript
entities {
  variables: {
    checkMode: 'equals', 
    value: { a: 1, b: 2 }
  }
}
```
2. Т.к. body и variables могут быть любой вложенности, то внутри дескриптора свойства тоже может быть объект
```typescript
entities {
  variables: {
    key: {
      checkMode: 'equals',
      value: { a: 1, b: 2 }
    }
  }
}
```

2023-09-23 15:43 UTC, MiaInturi commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.test.ts
>    });
Ответил с примерами выше. В целом, если есть мысли как избавиться от доп. параметра, то будет круто. Возможно валидацию checkMode `equals | notEquals` для объектов нужно в отдельную функцию выносить.

2023-09-23 15:44 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +    const { checkMode: topLevelCheckMode, value: topLevelValue } = entity;
Можно, просто эти строки уже были в коде и я их скопировал и вставил

2023-09-23 15:46 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
>          }
Но `isVariablesPlain` же не имеет смысла, т.к. variables по определению уже plain

2023-09-23 15:50 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +        >;
Я ушел от префикса mappedEntity потому что здесь может быть не только mappedEntity. Тут могут быть еще и plainEntity в формате не топ левел дескриптора. Дескриптор для plainEntity может быть двух вариантов - дескриптор на всю entity или дескриптор только на некоторые свойства. Вот recordEntries используется либо для mappedEntity либо для plainEntity с дескрипторами на некоторых свойствах

А по поводу "такой же нейминг в rest api" - в rest сейчас те баги, которые я исправил тут. Когда будем исправлять, то я исправлю нейминг и там

2023-09-24 07:18 UTC, debabin requested changes

2023-09-24 07:18 UTC, debabin commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
>        })) ?? [];
можно тут запарсить кверю с помощью функции если указали query и уже оттуда достать operationName

2023-09-24 07:18 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +        }
какой же я фанат все таки if () return я честно не до конца понимаю зачем писать { } в простых кейсах

2023-09-24 07:18 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +        .query({ query: 'query GetUsers { users { name } }' });
не хотим ли мы поддержать необязательность пробелов, а то человек, кто захочет указать query может добавить лишний пробел и удивится не работе кода, а то могут быть кейсы, что человек укажит вот так {  users { name  } }

2023-09-24 09:42 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +          new RegExp(requestConfig.operationName).test(query.operationName!) &&
Исправил

2023-09-24 10:10 UTC, MiaInturi commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +      return isValueValidOnTopLevel && isObjectOrArrayValid(value);
Короче, по поводу нашего обсуждения и что можно не добавлять доп. параметр, а расчитывать внутри функции, мол если нам передан объект, то валидируй как объект, а если передан примитив, то валидируй как примитив. Этот подход работает только с теми entites, которые в дескрипторах могут принимать и объекты и примитивы. Если же сделать такую динамическую валидацию и удалить доп. параметр, то не будет выкинута ошибка в таком кейсе, например:
```typescript
entities {
  headers: {
    key: {
      checkMode: 'equals',
      value: { a: 1, b: 2 }
    }
  }
}
```
Здесь в дескриптор свойства key из headers передается объект. Наша валидация тогда увидит что это объект и просто провалидирует его как, собственно, объект.

2023-09-24 10:19 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
>        })) ?? [];
А в query не всегда будет лежать operationName, как например на скриншоте
![Безымянный](https://github.com/siberiacancode/mock-config-server/assets/39031929/365513d9-194c-4e88-8cea-4ceb1a95abab)

2023-10-01 06:49 UTC, anv296 approved these changes

2023-10-01 06:49 UTC, anv296 commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +      return isValueObject && isObjectValid(value);
вкусовщина наверно, но можно в одну строку уложить в ретерн

2023-10-01 06:49 UTC, anv296 commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +        const recordOrArrayEntries = Object.entries(entityDescriptorOrValue) as Entries<
может я не в контексте, но вроде можно вместо as использовать satisfies, @RiceWithMeat эксперт по этому свежему оператору)

2023-10-01 09:02 UTC, debabin requested changes

2023-10-01 09:02 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateGraphqlConfig.test.ts
> +  test('Shouldcorrectly handle operation query only with correct type', () => {
пробел

2023-10-01 09:24 UTC, MiaInturi commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +  isCheckAsObject: boolean
Я отписал выше, почему так оставил

2023-10-01 09:24 UTC, MiaInturi commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +  isCheckAsObject: boolean
https://github.com/siberiacancode/mock-config-server/pull/114#discussion_r1335156453

2023-10-01 09:32 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateGraphqlConfig.ts
> +        throw new Error(`configs[${index}]`);
Ну тут ошибка именно в конфиге, мол в конфиге обязательно должны быть либо operationName, либо query.
А по поводу "это и другим пунктам относится" - я не понял

2023-10-01 09:39 UTC, MiaInturi commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +            isBody &&
Как раз таки баг в том, что `!isBody` не должно быть всерху

2023-10-01 09:59 UTC, MiaInturi commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
>            }
ответил

2023-10-01 10:04 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateGraphqlConfig.ts
> +        throw new Error(`configs[${index}]`);
ну сейчас мы просто скажем в каком конфиге ошибка, но не скажем почему, другие кейсы я про те что ниже

2023-10-01 10:19 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +            entityName === 'variables' ? graphQLInput.variables ?? {} : request[entityName]
Да, я верну эту штуку

2023-10-01 10:20 UTC, MiaInturi commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +            !isDescriptorValueValid(checkMode, element, false)
Ответил выше, почему я не вижу возможности убрать 3й параметр

2023-10-01 10:20 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>          return;
Вынести типо в отдельную функцию? Или вообще убрать?

2023-10-01 10:28 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +            entityName === 'variables' ? graphQLInput.variables ?? {} : request[entityName]
Хотя я сейчас увидел, что тут приходится костылить и в случае, если возвращается объект
```typescript
return resolveEntityValues(
            checkMode,
            Object.keys(graphQLInput.variables).length ? graphQLInput.variables : undefined,
            descriptorValue
          );
```
вот такой код сейчас в ветке main.

Мой подход с возвращением undefined мне кажется лучше по той причине, что так правильнее семантически (т.к. тот же variables буквально нет), а костыль с  `?? {}` менее громоздкий чем с `Object.keys`

2023-10-01 10:29 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +        .query({ query: 'query GetUsers { users { name } }' });
Думаю это можно сделать прям очень четко, прохождением по токенам, но нужно время для реализации этого. Думаю создам отдельную issue

2023-10-01 10:35 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +        }
исправил

2023-10-01 10:37 UTC, debabin commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +  isCheckAsObject: boolean
понял твоей тейк, но как по мне лучше описать логику явно выше, напирме если это headers и пришел обьект, то ошибка, и если все гуд уже вызывать функцию

2023-10-01 10:55 UTC, MiaInturi commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +  isCheckAsObject: boolean
понял, да, вроде бы должно сработать, даже вроде бы есть мысль как сделать красиво

2023-11-05 13:54 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +  test('Should correctly hanlde body entity only with correct type', () => {
handle

2023-11-05 13:54 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +    test('Should return 404 if actual query operationName does not mathc to config string operationName', async () => {
match

2023-11-05 13:54 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +              entityName === 'headers' ? (entityKey as string).toLowerCase() : entityKey
можно убрать as string, по типизации entityKey всегда строка

2023-11-05 13:54 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +                  entityName === 'headers' ? (entityKey as string).toLowerCase() : entityKey
entityKey всегда строка

2023-12-07 14:46 UTC, debabin requested changes

2023-12-07 14:46 UTC, debabin commented on README.md
> +              body: [{ key1: 'value1' }, ['value1']]
решили добавить check моды для масивов

2023-12-07 14:50 UTC, debabin requested changes

2023-12-21 14:27 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    cookieParseMiddleware(server);
Видимо добавил для чего-то, а потом забыл убрать. Удалил.

2023-12-21 15:54 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +        .query({ query: 'query GetUsers { users { name } }' });
Теперь все последовательности пробелов заменяются одним пробелом

2023-12-21 16:59 UTC, merged