#120 into release@3.3.0 ☄ polling support for rest and graphql
siberiacancode/mock-config-server pull request #121
Opened 2023-10-23 16:07 UTC by debabin

2023-10-29 19:29 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +  });
стоит добавить третий запрос чтобы проверить, что очередь пойдёт по кругу и опять вернётся John Doe

2023-10-29 19:29 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +      data: ((request: Request, entities: Entities) => Data | Promise<Data>) | Data;
Если так посмотреть, то так ли нам нужен флаг polling? Сейчас по сути от него нет смысла, ведь если он true, то мы разрешаем писать только queue, а если false или не указан, то разрешаем только data. Один к одному зависимость. Типизация не сломается если его убрать + будет и так сразу понятно, что это очередь для полинга если переименовать queue в pollingQueue. Можно в принципе оставить разве что на будущее когда будет редактор конфига наверное

2023-10-30 13:10 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            };
ну shallow это просто клон по факту

2023-10-30 13:11 UTC, debabin commented on src/utils/types/rest.ts
> +      data: ((request: Request, entities: Entities) => Data | Promise<Data>) | Data;
я бы заложил это на будущие в редактор + мне нравится, что это прям настройка, пользователь никогда не ошибется, он всегда будет говорить сам, я хочу полинг

2023-11-04 17:09 UTC, RiceWithMeat approved these changes

2023-11-19 11:41 UTC, MiaInturi requested changes

2023-11-19 11:41 UTC, MiaInturi commented on bin/validateMockServerConfig/validateSettings/validateSettings.test.ts
> +});
Не хватает проверок на то, что будет если скинуть невалидный setting и на то, что будет если в поле polling будет значение невалидного типа

2023-11-19 11:41 UTC, MiaInturi commented on bin/validateMockServerConfig/validateSettings/validateSettings.ts
> +      if (!isEntityAllowed) {
Неправильное название переменной

2023-11-19 11:41 UTC, MiaInturi commented on src/utils/types/rest.ts
> +      settings?: Settings & { polling?: false };
А почему тут polling может быть не определен? Мне кажется логичным, что если в случае с queue поллинг свойство обязательно, то и в случае с data оно должно быть обязательно. А за обратную совместимость с пред. версиями все равно отвечает необязательность свойства settings

2023-11-19 11:41 UTC, MiaInturi commented on .eslintrc.js
> +        'promise/always-return': 'off',
`promise/always-return': ['error', { ignoreLastCallback: true }]` - можно заменить на это. Думаю так будет правильнее

2023-11-19 11:41 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          };
1. На последней строчке не смысла обновлять index, т.к. он дальше не используется.
2. Можно сразу при изменении __pollingIndex сравнивать с длиной (и если что сеттить 0). Это позволит избежать лишней проверки на строке 90.

2023-11-22 05:39 UTC, debabin commented on bin/validateMockServerConfig/validateSettings/validateSettings.test.ts
> +});
Я посмотрел у нас везде такого нет, тот же интерцептор если взять, надо короче еще чуть-чуть помыслить а нужно ли оно

2023-11-22 16:51 UTC, MiaInturi requested changes

2023-11-22 16:51 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
>  import request from 'supertest';
Не хватает тестов для пустого queue. То же самое про Rest

2023-11-22 16:51 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +    await sleep(1000);
Обычно таймеры тестят с помощью специального апи для мокирования таймеров, типо jest.useFakeTimers и т.д. Тоже самое для Rest

2023-11-22 16:51 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +        }
1. Если queue не массив, то должна выводиться ошибка routes[index].queue
2. Если queue есть, но при этом polling не задан, то должна выводиться ошибка routes[index].settings
3. Если queue есть, но при этом polling задан и не true, то должна выводиться ошибка routes[index].settings.polling

2023-11-22 16:51 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
>          }
Тут то же самое про polling, что и выше

2023-11-22 16:51 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +        const isRouteQueueArray = Array.isArray(route.queue);
Валидация пропустит data и queue одновременно?

2023-11-22 16:51 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +  });
Тут еще надо перебирать все типы queue, settings, polling.

2023-12-10 09:18 UTC, RiceWithMeat approved these changes

2023-12-10 09:18 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +          console.log('@@@@@@@');
логи остались в файле

2023-12-10 12:50 UTC, anv296 approved these changes

2023-12-12 14:01 UTC, MiaInturi requested changes

2023-12-12 14:01 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +  });
Я имел в виду, что для queue, settings и polling нужно буквально перебирать все типы от number до regExp

2023-12-13 17:55 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
>          }
Так настройки проверяются ниже, это проверки по факту на queue и polling

2023-12-13 17:57 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +  });
Этот тест проверяет только полинг значения и их вариации, как раз те самые if выше, data проверятся уже в отдельном тесте выше, settings проверяется в validateSettings, допишу тесты к data про queue проверку

2023-12-17 06:49 UTC, MiaInturi requested changes

2023-12-17 06:49 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +  });
Тут useRealTimers не хватает

2023-12-17 06:49 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    jest.useRealTimers();
А почему useRealTimers тут, если здесь нет useFakeTimers?

2023-12-17 06:49 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +    ];
Думаю надо еще добавить `{ data: null, settings: { polling: false } }`

2023-12-17 06:49 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +  });
Нет проверки "нет queue и нет data", "есть queue и есть data", "есть data и при этом polling = false"

2023-12-17 06:49 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +    );
Короче, я думаю validateQueue нужна отдельная функция, т.к. надо проверять не только, что это массив, а также то, что элементы этого массива объекты у которых обязательно есть поле data, а поле time может быть только number | undefined

2023-12-18 10:10 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +    );
В итоге так и сделал, не видел твои комменты, сейчас займусь

2023-12-18 12:01 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +  });
1 кейс нет смысла проверять, это проверятся во всех других тестах же

2023-12-20 13:57 UTC, MiaInturi requested changes

2023-12-20 13:57 UTC, MiaInturi commented on bin/validateMockServerConfig/validateQueue/validateQueue.ts
> +      }
Этот вариант не проверяется тестами. В целом можешь запустить команду test и там выдаст coverage и покажет строки, которые не покрыты тестами

2023-12-20 13:57 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +  });
А можешь пример привести? +  "есть data и при этом polling = true" - это не проверяется на выброс исключения

2023-12-20 13:57 UTC, MiaInturi commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +    );
А от этой проверки же нет смысла, т.к. в validateQueue это проверяется

2023-12-20 13:59 UTC, MiaInturi requested changes

2023-12-20 13:59 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +
Лишний перенос строки

2023-12-20 14:23 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +  });
Добавил кейс

```ts
const incorrectSettingsRouteMappedValues = [{}, { data: null, settings: { polling: true } }];
      incorrectSettingsRouteMappedValues.forEach((incorrectSettingsRouteMappedValue) => {
        expect(() => validateRoutes([incorrectSettingsRouteMappedValue], 'query')).toThrow(
          new Error('routes[0]')
        );
      });
```

2023-12-20 14:48 UTC, MiaInturi requested changes

2023-12-20 14:48 UTC, MiaInturi commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
>          }
Короче, я понял, что меня смущало. Мне кажется, что тут должно быть `throw new Error(``routes[${index}].settings.polling``);` т.к. сломана настройка именно поллинга. В тестах тоже отписал про это.

2023-12-20 14:48 UTC, MiaInturi commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +    });
Второй элемент массива надо перенести в incorrectSettingPollingRouteMappedValue**S**, т.к. пусть именно там будет проверка поллинга, а сюда вместо этого добавить `{ data: null, queue: null }`. Была же проверка это, зачем удалил?

2023-12-20 15:16 UTC, MiaInturi approved these changes

2023-12-20 16:19 UTC, merged