#122 into release@3.3.0 ☄ pagination for database
siberiacancode/mock-config-server pull request #123
Opened 2023-11-03 15:41 UTC by debabin

2023-11-05 11:59 UTC, RiceWithMeat commented on README.md
> +- `pages` {number} count of elements
count of pages

2023-11-05 11:59 UTC, RiceWithMeat commented on README.md
> +- `prev` {string | null} querys string for prev link
лишняя s у query

2023-11-05 11:59 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +        const { _page, _limit, ...fillters } = request.query;
лишняя l у filters

2023-11-05 11:59 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +        console.log('@data', data);
лишний лог

2023-11-05 11:59 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      const secondResponse = await request(server).get('/users?_page=2&_limit=1');
лучше подставить query строку из firstResponse.body._link.next чтобы заодно проверить, что возвращается правильная ссылка

2023-11-05 11:59 UTC, RiceWithMeat commented on README.md
> +In the **Link** header you'll get **count**, **pages**, **next** and **prev** links.
In the **_link** object you'll...
Это не хедер же, а просто объект

2023-11-05 12:44 UTC, debabin commented on README.md
> +In the **Link** header you'll get **count**, **pages**, **next** and **prev** links.
возвращается и обьект link и хедер

2023-11-05 12:48 UTC, RiceWithMeat approved these changes

2023-11-19 09:29 UTC, MiaInturi requested changes

2023-11-19 09:29 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +        if (data._link) response.set('Link', JSON.stringify(data._link));
Link уже занятый header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link) - мб по другому как-то назовем? (типо Mcs-Link или что-то такое)

2023-11-19 09:29 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +    });
Мне кажется, что правильнее возвращать link инфу только в header, т.к. если возвращать ее еще и в body, то это заставляет пользователя по сути писать обработчик двух вариантов body (а вдруг юзеру вообще не нужна инфа из link и тогда этот обработчик вообще бесполезен будет). А вот если link инфу оставить только в header, то логика на стороне клиента будет простой: есть хэдер/нет хэдера.

2023-11-19 09:29 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +  describe('createNestedDatabaseRoutes: pagination function', () => {
Имхо нужна еще проверка prev-ссылки и хэдера

2023-11-22 05:56 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +  describe('createNestedDatabaseRoutes: pagination function', () => {
prev есть, добавил для ссылки

2023-11-22 09:53 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +    });
такой подход как здесь стандарт, везде так пишут делать https://developer.atlassian.com/server/confluence/pagination-in-the-rest-api/ 
https://dev.to/pragativerma18/unlocking-the-power-of-api-pagination-best-practices-and-strategies-4b49

2023-11-22 15:18 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +    });
Я бы не сказал, что стандарт:
https://docs.github.com/ru/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28#about-pagination

Но думаю можно просто поддержать инфу про pagination и в body и в header

2023-11-22 15:24 UTC, MiaInturi requested changes

2023-11-22 15:24 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +        if (data._link) response.set('mcs-link', JSON.stringify(data._link));
Я думаю, что Link надо вернуть по 2 двум причинам)))
1. Это не пересекается с назначением хэдера Link, т.к. REST всегда передает всю нужную инфу в одном ответе, так что в Link не будут класться ссылки на доп. данные
2. Так делают все

2023-11-25 11:50 UTC, MiaInturi requested changes

2023-11-25 11:50 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/pagination/pagination.ts
> +  const limit = queries._limit && +queries._limit > 0 ? Number(queries._limit) : DEFAULT_LIMIT;
А `+` и `Number()` же одинаковы здесь. Мб стоит что-то одно использовать?

2023-11-25 11:50 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      expect(firstResponseLinks.length).toEqual(3);
Тут можно проитерироваться по результату match и сделать как на строках 273-275

2023-11-25 11:50 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +    test('Should return normal data by invalid pagination data', async () => {
normal => valid. Думаю это более распространенная формулировка

2023-11-25 11:50 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      ]);
А почему именно toMatchObject, а не strictEqual? Он же более жесткую проверку делает

2023-12-10 08:00 UTC, RiceWithMeat approved these changes

2023-12-10 13:01 UTC, anv296 approved these changes

2023-12-10 19:39 UTC, MiaInturi requested changes

2023-12-10 19:39 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      );
А почему мы не хотим проверить польностью весь объект?

2023-12-10 19:39 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +    test('Should return correct _link for paginationed data', async () => {
correct => valid ))

2023-12-13 15:10 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      );
Понял 👍

2023-12-13 15:10 UTC, MiaInturi approved these changes

2023-12-13 16:41 UTC, merged