#124 into release@3.3.0 ☄ test for pagination, readme for pagination
siberiacancode/mock-config-server pull request #125
Opened 2023-11-04 11:53 UTC by debabin

2023-11-15 19:37 UTC, RiceWithMeat approved these changes

2023-11-15 19:37 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +        const { _sort, _order, ...fillters } = request.query;
лишняя l

2023-11-19 07:46 UTC, MiaInturi requested changes

2023-11-19 07:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      ]);
Мб для этого describe сделать хотя бы 3 юзера? Потому что при 2 юзерах всего 2 возможные комбинации ответа и не видно в тесте, что multiple query работает

2023-11-19 07:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/sort/sort.ts
> +  const result = array;
Это не поможет избежать мутации массива после вызова sort т.к. ссылка остается на тот же самый объект (сейчас все работает, потому что filter вызывается до _sort и создает новый экземпляр массива - как только чуть поменять логику вызова filter, то сразу начнутся мутации в db). Тут надо spread делать

2023-11-22 06:17 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +        '/users?_sort=name&_order=acs&_sort=id&_order=desc'
опечатка

2023-11-22 06:19 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/sort/sort.ts
> +      return 0;
ты про датабейз ? или что ты имеешь плоский ?

2023-11-22 06:20 UTC, debabin commented on README.md
> +GET /users?author.name=siberiacancode
лишний копипаст

2023-11-22 06:22 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      ]);
ну тут вопрос, если добавлять то для всех или не для всех и то и то чуть-чуть грязи добавить

2023-11-22 15:06 UTC, MiaInturi commented on README.md
> +GET /users/1/transfers?_sort=id&_order=asc
Мб добавить пример в получением вложенных данных через точку? А то написано, что так можно сделать, а примера нет

2023-11-22 15:07 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      ]);
Ну я бы добавил чисто для этого describe - в остальных же это не нужно

2023-11-23 16:01 UTC, MiaInturi approved these changes

2023-11-24 06:16 UTC, merged