#128 into release@3.3.0 🐘 fix api level interceptors behavior
siberiacancode/mock-config-server pull request #130
Opened 2023-11-19 15:24 UTC by RiceWithMeat

Fixes #128 + small refactoring

2023-12-05 12:07 UTC, debabin requested changes

2023-12-05 12:15 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +  serverResponseInterceptor?: Interceptors['response'];
потому что в таске с логгером сюда ещё добавится необязательный параметр loggers, а это уже 4 параметра и объектом красивее будет

2023-12-05 12:20 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +  serverResponseInterceptor?: Interceptors['response'];
а можешь рассказать как будет выглядить апи для логера

2023-12-05 12:27 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +  serverResponseInterceptor?: Interceptors['response'];
как обсуждали, на самом верху конфига есть объект loggers: {request, response}, в них есть поля enabled, tokens (что хотим видеть в логе) и logFunction (функция, которая принимает все параметры логгера + request + response если это респонс логгер). Можешь подробнее в пр-е глянуть
![image](https://github.com/siberiacancode/mock-config-server/assets/47690223/ba829959-e10b-44e7-a1c9-d8aaa6fcb815)

2023-12-10 13:05 UTC, anv296 approved these changes

2023-12-10 19:52 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +    const graphqlBaseUrl = urlJoin(serverBaseUrl, graphql?.baseUrl ?? '/');
Тут не настаиваю на переделывании, а просто выражаю мнение:
1. А зачем отдельная переменная serverBaseUrl, если для того же graphql отдельная переменная не создается?
2. Допустим переменная serverBaseUrl имеет место быть. Почему такое разделение пустыми строками? Пустые строки нужны для разделения разных смысловых блоков, а serverBaseUrl и graphqlBaseUrl являются единым блоком с точки зрения создания некого baseUrl

2023-12-10 19:52 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    const restBaseUrl = urlJoin(serverBaseUrl, rest?.baseUrl ?? '/');
Тут те же самые вопросы

2023-12-10 19:52 UTC, MiaInturi approved these changes

2023-12-11 14:02 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +    const graphqlBaseUrl = urlJoin(serverBaseUrl, graphql?.baseUrl ?? '/');
в принципе соглы, у `graphql?.baseUrl ?? '/'` нет переменной потому что она бы называлась graphqlBaseUrl, а это название уже и так юзается. Проще убрать тогда serverBaseUrl

2023-12-11 14:05 UTC, merged