#102 into release@3.3.0 🐘 add logger support
siberiacancode/mock-config-server pull request #131
Opened 2023-11-21 11:27 UTC by RiceWithMeat

Resolves #102

2023-12-03 17:24 UTC, RiceWithMeat commented on src/utils/types/logger.ts
> +  body?: boolean;
есть идея превратить этот объект в массив строк, будет занимать меньше места в конфиге + можно менять порядок вывода токенов + можно будет проще описать валидацию этого поля (просто проверить, что все элементы массива === названию entity)

2023-12-03 17:24 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/coloredString/getRestMethodColoredString.ts
> +  if (restMethod === 'options') return c.redBright(restMethod);
есть какие-то предпочтения по цветам для кусочков лога?

2023-12-10 13:19 UTC, anv296 commented on src/utils/helpers/logger/callRequestLogger/callRequestLogger.ts
> +import c from 'ansi-colors';
может colors хотя б написать?

2023-12-12 14:46 UTC, MiaInturi requested changes

2023-12-12 14:46 UTC, MiaInturi commented on src/utils/types/logger.ts
> +  cookies?: any;
А почему any?

2023-12-12 14:46 UTC, MiaInturi commented on src/utils/types/logger.ts
> +  body?: boolean;
Да мне кажется объектом более явно, ну а по поводу проверки, то по сложности это одинаково будет почти (с массивом придется все равно проверять, что это массив, а не что-то другое и т.д.)

2023-12-12 14:46 UTC, MiaInturi commented on src/utils/types/logger.ts
> +  defaultLogFunction: ResponseLogFunction;
А нужен ли этот проп? Просто я не понимаю его цель

2023-12-12 14:46 UTC, MiaInturi commented on src/utils/types/logger.ts
> +  meta: ResponseLoggerMetaTokenFlags<API>;
А мы не хотим сделать какой-то дефолтный набор параметров, который выводится? А то типы захотят добавить логгер, увидят кучу настроек и тильтанут

2023-12-12 14:46 UTC, MiaInturi commented on src/utils/helpers/logger/helpers/formatLogMessage.ts
> +};
Это какая-то временная залушка?

2023-12-12 14:46 UTC, MiaInturi commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +};
У console есть методы group и groupEnd. Можно их использовать, чтобы объединять сущности одного уровня (например entities)

2023-12-12 14:46 UTC, MiaInturi commented on src/core/middlewares/requestInfoMiddleware/requestInfoMiddleware.ts
> +      : null;
operationType и operationName в типе ResponseLogFunctionParams могут быть undefined, хотя по сути не могут

2023-12-12 14:46 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
> +      }
Получается, что requestLogger вызывается независимо от того, был найден нужный конфиг или нет. Мб тогда вызывать его в одном месте, а не в двух?

2023-12-12 14:46 UTC, MiaInturi commented on src/static/views/features/scheme/index.js
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars,no-unused-vars
Тут надо еще убрать первое правило `@typescript-eslint/no-unused-vars`

2023-12-26 09:07 UTC, RiceWithMeat commented on src/core/middlewares/requestInfoMiddleware/requestInfoMiddleware.ts
> +}
нет, на весь проект. Считаю это самым адекватным способом объяснить тс-у, что у нас в реквесте особые поля будут. Без всяких `ts-ignore` и `as`

2023-12-26 09:11 UTC, RiceWithMeat commented on src/utils/types/logger.ts
> +  defaultLogFunction: ResponseLogFunction;
чтобы можно было проще добавить кастом логику к нашим логам. Без этой функции пользователю придётся писать свою функцию-логгер. Допустим пользователь хочет только get запросы логировать, он просто сделает if (params.method === 'get') { defaultLogFunction(params) } и всё

2023-12-26 09:11 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/formatLogMessage.ts
> +};
да, я хотел функцию вынести, но забыл

2024-04-06 13:45 UTC, RiceWithMeat commented on src/utils/types/logger.ts
> +  cookies?: any;
хз, булеан должен быть

2024-04-06 13:53 UTC, RiceWithMeat commented on src/utils/types/logger.ts
> +  meta: ResponseLoggerMetaTokenFlags<API>;
думаю по умолчанию будет true у timestamp, method и url как самые ходовые и полезные токены. А если захотят логи entities например, пробросят их в объекте tokens

2024-04-06 19:37 UTC, RiceWithMeat commented on src/utils/helpers/date/formatUnixTimestamp/formatUnixTimestamp.ts
> +};
заменил эту функцию на нативный toLocaleString

2024-04-06 19:39 UTC, RiceWithMeat commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +};
переписал логику так, что теперь эта функция возвращает объект с токенами, который потом мы один раз console.dir-им

2024-04-06 19:44 UTC, RiceWithMeat commented on src/core/middlewares/requestInfoMiddleware/requestInfoMiddleware.ts
> +      : null;
почему не могут? request.graphQL?.operationType будет undefined т.к. graphQL === null

2024-04-06 19:54 UTC, RiceWithMeat commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
> +      }
от этого дублирования не уйти, если вынести вызов callRequestLogger из createRestRoutes, createGraphQLRoutes и notFoundMiddleware, то придётся добавлять одинаковый интерцептор в createMockServer, createRestMockServer и createGraphQLMockServer

2024-06-02 07:21 UTC, MiaInturi requested changes

2024-06-02 07:21 UTC, MiaInturi commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +};
Мне кажется, что можно упростить апи этой функции - нет смысла передавать все loggerParams, если функции по сути нужны только tokenFlags и tokenValues. И так будет легче понять ее смысл

2024-06-02 07:21 UTC, MiaInturi commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +        unixTimestamp: Date.now(),
request.timestamp?

2024-06-02 07:21 UTC, MiaInturi commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +  console.dir(tokens, { depth: null });
А нормально ли, что дефолтный console и logFunction оба сработают?

2024-06-02 07:21 UTC, MiaInturi commented on src/utils/types/logger.ts
> +}
С подобным типом автодополнение IDE не очень хорошо работает (для REST, например, он предложит graphql свойства, а для request свойства response). Т.к. мы отталкиваемся в первую очередь от удобства использования, а не удобства разработки, то предлагаю сделать 4 типа LoggerTokenValues (request,response - для каждого из них rest и graphql). А из этих 4 типов создать типы LoggerTokenFlags будет совсем просто - это по сути DeepPartial, только типами всех свойств станет boolean

2024-11-28 19:22 UTC, RiceWithMeat commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +};
да, стрингифай страшный ппц по сравнению с dir. добавляются экранирующие кавычки, теряются цвета у строк/чисел и т.д.

.dir(obj, { depth: null })
![image](https://github.com/user-attachments/assets/366a6fe8-2a8d-4d76-88ce-6d9b34352658)

.info(obj, null, 2)
![image](https://github.com/user-attachments/assets/28a20211-a120-4e33-8958-3c8a75e5f543)

2024-11-28 19:26 UTC, RiceWithMeat commented on src/utils/types/logger.ts
> +}
нет, поставил Cookies

2024-11-28 19:28 UTC, RiceWithMeat commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +  console.dir(tokens, { depth: null });
не понял, если прокинуть кастом функцию, мы же только её вызовем

2024-11-28 19:31 UTC, RiceWithMeat commented on bin/run.ts
> +// import { validateMockServerConfig } from './validateMockServerConfig/validateMockServerConfig';
возможно от loggers поля в конфиге вообще откажемся, т.к. log функцию теперь можно доаставать в любом интерцепторе в любом месте конфига. это как раз один из вопросов на завтра

2024-12-20 19:30 UTC, RiceWithMeat commented on bin/run.ts
> +// import { validateMockServerConfig } from './validateMockServerConfig/validateMockServerConfig';
так и получилось. вернул валидацию

2024-12-21 12:23 UTC, RiceWithMeat commented on src/utils/helpers/logger/callRequestLogger/callRequestLogger.test.ts
> +  test('Should return logged token values or null if enabled if false', () => {
i**s** false

2024-12-21 12:23 UTC, RiceWithMeat commented on src/utils/helpers/logger/callRequestLogger/callRequestLogger.test.ts
> +describe('callRequestLogger', () => {
добавить такие же тесты для респонс логгера

2024-12-21 12:23 UTC, RiceWithMeat commented on README.md
> +  - `interceptors?` `Interceptors` functions to change request or response parameters, [read](#interceptors)
поменял формат типов потому что md считает дженерики за кастомные элементы и скрывает их. Например сейчас у configs тип Array, без дженерика. Но если обернуть в косые кавычки - то отображает норм

2024-12-22 11:39 UTC, RiceWithMeat commented on src/utils/types/server.ts
>  }
пока нет, потому что у датабейза нет интерцепторов

2024-12-22 12:44 UTC, RiceWithMeat commented on src/core/middlewares/requestInfoMiddleware/requestInfoMiddleware.ts
> +  });
1,2,3 поправил.
4. нужен, чтобы потом можно было из любого места достать таймштамп, в том числе в логгере

2024-12-23 13:36 UTC, debabin commented on src/core/middlewares/contextMiddleware/contextMiddleware.ts
> +        : null;
мне кажется такое поведение должно быть в грайфкл миддлетваре

2024-12-23 13:36 UTC, debabin commented on src/core/middlewares/contextMiddleware/contextMiddleware.ts
> +    request.graphQL =
if (graphQLInput.query && graphQLQuery) {
 request.graphQL = ...
}

2024-12-23 13:36 UTC, debabin commented on src/utils/helpers/logger/callRequestLogger/callRequestLogger.ts
> +export const callRequestLogger = ({ logger, request }: CallRequestLoggerParams) => {
функции слишком похожие все таки, можем ли все таки попробовать сделать 1 ? Я думаю можно кидать в нее всегда request response + флаг мб или типо того

2024-12-23 13:36 UTC, debabin commented on src/utils/helpers/logger/helpers/filterTokenValues/filterTokenValues.ts
> +type TokenObjectOptions = Record<string, boolean>;
опять же вопрос, а что с боди, можно ли написать 
```ts
body: {
  value: {
      profile: true
   }
}
```

2024-12-23 13:36 UTC, debabin commented on src/utils/helpers/logger/helpers/filterTokenValues/filterTokenValues.ts
> +type TokenObjectOptions = Record<string, boolean>;
я просто думаю, что можно это сделать и просто сделать снизу как обычно flat

2024-12-23 13:36 UTC, debabin commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +  if (logger?.enabled === false) return null;
тут вопрос, а что у нас logger по дефалту, просто я думаю logger false по дефалту, но тут если например logger нет, то код пойдет дальше

2024-12-23 13:36 UTC, debabin commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +export const callResponseLogger = ({
А еще нужно описать zod для logger

2024-12-23 13:36 UTC, debabin commented on src/utils/helpers/logger/helpers/filterTokenValues/filterTokenValues.ts
> +export const filterTokenValues: FilterTokenValues = (rawTokenValues, tokenOptions) =>
И мне не нравится чот названия в итоге

Вот есть logger, в логере мы можем указать tokens, который уже содержит tokenName и tokenValue, который может быть object. Вроде бы так более clean, а то тут очень много лишних слов, ну или вместо токенс сразу просто options и все тоже самое

2024-12-23 15:44 UTC, RiceWithMeat commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +  if (logger?.enabled === false) return null;
снёс по итогу этот флаг. если пользователь захочет по условию включать выключать логи по каким-то особым условиям (если заролял особый кейс например), то всё равно придётся это писать в интерецепторах

2024-12-23 16:04 UTC, RiceWithMeat commented on src/utils/helpers/logger/index.ts
> +export * from './callResponseLogger/callResponseLogger';
не понял вопроса. У нас же сейчас по сути всё нужно. если logger это core, то и interceptors тоже

2024-12-23 16:06 UTC, RiceWithMeat commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +export const callResponseLogger = ({
не понял, логгер это же просто функция, которую достают из params в интерцепторах и вызывают. Это не поле, которое нужно валидировать

2024-12-23 16:18 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokenValues/filterTokenValues.ts
> +type TokenObjectOptions = Record<string, boolean>;
сейчас body может быть только boolean и залогается полностью (если не писать rewrite, с ним что угодно можно сделать).

body получается будет особняком, потому что это не  mappedEntity, у него может быть любое количество вложенностей + вопрос как логику blacklist/whitelist обрабатывать.

можно в конце функции дописать, что если `tokenName==='body' && (Array.isArray(tokenOption) || isPlainObject(tokenOption))` то при помощи flatten достань нужные поля, у которых указан true. 

Норм план?

2024-12-23 16:24 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokenValues/filterTokenValues.ts
> +export const filterTokenValues: FilterTokenValues = (rawTokenValues, tokenOptions) =>
если переименовать tokenOptions в tokens, то тогда теряется приемственность с tokenValues. tokenValues и tokenOptions по сути копии и различаются только тем, что у tokenOptions в значениях boolean, а у tokenValues реальные значения.

Или я не понял

2024-12-23 16:28 UTC, RiceWithMeat commented on src/utils/helpers/logger/callRequestLogger/callRequestLogger.ts
> +export const callRequestLogger = ({ logger, request }: CallRequestLoggerParams) => {
сделать можно, но тогда придётся добавлять response аргумент ещё в callRequestInterceptor, что чота не оч звучит. Зачем в реквест интерцепторе респонс.

Плюс на моменте где мы вызываем реквест интерцепторы, респонс ещё не имеет поля, которые можно залогать (statusCode и data). Получается в случае когда вызываем request log, просто так прокидываем response и новый параметр "это реквест лог или респонс лог".

И ещё тесты для callRequestInterceptor немного править. Стоит ли оно того?

2024-12-23 16:32 UTC, RiceWithMeat commented on src/core/middlewares/contextMiddleware/contextMiddleware.ts
> +        : null;
предлагаешь в отдельную мидлварь вынести (вызываться будет сразу после contextMiddleware), в которой будет только эта логика с графкл?

2024-12-26 12:16 UTC, RiceWithMeat commented on src/utils/helpers/logger/index.ts
> +export * from './callResponseLogger/callResponseLogger';
сделал ишью

2024-12-26 14:27 UTC, MiaInturi requested changes

2024-12-26 14:27 UTC, MiaInturi commented on src/core/middlewares/contextMiddleware/contextMiddleware.ts
Не хватает тестов на этот файл

2024-12-26 14:27 UTC, MiaInturi commented on src/core/middlewares/contextMiddleware/contextMiddleware.ts
> +        operationName: graphQLQuery.operationName as GraphQLOperationName,
не обязательно, что operationName будет всегда (в типизации отписал подробнее)

2024-12-26 14:27 UTC, MiaInturi commented on src/utils/types/interceptors.ts
> +  log: (logger?: Logger<'request'>) => Partial<LoggerTokenValues> | null;
А когда функция возвращает null?

2024-12-26 14:27 UTC, MiaInturi commented on README.md
> +- `variables`: `Record<string, any>` GraphQL variables. `null` if request is not GraphQL or variables is not passed
это описание расходится немного с тем, что описано в contextMiddleware

2024-12-26 14:27 UTC, MiaInturi commented on README.md
> +If you need to log specific mapped entities (headers, cookies, query, params), use `Record<string, boolean>` object instead of boolean.
`If you need to log specific properties in mapped entities` - я думаю надо указать, что именно определенные свойства объектов

2024-12-26 14:27 UTC, MiaInturi commented on README.md
> +- if some token is `false`, entity will be filtered by `blacklist` logic. All entities will be logged *except* disabled ones.
про false не some, а all

2024-12-26 14:27 UTC, MiaInturi commented on README.md
> +```
Имхо это вообще не нужно, т.к. выше уже все описано про whitelist и blacklist

2024-12-26 14:47 UTC, debabin commented on src/utils/types/logger.ts
> +  graphQLOperationType: GraphQLOperationType | null;
вообще кстати дыа, хороший вопрос

2024-12-26 17:28 UTC, debabin commented on src/utils/helpers/logger/helpers/filterTokenValues/filterTokenValues.ts
> +export const filterTokenValues: FilterTokenValues = (rawTokenValues, tokenOptions) =>
а там по дефалту же если задаешь не будет показывать все же, а только то что ты выбрал не ? @RiceWithMeat

2024-12-26 17:34 UTC, debabin commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +  const filteredTokenValues = filterTokenValues(rawTokenValues, tokenOptions);
на самом деле я посидел и посмотрел код и названия tokenValues норм, только нужно убрать raw и в типизации указать не просто PlainObject, а LoggerTokenValues<'response'> | LoggerTokenValues<'request'> же ? или я не прав

2024-12-30 14:47 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/formatTokenValues/formatTokenValues.ts
> +  };
нет, timestamp и method есть всегда. Такая запись тут только чтобы отформатировать их

2024-12-30 14:47 UTC, RiceWithMeat commented on src/utils/types/graphql.ts
> -};
да

2024-12-30 14:55 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokenValues/filterTokenValues.ts
> +export const filterTokenValues: FilterTokenValues = (rawTokenValues, tokenOptions) =>
я думал о том, чтобы на первом уровне поддержать blacklist логику, но понял, что это юзлесс. Токенов слишком много чтобы хотеть видеть их все кроме пары лишних. Например большинству не нужны будут три graphql токена, а только timestamp и url например. Это проще будет написать как timestamp: true, url: true, чем все токены false

2024-12-30 14:56 UTC, RiceWithMeat commented on src/utils/types/interceptors.ts
> +  log: (logger?: Logger<'request'>) => Partial<LoggerTokenValues> | null;
уже никогда, возвращался null когда log не вызывался из-за enabled: false.
убрал

2024-12-30 15:04 UTC, RiceWithMeat commented on src/utils/types/logger.ts
> +  rewrite?: (tokenValues: Partial<LoggerTokenValues<Type, API>>) => void;
потому что rewrite получает не не все токены, а только те, которые были указаны в tokenOptions

2024-12-30 15:08 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokenValues/filterTokenValues.ts
> +export const filterTokenValues: FilterTokenValues = (rawTokenValues, tokenOptions) =>
давайте обсудим

2024-12-30 15:25 UTC, RiceWithMeat commented on src/utils/types/logger.ts
> +  graphQLOperationType: GraphQLOperationType | null;
любой graphql токен будет null если залогать его для рест запроса. сейчас сделал так, что в rest interceptors нельзя залогать graphql токены. Но т.к. есть глобальные интерцепторы, то от этого не уйти

2024-12-30 15:27 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokenValues/filterTokenValues.ts
> +export const filterTokenValues: FilterTokenValues = (rawTokenValues, tokenOptions) =>
как идея можно внести нейминг tokenName, tokenValue, tokenFlag/tokenEnabled, tokenValueByName, tokenEnabledByName. Так сразу будет понятно где мапа, а где просто value

2024-12-30 15:36 UTC, RiceWithMeat commented on README.md
> +- `variables`: `Record<string, any>` GraphQL variables. `null` if request is not GraphQL or variables is not passed
здесь идёт речь конкретно чему будут равны graphql токены в сообщении логгера. Все graphql токены становятся null, если в context.graphql === null

2025-01-02 10:08 UTC, debabin commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +  };
пусть будет просто tokens и будет как у нас в другом месте loggerTokens и loggerOptions я думаю лучше вот так сделать

2025-01-02 10:08 UTC, debabin commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.ts
> +  const rawTokenValues: LoggerTokenValues<'response'> = {
LoggerTokenValues -> LoggerTokens 
LoggerTokenOptions-> LoggerOptions

2025-01-03 19:38 UTC, RiceWithMeat commented on src/utils/types/logger.ts
> +};
переименовал тип и сделал PlainObject

2025-01-05 09:10 UTC, RiceWithMeat commented on README.md
> +```
Я бы оставил, а то до этого есть пример кода, а тут вдруг нет

2025-01-05 11:03 UTC, MiaInturi commented on README.md
> +- `tokens` `LoggerOptions` object map containing tokens to log. Keys is token names, values is boolean. `true` will add token into log, `false` will remove. If `tokens` is not passed, following token
Этот параметр должен называться options видимо

2025-01-05 11:03 UTC, MiaInturi commented on README.md
> +                  tokens: {     // response get: http://localhost:31299/api/rest/posts/1 => 200
отступы у комментов немного поехали

2025-01-05 11:06 UTC, RiceWithMeat commented on src/utils/types/logger.ts
> +  tokens?: LoggerOptions<Type, Api>;
мне тож это не нравится расхождение в нейминге, но намеренно назвал tokens чтобы явно сказать "укажи токены", а не абстрактные опции

2025-01-05 11:10 UTC, RiceWithMeat commented on README.md
> +    - `logger` `Logger | undefined` logger options
1. не может, поправил
2. тру, поправил

2025-01-05 11:28 UTC, RiceWithMeat commented on README.md
> +- `rewrite` `(tokens: Partial<LoggerTokens>) => void` function to replace default `console.dir(tokens, { depth: null })` appearance
да вроде по `object map containing tokens to log` и так понятно, что в объекте не обязательно надо все возможные токены указывать

2025-01-05 11:35 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.ts
> +            }
если body будет примитивом, то мы же только один раз достанем из него ключ и он будет undefined. я код не смог сломать. Но на всякий добавил проверку, чтобы actual token тоже был объектом. мало ли потом стрельнет

2025-01-05 11:37 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.ts
> +      const objectTokenValues = tokenValue;
убрал

2025-01-05 11:39 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.test.ts
> +    });
первая это когда все токены true, а вторая чекает что всё равно будет whitelist если вместе передать true и false

2025-01-05 11:40 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.test.ts
поправил

2025-01-05 11:40 UTC, RiceWithMeat commented on README.md
> +- `tokens` `LoggerOptions` object map containing tokens to log. Keys is token names, values is boolean. `true` will add token into log, `false` will remove. If `tokens` is not passed, following token
мне тож это не нравится расхождение в нейминге, но намеренно назвал tokens чтобы явно сказать "укажи токены", а не абстрактные опции

2025-01-05 11:44 UTC, RiceWithMeat commented on src/utils/types/interceptors.ts
>  ) => any;
поправил

2025-01-05 11:47 UTC, RiceWithMeat commented on README.md
> +- `rewrite` `(tokens: Partial<LoggerTokens>) => void` function to replace default `console.dir(tokens, { depth: null })` appearance
добавил в список всех токенов вопросики

2025-01-05 11:57 UTC, RiceWithMeat commented on src/utils/helpers/logger/callResponseLogger/callResponseLogger.test.ts
> +    vi.spyOn(Date, 'now').mockImplementation(() => 1735623296789);
поправил

2025-01-05 12:08 UTC, debabin approved these changes

2025-01-05 12:08 UTC, MiaInturi commented on README.md
> +- `rewrite` `(tokens: Partial<LoggerTokens>) => void` function to replace default `console.dir(tokens, { depth: null })` appearance
Я имел в виду что `rewrite?`, `tokens?`

2025-01-05 12:17 UTC, RiceWithMeat commented on README.md
> +- `rewrite` `(tokens: Partial<LoggerTokens>) => void` function to replace default `console.dir(tokens, { depth: null })` appearance
пон, поправил

2025-01-05 12:18 UTC, MiaInturi requested changes

2025-01-05 12:18 UTC, MiaInturi commented on README.md
> +    - `logger` `Logger | undefined` logger options
Тут надо убрать  `| null` + LoggerTokenValues заменить на LoggerTokens

2025-01-05 12:18 UTC, MiaInturi commented on README.md
> +- `rewrite` `(tokens: Partial<LoggerTokens>) => void` function to replace default `console.dir(tokens, { depth: null })` appearance
Если tokens назван так намеренно, то все равно мне не заходит из-за этого, что `tokens` в качестве опций это объект вида `{ [key]: boolean }`. А в аргументе функции rewrite это объект вида `{ [key]: ${тут значение ключа} }`. 

Т.е. два соседствующих объекта названы одинаково, но представляют собой разные вещи.

И это вносит непонятность как по мне бОльшую, нежели название `options` для первого аргумента

2025-01-05 12:19 UTC, RiceWithMeat commented on README.md
> +    - `logger` `Logger | undefined` logger options
поправил

2025-01-05 12:35 UTC, MiaInturi approved these changes

2025-01-05 12:35 UTC, MiaInturi commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.ts
> +      const tokenObjectOptionsFilterMode = resolveTokenObjectOptionsFilterMode(option);
а это не должно называться objectOptionFilterMode? Если префиксы везде убрали

2025-01-05 12:35 UTC, MiaInturi commented on README.md
> +                  options: {           // {
тут пробельчики съехали))

2025-01-05 12:35 UTC, MiaInturi commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.ts
> +        acc[name] = Object.entries(option).reduce((acc, [name, objectTokenOption]) => {
`objectTokenOption`
1. А почему везде ушла приписка token, а тут осталась?
2. Мб назвать тогда nestedOption? Раз сверху название просто option

2025-01-05 12:35 UTC, MiaInturi commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.ts
После этого я еще больше стал топить за no-shadow)))

2025-01-05 12:38 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.ts
> +      const tokenObjectOptionsFilterMode = resolveTokenObjectOptionsFilterMode(option);
поправил

2025-01-05 12:47 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.ts
если ты про параметр name, то хз как его обозвать. это не nestedOptionName потому что name есть только у токенов и не nestedTokenName потому что nested может быть только option, а не токен

2025-01-05 12:47 UTC, RiceWithMeat commented on src/utils/helpers/logger/helpers/filterTokens/filterTokens.ts
> +        acc[name] = Object.entries(option).reduce((acc, [name, objectTokenOption]) => {
1. поправил
2. согл

2025-01-05 12:51 UTC, merged