#137 into release@4.0.0 ☄ add delay and status settings
siberiacancode/mock-config-server pull request #138
Opened 2024-01-08 14:44 UTC by debabin

2024-02-19 16:10 UTC, MiaInturi requested changes

2024-02-19 16:10 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +  test('Should correctly set statusCode into response with status setting', async () => {
По поводу теста на delay. 
Можно сделать что-то подобное
```typescript
const startTime = Date.now();
await request(server).get('/').query(query);
const endTime = Date.now();
expect(endTime - startTime).toBeGreaterThanOrEqual(delay);
```

2024-02-23 16:09 UTC, RiceWithMeat approved these changes

2024-02-23 16:09 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    const startTime = Date.now();
вычитал, что что performance.now() в 10 раз точнее Date.now() (1 мс против 0.1 мс), но при этом в 2-4 раза медленнее в зависимости от браузера. Звучит так, что performance.now не нужен, так как мы не оперируем настолько маленькими промежутками времени☝️🤓

2024-02-23 18:11 UTC, MiaInturi requested changes

2024-02-23 18:11 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
>          configs: [
Тест на empty queue для `src/core/rest/createRestRoutes/createRestRoutes.test.ts`, лежит в дескрайбе `createRestRoutes: settings`, а для файла `src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts` тест нра empty queue лежит в `createRestRoutes: content` - то есть надо привести к одному виду, где у нас лежит тест на empty queue (мне больше нравится content, т.к. в дескрайбе settings все же должны проверяться именно настройки)

2024-02-23 18:11 UTC, MiaInturi commented on bin/validateMockServerConfig/validateSettings/validateSettings.ts
> +      (typeof setting === 'number' && !(setting >= 200 && setting <= 599)))
`typeof setting !== 'number' || (typeof setting === 'number' && !(setting >= 200 && setting <= 599)` - во вторых скобках проверка `typeof setting === number` бесполезная, т.к. если setting не number, то первое условие будет верным и второе условие не сработает исходя из логики работы оператора `||`

2024-02-23 18:11 UTC, MiaInturi commented on bin/validateMockServerConfig/validateSettings/validateSettings.test.ts
> +    });
Еще в качестве проверяемых значений мы кидаем пустые объекты `{}`

2024-02-24 15:31 UTC, MiaInturi approved these changes

2024-02-25 06:01 UTC, merged