#139 into release@4.0.0 ☄ add full search for database
siberiacancode/mock-config-server pull request #140
Opened 2024-01-09 13:09 UTC by debabin

2024-03-02 06:17 UTC, MiaInturi requested changes

2024-03-02 06:17 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.test.ts
> +  describe('createShallowDatabaseRoutes: filter function', () => {
Надо еще добавить проверку, что если запрашиваемый ресурс не является массивом, то ничего не происходит - возвращается тот же самый ресурс без каких-либо изменений

2024-03-09 16:26 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +        const { _page, _limit, _begin, _end, _sort, _order, q, ...filters } = request.query;
все с _ префиксом, а q нет. поч?

2024-03-09 16:26 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/search/search.ts
> +    }
нужны ли эти else? во всех if-ах же return и если проверка будет true, то код до следующего else просто не дойдёт. А если false, то стопроц дойдёт

2024-03-18 15:15 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/search/search.ts
> +  for (const key in obj) {
Но возможен кейс, что в массиве будут примитивы например 

database: { data: {prop: ['dima', 'vova'] } }

доделал функцию

2024-03-18 15:18 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/search/search.ts
> +};
я сделал всегда toString просто, не знаю зачем сделал только number и string

2024-03-24 09:08 UTC, RiceWithMeat approved these changes

2024-03-24 09:08 UTC, RiceWithMeat commented on README.md
> +> Add q parameter for search data, search can be done by strings and numbers
здесь _ не хватает

2024-03-24 09:15 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/search/search.ts
> +};
А что если будет null, unedfined ?

2024-03-25 14:46 UTC, MiaInturi requested changes

2024-03-25 14:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      test(`Should search data by ${correctSearchValue} query with type ${typeof correctSearchValue}`, async () => {
тут для null `typeof correctSearchValue` вернет object - не хотим это обработать?

2024-03-25 14:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
> +      test(`Should search data by ${correctSearchValue} query with type ${typeof correctSearchValue}`, async () => {
Should search data by "${correctSearchValue}" query - добавились кавычки, а то может странно смотреться что-то типа: `Should search data by true query` или `by 3000 query`

2024-03-25 14:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/search/search.ts
> +  return false;
Этот код можно превратить в 
```typescript
if (typeof obj[key] === 'object' && obj[key] !== null) {
      return searchInNestedObjects(obj[key], searchText);
  }
  return String(obj[key]).includes(searchText)
```

2024-03-25 14:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +      }
Хэлперы filter и sort внутри себя используют flatten, которые не работают с null и undefined, т.е. подобный конфиг упадет
```typescript
const mockServerConfig: MockServerConfig = {
  database: {
    data: {
      shallow: [null]
    }
  }
};
```

2024-03-25 14:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.test.ts
> +    ],
Т.к. это shallowDatabase, то внутри массива может лежать и примитив. Думаю надо в массив добавить строку и null и посмотреть, что упадет

2024-03-25 14:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.test.ts
> +    ],
https://github.com/siberiacancode/mock-config-server/pull/140#discussion_r1537713809

2024-03-25 17:20 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/search/search.ts
> +  return false;
Прям так нельзя, еслинт ругается вот тут (typeof obj[key] === 'object' && obj[key] !== null) {
      return searchInNestedObjects(obj[key], searchText);
  }

https://eslint.org/docs/latest/rules/no-unreachable-loop

2024-03-25 17:23 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/search/search.ts
> +  return false;
Плюс нельзя так сделать, второе условие говорит сейчас, если совпало то верни тру, а если мы сделаем return String(), то выйдем из for сразу с первого раза

2024-03-25 17:44 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +      }
Понял, завтра обсудим, есть буквально 2 варианта

2024-03-31 09:37 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +      }
сделал фильтрации перед функциями

2024-03-31 15:58 UTC, RiceWithMeat approved these changes

2024-04-01 13:27 UTC, MiaInturi requested changes

2024-04-01 13:27 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +      data = data.filter((element) => typeof element === 'object' && element !== null);
В nested такие условия невозможны, там всегда это массив, у которого все элементы с id

2024-04-01 13:27 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +      }
Мне не очень заходит идея, что если имеется массив, то мы сразу убираем оттуда null -  даже если не было никаких query-параметров. Типо юзер сделает запрос на урл `/something-array`, а у него null все пропали и не понятно почему. Имхо, фильтрация должна быть после проверки на то, что request.query есть. Ну и дописать в readme, что в случае функций в query мы не обрабатываем null

2024-04-01 16:59 UTC, RiceWithMeat approved these changes

2024-04-01 17:00 UTC, MiaInturi approved these changes

2024-04-01 17:00 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +      }
Условия можно объединить через `||`

2024-04-01 17:00 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +      }
Так же можно объединить условия

2024-04-01 18:09 UTC, merged