#132 into release@4.0.0 ☄ init cli, change bin run script, change readme
siberiacancode/mock-config-server pull request #143
Opened 2024-01-21 09:17 UTC by debabin

2024-03-02 08:50 UTC, MiaInturi requested changes

2024-03-02 08:50 UTC, MiaInturi commented on bin/init.ts
> +          message: 'Base url:',
Думаю надо в скобочках еще дописать (Must start with a forward slash)

2024-03-02 08:50 UTC, MiaInturi commented on bin/init.ts
> +        : 'npm';
Я не знаю про остальные пакетные менеджеры, но npm запускает пакеты через команду `npx` начиная с версии 5.2.0 https://stackoverflow.com/questions/9679932/how-to-use-executables-from-a-package-installed-locally-in-node-modules

2024-03-02 08:50 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
>        expect(firstResponseLinks.length).toEqual(3);
Мне кажется проще написать `expect(firstResponseLinks?.length).toEqual(3);` и тогда expect не сработает в случае, если match вернет null

2024-03-02 08:50 UTC, MiaInturi commented on bin/run.ts
> +      (!mergedMockServerConfig.rest || !mergedMockServerConfig.graphql) &&
Мне кажется, что вместо `||` тут должно быть `&&`, т.к. не должна допускаться след. ситуация
```typescript
const config = {
   rest: {...},
   configs: [...]
}
```

2024-03-02 08:50 UTC, MiaInturi commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
А эта ветка условий вообще возможна? Разве мы не должны тут выкидывать исключение?

2024-03-02 08:50 UTC, MiaInturi commented on bin/validateMockServerConfig/validateApiMockServerConfig.ts
> +      }
А если в configs[0] не будет ни path, ни operationName, ни query? Тогда configs по сути невалидный, но при этом мы не провалидируем его

2024-03-02 14:15 UTC, debabin commented on bin/cli.ts
> +      })
Статик path может быть сложным, а не просто строкой, думаешь стоит ?

2024-03-02 14:16 UTC, debabin commented on .gitignore
> +mock-server-build
косяк мой, удалил

2024-03-02 14:19 UTC, debabin commented on bin/helpers/renderTemplate.ts
> +  }
сделал просто условие, что если порт человек указал

2024-03-02 14:21 UTC, debabin commented on mock-requests/graphql/index.ts
мой факап, удалил

2024-03-02 16:04 UTC, debabin commented on bin/init.ts
> +        : 'npm';
не совсем понял твое предложение тут

2024-03-02 16:05 UTC, debabin commented on bin/helpers/renderTemplate.ts
> +  }
тоже самое с baseUrl

2024-03-02 19:14 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.test.ts
>        expect(firstResponseLinks.length).toEqual(3);
это не поможет, потому-что ниже мы спредим массив с ссылками и там тоде будет проблема с типизацией

2024-03-02 19:17 UTC, debabin commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
Да тут кейс следующий, у нас есть database и staticPath, мы можем запустить сейчас сервер без configs, rest или graphql, тогда по дефалту считаем, что это был rest

2024-03-03 04:49 UTC, MiaInturi commented on bin/cli.ts
> +      })
Ну мы же можем указать строковый staticPath при запуске мока, думаю тут тоже как минимум лишним не будет

2024-03-03 04:51 UTC, MiaInturi commented on bin/init.ts
> +        : 'npm';
Я имел в виду, что если у человека пакетный менеджер npm, то команду для запуска ему выдаст `npm mcs` - и она не сработает, т.к. теперь команды запускаются через `npx`

2024-03-03 06:21 UTC, MiaInturi requested changes

2024-03-03 06:21 UTC, MiaInturi commented on bin/helpers/createTemplate.ts
> +  fs.cpSync(`${templatePath}/mock-requests`, `${APP_PATH}/mock-requests`, { recursive: true });
Не думаешь, что сюда кроме флага recursive надо еще прокинуть флаг force?

2024-03-03 06:21 UTC, MiaInturi commented on bin/helpers/createTemplate.ts
> +interface RenderTemplateOptions {
Забыл переименовать тип - осталось слово Render

2024-03-03 06:21 UTC, MiaInturi commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
А мб тогда тут больше подходит вызов функции `startDatabaseMockServer`? И тогда код станет понятнее гораздо

2024-03-03 07:47 UTC, debabin commented on bin/helpers/createTemplate.ts
> +  fs.cpSync(`${templatePath}/mock-requests`, `${APP_PATH}/mock-requests`, { recursive: true });
Да хороший совет, чтобы всегда переписывалось

2024-03-03 07:48 UTC, debabin commented on bin/init.ts
> +        : 'npm';
хм, вообще надо бы проверить + npm run mcs наверное надо писать

2024-03-03 07:49 UTC, debabin commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
database может быть в любом моке, у нас просто по дефалту если ничего нет то rest

2024-03-03 07:51 UTC, MiaInturi commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
Ну типо вот это и не вяжется, что по сути когда код доходит до сюда, то у нас database + staticPath, а вызывается почему то rest

2024-03-04 16:34 UTC, debabin commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
нет стой, тут может и не быть database | staticPath

2024-03-04 16:35 UTC, debabin commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
ситуация например с конфигом вида 

```ts
const mockServerConfig = {
  port: 31299,
  baseUrl: '/',
  configs: []
};
```

мы тут не можем определить что это за сервер поэтому по дефалту делаем rest

2024-03-08 15:20 UTC, MiaInturi requested changes

2024-03-08 15:20 UTC, MiaInturi commented on bin/helpers/createTemplate.ts
> +    mockServerConfig = mockServerConfig.replace(/baseUrl: '\/'/, `baseUrl: '${options.baseUrl}'`);
Тут опять же не нужен RegExp

2024-03-08 15:20 UTC, MiaInturi commented on bin/init.ts
> +        : 'npm';
Я попробовал через npm run - и это тоже не работает, так что думаю npx это единственно верное решение здесь

2024-03-08 15:22 UTC, MiaInturi commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
Понял, закрываю тред

2024-03-08 15:30 UTC, MiaInturi requested changes

2024-03-08 15:30 UTC, MiaInturi commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
Закрыл старый тред, но открыл новый) По сути с такой логикой, как описаны сейчас ф-ии `bin/run.ts` и `validateApiMockServerConfig.ts`, у нас могут быть пропущены невалидные configs как здесь:
```typescript
const restMockServerConfig = {
  port: 31299,
  baseUrl: '/',
  configs: [
    {
      unexpected: 'property'
    }
  ]
};
```

2024-03-09 09:38 UTC, debabin commented on bin/init.ts
> +        : 'npm';
овер странно конечно, я брал это из реальной какой-то библы, поменял на npx

2024-03-09 10:54 UTC, debabin commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
Почему ? мы же если не определимся запускаем валидацию для rest

2024-03-09 10:56 UTC, debabin commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
![image](https://github.com/siberiacancode/mock-config-server/assets/45297354/e470aa1b-04df-44ea-b389-2883d32825be)

2024-03-09 15:50 UTC, MiaInturi requested changes

2024-03-09 15:50 UTC, MiaInturi commented on bin/helpers/createTemplate.ts
> +    new RegExp(`port: ${DEFAULT.PORT}`),
Тут RegExp лишний

2024-03-09 15:50 UTC, MiaInturi commented on bin/run.ts
> +      return startRestMockServer(mergedApiMockServerConfig as RestMockServerConfig);
а, да, проглядел

2024-03-09 16:04 UTC, RiceWithMeat commented on bin/helpers/createTemplate.ts
> +  }
тут не понял почему на порт завязываемся. Выше же порт уже реплейсим и тут ничего не заменится

2024-03-09 16:44 UTC, debabin commented on bin/init.ts
> +    console.log(`start command: ${color.bold(color.green(`${packageManager} mcs`))}`);
тут специально сделал с маленькой

2024-03-09 16:47 UTC, debabin commented on bin/helpers/createTemplate.ts
> +  }
поменял последовательность

2024-03-09 17:00 UTC, MiaInturi approved these changes

2024-03-10 09:39 UTC, anv296 commented on bin/cli.ts
> +      ...initOptions,
честно, не вижу смысла в выносе ради выноса или это для чего-то будущего?

2024-03-10 09:39 UTC, anv296 approved these changes

2024-03-10 16:25 UTC, merged