#133 into release@4.0.0 👹 add new config validation (using zod)
siberiacancode/mock-config-server pull request #144
Opened 2024-01-27 15:23 UTC by MiaInturi

2024-02-23 15:30 UTC, debabin requested changes

2024-02-23 15:30 UTC, debabin commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.test.ts
> +                checkMode: 'equals',
А не нужны ли тесты на кейсы exist и notExist ?

2024-02-24 15:59 UTC, MiaInturi commented on bin/newValidateMockServerConfig/utils/nonRegExpSchema/nonRegExpSchema.ts
> +  z.custom((value) => !(value instanceof RegExp)).pipe(schema);
Эта кастомная схема сделана из-за того, что zod воспринимает regexp как пустой объект. Т.е. `z.object().parse(/\d/)` вернет true.
Из-за подобной особенности такая ошибка стреляет в случаях, когда некоторый объект состоит целиком из опциональных свойств (например, interceptors с типом `{ request?: ..., response?: ... }`). Такая типизация позволяет передавать пустые объекты и если не добавить обертку `nonRegExpSchema`, то пользователь по сути сможет прокинуть regexp туда, где возможен пустой объект

2024-02-24 16:00 UTC, MiaInturi commented on src/utils/types/entities.ts
> +type NonCheckMode<T extends object> = T & { checkMode?: never };
Там был бак из-за того, что `{ checkMode: never }` - т.е. checkMode по сути был обязательным, однако не мог принять никакое из значений. Здесь же checkMode стал необязательным. А `never` я добавил, чтобы явно показать, что это свойство не должно передаваться

2024-02-24 16:34 UTC, MiaInturi commented on examples/.eslintrc.js
> +const { eslint } = require('@siberiacancode/eslint');
Отвечу отдельно про tsconfig и отдельно про eslint:
1. tsconfig отдельно я сделал, потому что папка examples - это по сути мир с отдельным ts-alias `"mock-config-server": ["./dist"]` . Данный alias нужен только в этой папке, а этой папке в свою очередь нужен только один alias. Поэтому чтобы этот alias не мозолил глаза в обычной части проекта я для папки examples создал отдельный tsconfig оставив там только один единственный нужный alias.
2. т.к. теперь tsconfig для обычного проекта и для examples разные (различаются alias, emit и include опции) - то и eslint конфиги должны быть разные (ведь при их настройке мы указываем с каким tsconfig они должны быть синхронизированы)

2024-02-25 14:02 UTC, MiaInturi commented on src/utils/types/server.ts
> +export interface MockServerConfigArgv extends Arguments {
![Снимок экрана 2024-02-24 231351](https://github.com/siberiacancode/mock-config-server/assets/39031929/88c61a88-f482-4dbb-8180-72d033bf8fe6)
не, тут все правильно по типизации - мне надо было добавить в типизацию свойства `_` и `$0`. Единственное, что мб было бы правильнее написать 
```typescript
interface MockServerConfigArgv = Arguments<{
  baseUrl?: string;
  port?: number;
  staticPath?: string;
  config?: string;
  watch?: boolean;
}>
```

2024-03-10 09:28 UTC, anv296 approved these changes

2024-03-10 17:16 UTC, RiceWithMeat commented on bin/newValidateMockServerConfig/utils/jsonSchema/jsonSchema.ts
> +export const jsonLiteralSchema = z.union([z.string(), z.number(), z.boolean(), z.null()]);
Вкусовщина эта константа перед типами должна быть. До использования в z.infer

2024-03-10 17:16 UTC, RiceWithMeat commented on bin/newValidateMockServerConfig/utils/jsonSchema/jsonSchema.ts
> +    z.record(jsonSchema).and(z.custom((value) => isPlainObject(value)))
Можно попробовать убрать

2024-03-10 17:16 UTC, RiceWithMeat commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
> +    if (!parseResult.success) {
Это чисто чтобы по типизации .error появился?

2024-03-10 17:16 UTC, RiceWithMeat commented on bin/newValidateMockServerConfig/validateMockServerConfig.ts
> +      `Validation Error: configuration${validationMessage} does not match the API schema. Click here to see correct type: https://github.com/siberiacancode/mock-config-server`
Ведём то на нпм, то на гмтхаб. Мб одно оставим?

2024-03-10 18:14 UTC, MiaInturi commented on jest.config.js
> +  collectCoverage: false,
Забыл вернуть)

2024-03-17 16:42 UTC, debabin requested changes

2024-03-17 16:42 UTC, debabin commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
> +      if (body.checkMode === 'exists' || body.checkMode === 'notExists') {
А здесь не нужно использовать нашу константу CHECK_ACTUAL_VALUE_CHECK_MODES

2024-03-17 16:42 UTC, debabin commented on src/utils/types/entities.ts
> +type NonCheckMode<T extends object> = T & { checkMode?: never };
Я тут тупанул, тут все ок и даже не понимаю почему мы сразу не сделали просто 

    : Check extends CheckActualValueCheckMode
    ? {
        checkMode: Check;
      }

У нас же там value?: undefined стоит вроде бы

2024-03-17 16:42 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/helpers/prepareGraphQLRequestConfigs/prepareGraphQLRequestConfigs.ts
> +      if (variables.checkMode === 'exists' || variables.checkMode === 'notExists') {
Тут аналогично body в rest

2024-03-17 16:42 UTC, debabin commented on src/utils/types/entities.ts
> +type PropertyLevelPlainEntityDescriptor<Check extends CheckMode = CheckMode> =
Мне кажется данный тип должен совпадать с MappedEntityDescriptor, ведь если человек описывает внутри все тело, то это уже схоже с headers например, сейчас человек не может написать например regexp для филда в боди

![image](https://github.com/siberiacancode/mock-config-server/assets/45297354/f0001f0e-42cf-4763-9565-c670f61d9e26)

2024-03-17 16:42 UTC, debabin commented on src/utils/types/entities.ts
> +type PropertyLevelPlainEntityDescriptor<Check extends CheckMode = CheckMode> =
если человек делает regexp на объект, это он сам дурак

2024-03-17 16:42 UTC, debabin commented on bin/newValidateMockServerConfig/validateMockServerConfig.ts
> +      `Validation Error: configuration${validationMessage} does not match the API schema. Click here to see correct type: https://github.com/siberiacancode/mock-config-server`
в cli своем уже поправил

2024-03-17 16:42 UTC, debabin commented on bin/newValidateMockServerConfig/utils/nonRegExpSchema/nonRegExpSchema.ts
> +  z.custom((value) => !(value instanceof RegExp)).pipe(schema);
Добавь импортант, но суть я понял, по факту человек может написать вот так request: /a/g и zod это нормально схавает, забавно

2024-03-17 16:56 UTC, debabin requested changes

2024-03-17 16:56 UTC, debabin commented on bin/helpers/getMostSpecificPathFromError.ts
> +      // eslint-disable-next-line no-continue
включить просто warn в конфиг eslint

2024-03-17 16:56 UTC, debabin commented on bin/helpers/isOnlyRequestedDataResolvingPropertyExists.ts
> +export const isOnlyRequestedDataResolvingPropertyExists = (
она проверяет, что существует только 'data', 'file', 'queue' что-то одно из этого

2024-03-17 16:56 UTC, debabin commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +      settingsSchema.extend({ polling: z.literal(false).optional() })
респект

2024-03-17 16:56 UTC, debabin commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +  interceptors: nonRegExpSchema(interceptorsSchema.pick({ response: true })).optional()
nonRegExpSchema каждый раз писать для optional object супер не хочется, может мы наоборот создадим функцию optionalObject ? и там скроем явную проверку на object ? А то мне кажется очень много вопросов будет задавать такая проверка

2024-03-17 16:56 UTC, debabin commented on bin/newValidateMockServerConfig/restConfigSchema/restConfigSchema.ts
> +    interceptors: nonRegExpSchema(interceptorsSchema).optional()
optionalObject(interceptorsSchema) и вот так будет супер секс вроде бы

2024-03-17 16:56 UTC, debabin commented on bin/newValidateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +const fileRouteConfigSchema = (method: RestMethod) =>
а у нас же не умеет в polling files, как смотришь на такую фичу ?

2024-03-18 16:15 UTC, debabin requested changes

2024-03-18 16:15 UTC, debabin commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
> +      entities: null,
А есть ли смысл в этом тесте ? я чот но не совсем понял

2024-03-18 16:15 UTC, debabin commented on bin/newValidateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
> +  test('Should return correct error path on handle object with more than one data resolving properties', () => {
Этот тест понимаю, он нужен на нашу логику, но чот не могу понять зачем нижний мб чего не понял, также первый тест я как понял, когда ничего нет. Разве это тоже наша логика, а не зода уже ? Мы тип склеили схему ну и все

2024-03-18 16:15 UTC, debabin commented on bin/newValidateMockServerConfig/utils/entitiesSchema/entitiesSchema.test.ts
> +    expect(propertyLevelParseResult.success).toBe(false);
А мы не хотим все checkMode тип через for ?

2024-03-18 16:15 UTC, debabin commented on bin/newValidateMockServerConfig/utils/entitiesSchema/entitiesSchema.test.ts
> +      checkMode: 'some random string'
А опять же это не ответственность зода ? Мы опять склеили все и дальше он сам ? или нет ?

2024-03-23 12:31 UTC, MiaInturi commented on src/utils/constants/checkModes.ts
> +] as const satisfies readonly CompareWithDescriptorValueCheckMode[];
нет, satisfies работает только в месте своего вызова. Он никак не влияет на тип переменной при дальнейшем использовании. Таким образом `as const` сужает тип, а satisfies проверяет, что переменная соответствует нужному нам типу

2024-03-23 12:35 UTC, MiaInturi commented on bin/helpers/isOnlyRequestedDataResolvingPropertyExists.ts
> +export const isOnlyRequestedDataResolvingPropertyExists = (
Да, именно это и проверяет. Мне тоже не очень нравятся такие длинные названия функций, мб есть предложения получше?

2024-03-23 13:16 UTC, MiaInturi commented on bin/newValidateMockServerConfig/utils/jsonSchema/jsonSchema.ts
> +    z.record(jsonSchema).and(z.custom((value) => isPlainObject(value)))
Я вспомнил для чего это - убрать не получится, но я добавил important

2024-03-23 13:19 UTC, MiaInturi commented on bin/run.ts
> +  { baseUrl, port, staticPath }: MockServerConfigArgv
Потому что в соответствии с этим комментом https://github.com/siberiacancode/mock-config-server/pull/144#discussion_r1501827995 у нас в agrv будут `_`, `$0`, а еще `watch` и `config`. zod начнет ругаться на них

2024-03-23 13:22 UTC, MiaInturi commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
> +      if (body.checkMode === 'exists' || body.checkMode === 'notExists') {
![image](https://github.com/siberiacancode/mock-config-server/assets/39031929/3734ce2a-d7cd-4b69-a085-c5c156217d74)
Из-за того, что checkMode вложен в body, то typescript не может с помощью конструкции `if { return ... }` сузить тип body.checkMode

2024-03-23 13:22 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/helpers/prepareGraphQLRequestConfigs/prepareGraphQLRequestConfigs.ts
> +      if (variables.checkMode === 'exists' || variables.checkMode === 'notExists') {
Ответил здесь https://github.com/siberiacancode/mock-config-server/pull/144#discussion_r1536632775

2024-03-23 13:33 UTC, MiaInturi commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
> +      entities: null,
Я тоже не понял зачем тест - удалю. Возможно, я писал эти тесты до того, как упросил zod-схемы, т.к. раньше кастомных проверок было больше.

2024-03-23 13:35 UTC, MiaInturi commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
> +      entities: null,
А, я понял для чего этот тест. По сути я его не правильно написал. Он проверяет, что все нет ошибок, если используется только одно из property - data или queue. Вообще это все в 1 тест можно объединить - типо проверка, что правильно работает кастомная логика, которая пропускает только 1 property (data, queue или file в случае с rest)

2024-03-23 13:35 UTC, MiaInturi commented on bin/newValidateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.test.ts
> +  test('Should return correct error path on handle object with more than one data resolving properties', () => {
Ответил выше

2024-03-23 13:51 UTC, MiaInturi commented on bin/newValidateMockServerConfig/utils/entitiesSchema/entitiesSchema.test.ts
> +    expect(propertyLevelParseResult.success).toBe(false);
Не, тут проверяются не checkMode-ы, а именно сообщения об ошибке. Короче, zod имеет довольно неочевидное поведение, покажу на примере этого кода
```typescript
export const plainEntitySchema = z.union([
  topLevelPlainEntityDescriptorSchema,
  topLevelRecordSchema,
  topLevelArraySchema
]);
```
Тут по сути схема, которая состоит из 3 других схем. И порядок этих схем внутри z.union имеет значение, т.к. если каждая из схем выдаст ошибку, то zod отдаст нам 1-ую из них. И получается, что сейчас, когда `topLevelPlainEntityDescriptorSchema` на первом месте, то в первую очередь отдается ошибка оттуда, а если бы, например, первым стояла `topLevelRecordSchema`, то отдавалась бы ошибка оттуда.

Что я имею в виду: сейчас если в текущую схему скинуть объект
```typescript
{
  checkMode: 'equals'
}
```
то ошибка пожалуется на то, что нет value (как в тестах и проверяется), а вот если схема будет такая
```typescript
const topLevelRecordSchema = nonCheckModeRecordSchema(
  z.record(z.union([propertyLevelPlainEntityDescriptorSchema, topLevelRecordValueSchema]))
);

// topLevelRecordSchema ПЕРЕД topLevelPlainEntityDescriptorSchema
export const plainEntitySchema = z.union([
  topLevelRecordSchema,
  topLevelPlainEntityDescriptorSchema,
  topLevelArraySchema
]);
```
то на тот же самый скинутый объект ошибка уже пожалуется на checkMode (т.к. схема topLevelRecordSchema обернута в nonCheckModeRecordSchema).

2024-03-23 13:51 UTC, MiaInturi commented on bin/newValidateMockServerConfig/utils/entitiesSchema/entitiesSchema.test.ts
> +      checkMode: 'some random string'
Ответил тут https://github.com/siberiacancode/mock-config-server/pull/144#discussion_r1536636834

2024-03-23 13:53 UTC, MiaInturi commented on bin/newValidateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +const fileRouteConfigSchema = (method: RestMethod) =>
чтобы внутри объектов в queue можно было писать не только data, но и file? Да норм в целом

2024-03-23 13:58 UTC, MiaInturi commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +  interceptors: nonRegExpSchema(interceptorsSchema.pick({ response: true })).optional()
Сперва я так и сделал, но прикол в том, что возвращаемый тип функции `z.object()` ZodObject имеет много полезных методов, типо merge, pick, omit и тд. В общем всякие методы, которые уникальны именно для объектов. Если же сделать что-то типа 
```typescript
const plainObjectSchema = (shape: PlainObject) =>
  z.custom((value) => !(value instanceof RegExp)).pipe(z.object(shape));
```
то возвращаемый тип будет ZodPipeline который не имеет уникальные для объекта методы. И получается мы не сможем использовать эти методы

2024-03-23 14:10 UTC, MiaInturi commented on src/utils/types/entities.ts
> +type PropertyLevelPlainEntityDescriptor<Check extends CheckMode = CheckMode> =
1. Я не вижу ничего плохо огранить возможность писать RegExp, нежели юзер напишет и потом будет думать, а почему не работает
2. Основная причина раздельного существования PropertyLevelPlainEntityDescriptor и MappedEntityDescriptor - это поддержка вложенных сущностей. Для PropertyLevelPlainEntityDescriptor checkMode function и CompareWithDescriptorAnyValueCheckMode поддерживают бесконечно вложенные сущности. Ведь может быть такой вариант:
```typescript
 routes: [
          {
            entities: {
              body: {
                property: {
                  checkMode: 'equals',
                  value: {
                    nested1: {
                      nested2: {
                        nested3: 'value'
                      }
                    }
                  }
                }
              }
            },
            data: 'hello world'
          }
        ]
```
Подобная вложенность невозможна для MappedEntityDescriptor

2024-03-23 15:21 UTC, MiaInturi commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +  interceptors: nonRegExpSchema(interceptorsSchema.pick({ response: true })).optional()
Единственное что, мы можем просто забить и позволить писать regexp там, где можно писать объекты

2024-03-23 15:22 UTC, MiaInturi commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +  interceptors: nonRegExpSchema(interceptorsSchema.pick({ response: true })).optional()
Но хз, мне не очень такое нравится, т.к. поведение типизации и поведение валидации будут разными (типизация не пропустит regexp, а валидация пропустит)

2024-03-24 06:18 UTC, debabin commented on bin/helpers/isOnlyRequestedDataResolvingPropertyExists.ts
> +export const isOnlyRequestedDataResolvingPropertyExists = (
Я думал, но ничего не придумал

2024-03-24 06:19 UTC, debabin commented on src/utils/types/entities.ts
> +type PropertyLevelPlainEntityDescriptor<Check extends CheckMode = CheckMode> =
Не просто, а что если юзер хочет regexp, ну например там есть 

```ts
body: {
 name: {
  checkMode: regexp
...   
}
}
```

2024-03-24 06:23 UTC, debabin commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +  interceptors: nonRegExpSchema(interceptorsSchema.pick({ response: true })).optional()
> Сперва я так и сделал, но прикол в том, что возвращаемый тип функции `z.object()` ZodObject имеет много полезных методов, типо merge, pick, omit и тд. В общем всякие методы, которые уникальны именно для объектов. Если же сделать что-то типа
> 
> ```ts
> const plainObjectSchema = (shape: PlainObject) =>
>   z.custom((value) => !(value instanceof RegExp)).pipe(z.object(shape));
> ```
> 
> то возвращаемый тип будет ZodPipeline который не имеет уникальные для объекта методы. И получается мы не сможем использовать эти методы


Так вот этот вариант с кодом довольно не плох, просто я хотел бы поменять нейминг и все, чтобы не было вопросов про regexp и уже внутри plainObjectSchema написать important

2024-03-24 06:23 UTC, debabin commented on bin/newValidateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +const fileRouteConfigSchema = (method: RestMethod) =>
Надо issue сделать на доработку

2024-03-24 07:36 UTC, MiaInturi commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +  interceptors: nonRegExpSchema(interceptorsSchema.pick({ response: true })).optional()
Но этот вариант накладывает ограничения: `возвращаемый тип будет ZodPipeline который не имеет уникальные для объекта методы. И получается мы не сможем использовать эти методы`. А эти методы нам нужны в дальнейшем

2024-03-24 07:47 UTC, MiaInturi commented on src/utils/types/entities.ts
> +type PropertyLevelPlainEntityDescriptor<Check extends CheckMode = CheckMode> =
А, то есть ты хочешь добавить regexp checkMode для property body. Да, добавлю - его добавление выглядит логично

2024-03-24 08:05 UTC, MiaInturi commented on bin/newValidateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +const fileRouteConfigSchema = (method: RestMethod) =>
[Сделал](https://github.com/siberiacancode/mock-config-server/issues/158)

2024-03-24 09:03 UTC, RiceWithMeat commented on bin/newValidateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +    .strictObject({
форматер поехал мне кажется

2024-03-24 09:28 UTC, MiaInturi commented on bin/newValidateMockServerConfig/graphqlConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +  interceptors: nonRegExpSchema(interceptorsSchema.pick({ response: true })).optional()
Переименовал с nonRegExpSchema на plainObjectSchema

2024-03-24 09:29 UTC, MiaInturi commented on bin/newValidateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +    .strictObject({
А prettier ошибку подсвечивал. Я сравнил main и release@3.4.0 и там обновили версию prettier. Мб поэтому так

2024-03-24 09:29 UTC, MiaInturi commented on bin/run.ts
> +import { validateMockServerConfig } from './newValidateMockServerConfig/validateMockServerConfig';
Да, я это сделаю, когда аппрувы будут, так как иначе там git diff поедет жоско и вам будет неудобно смотреть изменения

2024-03-24 09:33 UTC, MiaInturi commented on bin/newValidateMockServerConfig/validateApiMockServerConfig.ts
> +export const validateApiMockServerConfig = (
Этот файл по сути аналог этого файла https://github.com/siberiacancode/mock-config-server/blob/release%403.4.0/bin/validateMockServerConfig/validateApiMockServerConfig.ts. Он был создан в рамках https://github.com/siberiacancode/mock-config-server/pull/143

2024-03-24 09:58 UTC, RiceWithMeat commented on bin/newValidateMockServerConfig/restConfigSchema/routeConfigSchema/routeConfigSchema.ts
> +    .strictObject({
надо будет посмотреть потом

2024-03-24 09:59 UTC, RiceWithMeat approved these changes

2024-03-25 14:12 UTC, merged