#145 into release@4.0.0 ☄ filter operators for database
siberiacancode/mock-config-server pull request #146
Opened 2024-01-28 09:30 UTC by debabin

2024-02-27 18:19 UTC, bobul approved these changes

2024-03-02 06:51 UTC, MiaInturi requested changes

2024-03-02 06:51 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +  const [element, operator] = key.split('_');
Конструкция вида 
```typescript
key.split('_')
```
подвержена большому кол-ву багов, ведь пользователь может делать поиск по ключам с нижним подчеркиванием (например, ключ `_index`). Мне кажется тут больше подойдет регулярка вида 
```typescript
new RegExp(`^(.+)_(${Object.keys(OPERATORS).join('|')})$`)
```

2024-03-02 06:51 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.test.ts
> +    });
Пропустил тесты для `neq` оператора

2024-03-02 06:51 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.test.ts
> +      const response = await request(server).get('/users?name_new=a=J');
Тут так и должно быть `a=J`?

2024-03-02 16:25 UTC, MiaInturi requested changes

2024-03-02 16:25 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +  const parts = key.match(new RegExp(`^(.+)_(${Object.keys(OPERATORS).join('|')})?$`));
Тут можно использовать `OPERATORS_KEYS`

2024-03-02 16:25 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +  const parts = key.match(new RegExp(`^(.+)_(${Object.keys(OPERATORS).join('|')})?$`));
А почему вторая группа является опциональной? Ведь это блокирует возможность использования пользователем ключей с нижним подчеркиванием в конце. Мы же через RegExp должны искать идеальное совпадение с форматом `${element}_${operator}`.

2024-03-02 16:25 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +  if (!operator || !OPERATORS_KEYS.includes(operator)) return `${element}` === value;
на текущий момент второе условие невозможно, т.к. проверку на себя берет регулярное выражение по сути

2024-03-02 16:25 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +const filtered = (element: any, value: any, operator?: string) => {
Если вторая группа регулярки будет неопциональной, то на строке 27 operator уже будет иметь тип `keyof typeof OPERATORS`, и получается в функции `filtered` второй аргумент будет типа `keyof typeof OPERATORS`, что убирает необходимость приведения строки к нужному типу на 38 строчке

2024-03-02 16:25 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
>      });
Ну тут отключение правила `no-shadow` прям жоско ломает читаемость. У нас есть два element и два value по сути. Мб как-то переименовать хотя бы по одному экземпляру каждого из них?

2024-03-03 04:46 UTC, MiaInturi requested changes

2024-03-03 04:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +  const parts = key.match(new RegExp(`^(.+)_(${OPERATORS_KEYS.join('|')})$`));
regexp можно вынести за пределы функции

2024-03-03 04:46 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
>    });
Мб тогда element на строчке 42 переименуем в arrayElement, а flattenedElement в flattenedArrayElement? А то 3 разных element для такой маленькой функции многовато

2024-03-03 06:25 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +  const parts = key.match(new RegExp(`^(.+)_(${OPERATORS_KEYS.join('|')})$`));
Не вижу в этом смысла

2024-03-03 06:34 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/filter/filter.ts
> +  const parts = key.match(new RegExp(`^(.+)_(${OPERATORS_KEYS.join('|')})$`));
Вижу сделал

2024-03-03 06:57 UTC, MiaInturi approved these changes

2024-03-03 07:24 UTC, RiceWithMeat approved these changes

2024-03-03 07:41 UTC, merged