#67 into release@4.0.0 👹 rest routes support file paths
siberiacancode/mock-config-server pull request #155
Opened 2024-02-14 16:26 UTC by MiaInturi

2024-02-15 17:32 UTC, debabin requested changes

2024-02-15 17:32 UTC, debabin commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.test.ts
> +      tmpDirPath = fs.mkdtempSync(`${os.tmpdir()}${path.sep}`);
если это нужный код мб функцию вынесем ?

2024-02-15 17:32 UTC, debabin commented on examples/files/relative-path.ts
> +            // Will looking for file by (process.cwd() + "/relative/path/to/file") path
думаю людям нужен этот коммент ? просто это такое прям, внутрянка

2024-02-15 17:32 UTC, debabin commented on README.md
> +              }
а мы в итоге запрещаем data менять для файла ?

2024-02-15 17:32 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +  test.each(operationTypesWithoutCacheControlHeader)(
мы не используем test.each, а юзаем forEach

2024-02-15 17:32 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +  test.each(methodsWithoutCacheControlHeader)(
test.each -> forEach

2024-02-15 17:35 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +  test.each(operationTypesWithoutCacheControlHeader)(
forEach очень неудобен, когда тест падает. test.each в этом плане гораздо лучше, т.к. создан под такие кейсы. Так еще и запускать async ф-ии в forEach неудобно. Это надо делать map + Promise.all

2024-02-15 18:05 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +  test.each(operationTypesWithoutCacheControlHeader)(
Если мы говорим про test each, то его апи какашка, плюс ты описываешь проблему, когда в test внутри делаешь forEach, если сделать forEach -> test то все ок, он создает n тестов и есть все логи по ним же. По крайне мере мы точно об этом говорили. Не понял про async (я знаю про работу async и forEach я не совсем понял в чем у нас проблема)

2024-02-16 15:51 UTC, MiaInturi commented on examples/files/relative-path.ts
> +            // Will looking for file by (process.cwd() + "/relative/path/to/file") path
Этот коммент нужен для того, чтобы пользователи понимали, относительно чего строится относительный путь (найс тавтология)

2024-02-16 15:52 UTC, MiaInturi commented on README.md
> +              }
ну по сути никто не запрещает менять data и она даже в последующие middleware будет передаваться измененной, но на сам итоговый ответ это влияния иметь не будет

2024-02-16 16:14 UTC, MiaInturi commented on src/utils/helpers/files/isFilePathValid/isFilePathValid.test.ts
> +    expect(isFilePathValid(notExistedFilePath)).toBe(false);
Тут проверка, что вернет false для несуществующего ФАЙЛА, а ниже проверка, что вернет false для НЕ ФАЙЛОВ

2024-02-16 16:14 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.test.ts
> +      tmpDirPath = fs.mkdtempSync(`${os.tmpdir()}${path.sep}`);
Думаю можно вынести в какую-нибудь utils функцию

2024-02-19 15:41 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +        response.status(response.statusCode);
А в чем смысл этого кода вообще? Он же по сути бессмысленен

2024-02-19 15:43 UTC, MiaInturi commented on tsconfig.dev.json
> +      "@/utils/helpers/tests": ["./src/utils/helpers/tests"],
Вынес для этого отдельный alias, т.к. хотел, чтобы хэлперы тестов явно выделялись в коде

2024-02-19 17:09 UTC, debabin requested changes

2024-02-19 17:09 UTC, debabin commented on src/utils/helpers/tests/createTmpDir.ts
> +};
export const createTmpDir = () => fs.mkdtempSync(`${os.tmpdir()}${path.sep}`)

2024-02-19 17:09 UTC, debabin commented on src/utils/helpers/tests/createTmpDir.ts
> +export const createTmpDir = () => {
мне казалось, что я видел не только это в тестах или мне показалось, сейчас не смог найти

2024-02-23 15:56 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +        if (!((isRouteHasFileProperty !== isRouteHasDataProperty) !== isRouteHasQueueProperty)) {
можно объединить эту и все проверки выше в `if ((isRouteHasFileProperty + isRouteHasDataProperty + isRouteHasQueueProperty) !== 1) `

2024-02-23 15:56 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.test.ts
> +import { createTmpDir } from '@/utils/helpers/tests';
temp. Пусть и тоже сокращение, но кажется более общепринятым чем tmp

2024-02-23 18:11 UTC, MiaInturi commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +        if (!((isRouteHasFileProperty !== isRouteHasDataProperty) !== isRouteHasQueueProperty)) {
Харош

2024-02-23 18:14 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.test.ts
> +import { createTmpDir } from '@/utils/helpers/tests';
Название выбирал исходя из того, что в этой функции вызывается функция `os.tmpdir`

2024-02-24 07:18 UTC, debabin approved these changes

2024-02-24 07:31 UTC, RiceWithMeat approved these changes

2024-02-25 10:52 UTC, merged