#167 into release@3.6.0 🐘 call server response interceptors for database requests, add detabase api interceptors, add baseUrl field for database
siberiacancode/mock-config-server pull request #170
Opened 2024-05-20 20:06 UTC by RiceWithMeat

2024-06-01 08:27 UTC, MiaInturi requested changes

2024-06-01 08:27 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.test.ts
> +  test('Should call response interceptors in order: api -> server', async () => {
1. Я думаю можно в рамках этого же PR исправить: тесты на interceptors для `createRestRoutes` и `createGraphqQLRoutes` не содержат проверку на вызов api response interceptor в цепочке interceptor-ов. Надо бы добавить
2. Я бы текущие тесты перенес в `createShallowDatabase.test.ts` и `createNestedDatabase.test.ts` по след. причинам:
  2.1 текущий тест проверяет по сути только shallow interceptors, т.к. запрос на /users не делается
  2.2 проверяется только get method

2024-06-01 08:27 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
>      });
А почему для post не добавили response interceptor? Ресурс же возвращается по сути. Если пользователи не захотят interceptor ля POST, то смогут отфильтровать через 
```typescript
if (req.method !== 'POST') {
...
}
```

2024-06-01 08:27 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +    );
А вот тут для post как раз сделано

2024-06-01 08:29 UTC, MiaInturi commented
И еще вопрос на обсудить - не хотим ли мы route request interceptor добавить? Потому что сейчас нет interceptor-а именно для запросов, которые совпали полностью по роутам

2024-06-02 16:28 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.test.ts
> +  test('Should call response interceptors in order: api -> server', async () => {
По 1 пункту сделал тут: https://github.com/siberiacancode/mock-config-server/pull/177

2024-06-10 17:04 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
>      });
пропустил прост. поправил

2024-06-10 17:04 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +    );
пропустил прост. поправил

2024-06-10 17:06 UTC, RiceWithMeat commented on src/server/createMockServer/createMockServer.ts
> +    server.use(databaseBaseUrl, routerWithDatabaseRoutes);
поправил

2024-12-09 04:12 UTC, debabin approved these changes

2024-12-24 17:07 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +          data: {},
думаю null более правильно будет передавать, т.к. мы буквально в ответе не отправляем ничего

2024-12-24 17:07 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
> +    );
Мне кажется на __routes и __db не нужно навешивать interceptor - это метаинформация о базе данных, а не ответы самой бд и эта инфа всегда должна отражать реальную картину

2024-12-29 08:38 UTC, debabin commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
> +    );
соглы тут

2024-12-29 08:42 UTC, debabin commented on src/server/createRestMockServer/createRestMockServer.ts
> +    });
вообще дыа, как будто забыли везде добавить его

2025-01-06 12:47 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.test.ts
> +  test('Should call response interceptors in order: api -> server', async () => {
поправил по второму

2025-01-06 16:13 UTC, debabin approved these changes

2025-01-07 09:29 UTC, closed without merging