#106 into release@4.0.0 🌵 add dropdown feature, add system option in scheme switcher, change header items, change scheme colors, fix hover styles
siberiacancode/mock-config-server pull request #182
Opened 2024-06-30 17:27 UTC by kvelian

Темная тема:
![image](https://github.com/siberiacancode/mock-config-server/assets/81089091/caf4501f-8f1f-43e1-aea8-ce791ce56a75)

Светлая тема:
![image](https://github.com/siberiacancode/mock-config-server/assets/81089091/458cbdae-55a1-4c81-b52d-0f3f7299e67e)

2024-06-30 18:55 UTC, RiceWithMeat commented on src/static/views/features/dropdown/index.js
> +  });
хендлер тоже можно вынести в константу по аналогии с onClickOutsideListener

2024-06-30 18:55 UTC, RiceWithMeat commented on src/static/views/features/scheme/index.js
> +  } else mediaDark.removeEventListener('change', () => setScheme('system'));
в dropdown/index.js есть скобки у else для одной строки, а тут нет

2024-06-30 18:55 UTC, RiceWithMeat commented on src/static/views/assets/styles/global.css
> +}
что vl означает?

2024-06-30 18:55 UTC, RiceWithMeat commented on src/static/views/components/header/index.ejs
> +            </svg>
свгшки не сжаты

2024-06-30 18:55 UTC, RiceWithMeat commented on src/static/views/components/header/index.js
> +  }
arrow declaration и forEach/for of не поддерживаются я так понимаю?

2024-07-01 06:36 UTC, kvelian commented on src/static/views/assets/styles/global.css
> +}
как тэг hr - горизонтальная линия, vl - вертикальная

2024-07-07 07:57 UTC, MiaInturi requested changes
Еще предлагаю задуматься над использованием JS модулей, т.к. сейчас весь js как бы в одном пространстве имен. Хотя браузеры давно поддерживают модули

2024-07-07 07:57 UTC, MiaInturi commented on src/static/views/features/scheme/index.js
> +  const scheme = getSavedScheme() ?? 'system';
Можно функцию вместо `getSavedScheme` сделать функцию `getCurrentScheme` и уже в ней будет логика `?? 'system'` - чтобы определение схемы было полностью в одном месте

2024-07-07 07:57 UTC, MiaInturi commented on src/static/views/features/scheme/index.js
> +    mediaDark.addEventListener('change', () => setScheme('system'));
сейчас listener вызовет снова setScheme, который снова поставит новый listener. И новые listener-ы будут добавляться каждый раз, когда системная тема меняется

2024-07-07 08:28 UTC, MiaInturi commented on src/static/views/features/scheme/index.js
>    darkStyles.media = darkMedia;
Еще мне не очень нравится текущая реализация смены темы через изменения media (как минимум потому что это триггерит загрузку файлов каждый раз при смене темы). Я считаю, что проще обойтись одним css-файлом
![image](https://github.com/siberiacancode/mock-config-server/assets/39031929/1ad07c33-f729-4e0d-82d8-3954b2b0d856)

И при смене темы просто добавлять/удалять класс dark_theme. Ну или по умолчанию сделать темным, а добавлять/удалять light_theme - тут уже без разницы. И тогда весь css будет в одном месте и не будут делаться лишние запросы.

2024-08-04 15:06 UTC, debabin commented on src/static/views/components/header/index.js
> +  }
можно сделать

2024-08-09 14:13 UTC, kvelian commented on src/static/views/features/dropdown/index.js
> +  const dropwdownTrigger = document.getElementById(`${dropdownId}_trigger`);
даже буквально с наводкой ещё тупила и не могла её разглядеть 🤦‍♂️

2024-08-09 14:30 UTC, kvelian commented on src/static/views/features/dropdown/index.css
> +}
решила оставить отдельно стоящий acitve класс везде, такой вариант больше нравится
На счет БЭМ есть смысл, но думаю лучше в отдельной ветке это делать уже

2024-08-09 15:59 UTC, kvelian commented on src/static/views/components/header/index.js
> +  }
огнище, спасибо 🔥

2024-12-03 10:54 UTC, closed without merging