#185 into release@4.0.0 🧊 add new eslint
siberiacancode/mock-config-server pull request #186
Opened 2024-10-18 09:41 UTC by debabin

2024-11-10 10:20 UTC, RiceWithMeat commented on .husky/commit-msg
>      branch=$(git symbolic-ref --short HEAD)
в husky.sh написано первую строку тоже надо удалить. или она нужна для другой логики в файлах?

2024-11-10 10:20 UTC, RiceWithMeat commented on package.json
> +  ],
graphQL и database мб ещё добавим? основные фичи

2024-11-10 12:06 UTC, debabin commented on .husky/commit-msg
>      branch=$(git symbolic-ref --short HEAD)
не понял

2024-11-10 13:19 UTC, MiaInturi requested changes

2024-11-10 13:19 UTC, MiaInturi commented on eslint.config.mjs
> +  }
мб сделаем у этих конфигов префикс `mock-config-server`? Чтобы было понятно, что это правила чисто для этого проекта, а не часть @siberiacancode/eslint, где есть конфиги с префиксом `siberiacancode`?

2024-11-10 13:19 UTC, MiaInturi commented on eslint.config.mjs
> +      'ts/consistent-type-imports': 'off'
А почему вырубили правило? Оно же по сути отвечает за то, чтобы import type норм выглядели

2024-11-10 13:19 UTC, MiaInturi commented on tsconfig.production.json
> -  "include": ["bin", "src", "./index.ts"],
А declaration.d.ts же не нужен по сути. Да он и не будет загружен пользователем, т.к. в поле types в package.json прописан только index.d.ts

2024-11-10 13:19 UTC, MiaInturi commented on bin/bin.ts
> +import packageJson from '../../package.json' assert { type: 'json' };
import packageJson from '../package.json'; 

там путь неправильный был и не нужно тогда делать declaration.d.ts, ведь в tsconfig стоит опция resolveJsonModule

2024-11-16 14:50 UTC, debabin commented on eslint.config.mjs
кстати я совсем забыл про template для flat нужно будет добавить

2024-11-16 14:53 UTC, debabin commented on .husky/_/husky.sh
этот файл автогеном добавляет хаски

2024-11-16 14:55 UTC, debabin commented on eslint.config.mjs
> +      'ts/consistent-type-imports': 'off'
я пробовал решить тему с pacakge json, удалил правило

2024-11-16 14:56 UTC, debabin commented on package.json
> +    "graphql": "^16.9.0",
Я поставил сразу 14, что думаешь ?

2024-11-16 15:15 UTC, MiaInturi commented on package.json
> +    "node": ">=12.22.0"
Тут недостаточно поставить только младшую версию, а надо именно 1 в 1 взять `^12.22.0 || ^14.16.0 || ^16.0.0 || >=17.0.0`
т.к. версия 14.1.0 подходит под условие `"node": ">=12.22.0", но не подходит под условие  `^12.22.0 || ^14.16.0 || ^16.0.0 || >=17.0.0`

2024-11-16 16:59 UTC, MiaInturi approved these changes

2024-12-03 06:21 UTC, debabin commented on bin/bin.ts
> +const packageJson = require('../package.json');
тут был верной json

2025-01-11 12:14 UTC, closed without merging

2025-01-11 12:14 UTC, debabin commented
The pull request was closed due to a large number of issues, and new eslint was added manually in the release.