#192 into #187 🧊 add validate to create functions
siberiacancode/mock-config-server pull request #193
Opened 2024-11-21 17:50 UTC by debabin

2024-11-22 14:35 UTC, MiaInturi requested changes

2024-11-22 14:35 UTC, MiaInturi commented on tsconfig.dev.json
> +      "@/utils/validate": ["./src/utils/validate"]
Надо новый алиас еще в .swcrc файл добавить

2024-11-23 11:48 UTC, debabin commented on src/server/createMockServer/createMockServer.ts
они не используются, но торчат в Index.ts из библы, удалим в 5.0.0, когда оставим только flat

2024-11-23 11:49 UTC, debabin commented on tsconfig.dev.json
> +      "@/utils/validate": ["./src/utils/validate"]
файл не запушился, сделаем

2024-11-25 13:05 UTC, MiaInturi requested changes

2024-11-25 13:31 UTC, MiaInturi approved these changes

2024-11-25 13:34 UTC, RiceWithMeat commented on src/utils/validate/index.ts
> +export * from './validateMockServerConfig';
можно оставить только validate функции, утилсы и схемы валидаторов нигде кроме этих функций не нужны

2024-11-25 13:38 UTC, debabin commented on src/utils/validate/index.ts
> +export * from './validateMockServerConfig';
вот я тоже так думал, а они используются в bin, поэтому решил у все возврщать из модуля

2024-11-25 13:39 UTC, debabin commented on src/server/startFlatMockServer/startFlatMockServer.ts
>    });
тут как раз специально так сделали, чтобы сначала был вызов createFlatMockServer, в котором валидация, да это не явно, но правильно с точки зрения где должна быть валидация

2024-11-25 13:41 UTC, RiceWithMeat commented on src/utils/validate/index.ts
> +export * from './validateMockServerConfig';
рэально, тогда ок

2024-11-25 13:42 UTC, RiceWithMeat approved these changes

2025-01-10 15:32 UTC, merged