#158 into release@4.0.0 🐘 add file polling support
siberiacancode/mock-config-server pull request #201
Opened 2024-12-27 12:53 UTC by RiceWithMeat

2024-12-29 08:37 UTC, debabin commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
> +  const sortedByPathRequestConfigs = requestConfigs.sort(
это ты сразу решил сделать, мы же не фиксили это баг или как ? я чот забыл про это вообще, хотя я точно помню мы с Нусултаном подобную штуку обсуждали

2024-12-29 08:37 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            if (!isFilePathValid(queueItem.file)) return next();
а вот такое не должно проверять на уровне zod схем ?

2024-12-29 08:37 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
>            if (!isFilePathValid(matchedRouteConfig.file)) return next();
аналогичный вопрос

2024-12-29 14:51 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            if (!isFilePathValid(queueItem.file)) return next();
проверять валиден ли путь до файла точно не ответственность зода. Он должен только проверить, что путь - это строка. А искать файл надо на каждый запрос. Плюсы у такого подхода:
1. У пользователя есть возможность работать с файлами пока запущен мок сервер. Никто не запрещает пользователю юзать fs и создать например файл, который потом вернётся другим запросом. (например так можно замокать генерацию pdf-доков чтобы другой запрос уже его возвращал)
2. логика "верни 404 если файла нет" теряет смысл, ведь сервер просто не запустится если файла нет

Имхо сейчас всё выглядит правильно и логично в плане файлов

2024-12-29 14:51 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
>            if (!isFilePathValid(matchedRouteConfig.file)) return next();
выше ответил

2024-12-29 14:58 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
> +  const sortedByPathRequestConfigs = requestConfigs.sort(
я этот файл не трогал. гитхаб баганул и показывает лишние коммиты, хотя моя ветка от main, а в 4.0.0 я подлил main

2024-12-29 14:59 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
> +  const sortedByPathRequestConfigs = requestConfigs.sort(
я пробовал локально смержить этот мр, меняются только файлы из моего коммитах

2024-12-31 08:02 UTC, debabin approved these changes

2024-12-31 13:06 UTC, MiaInturi requested changes

2024-12-31 13:06 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +        }
Тогда в response interceptors будет отправляться не null, а имя файла - т.е. это условие по сути не нужно

2024-12-31 13:06 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +        }
вычисление `resolvedData` можно поставить прям перед вызовом response interceptors

2024-12-31 13:12 UTC, MiaInturi commented on README.md
> +`queue` is an array containing `data` and `file` that should be returned in order.
`data` or `file` - or вместо and?

2024-12-31 13:12 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +        }
А, это было сделано намеренно, понял

2024-12-31 13:41 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          }
соглы

2024-12-31 13:44 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +        }
а мы не хотим в response кидать сам файл ?

2024-12-31 13:49 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +        }
можно прочитать файл и кинуть его как Blob. Но тогда возникает вопрос с отправкой - можно оставить как есть res.sendFile - но по сути тогда файл читается два раза. Вариант номер 2 - это уже прочитанный блоб отправлять, но тогда надо правильно поставить хэдеры типо Content-Type, Content-Disposition и т.д., что за нас делал раньше res.sendFile

2025-01-01 05:26 UTC, debabin approved these changes

2025-01-03 18:03 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            !data.file
мб вынесем это в константу выше все таки и даже на куски попилим ?

2025-01-03 18:03 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    const pathToUser2 = path.join(tmpDirPath, './user2.json');
сделай пж не user1  и user2, а тип first-user second-user

2025-01-03 19:34 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            !data.file
сделал хелпер

2025-01-05 15:18 UTC, MiaInturi requested changes

2025-01-05 15:18 UTC, MiaInturi commented on src/utils/helpers/files/isFileDescriptorValid/isFileDescriptorValid.ts
> +  Buffer.isBuffer(value.file);
Я думаю эту функцию можно переделать вот так
```typescript
return z.object({
  path: z.string().refine(isFilePathValid),
  file: z.instanceof(Buffer),
}).strict().safeParse().success; // хз надо ли strict или нет
```

и тогда можно как с обычной валидацией просто не делать тесты, т.к. по сути все за нас делает zod. Ну и как по мне когда так написано, то видишь сразу структуру ожидаемого объекта (ключи/значения), что клево

2025-01-05 15:18 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          response.set('Content-Disposition', `filename=${fileName}`);
Есть метод res.attachment который все это может сделать за нас https://expressjs.com/en/api.html#res.attachment

2025-01-05 15:28 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          response.set('Content-Disposition', `filename=${fileName}`);
я пробовал .attachment, он работает, но из-за того что он всегда добавляет `attachment` в начало хедера `Content-Disposition`, браузер всегда начинает скачивание файла даже если его можно отобразить в браузере. Такую крутую тему хочется оставить

2025-01-05 15:34 UTC, RiceWithMeat commented on src/utils/helpers/files/isFileDescriptorValid/isFileDescriptorValid.ts
> +  Buffer.isBuffer(value.file);
респект. strict нужен, чтобы при добавлении доп полей тоже падала валидация

2025-01-05 15:38 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          response.set('Content-Disposition', `filename=${fileName}`);
пришла в голову идея для ишью, сделать флажок `download` в для file чтобы управлять логикой скачки "вы файлы качаете? нет, только показываю. красивое..."

2025-01-05 15:39 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    expect(thirdResponse.body).toStrictEqual({ name: 'John', surname: 'Doe' });
Имхо в этих проверках нет смысла - это буквально проверка того, что res.json ставит правильный хэдер, что превращается в тестирование библиотеки

2025-01-05 15:39 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +  test('Should correctly process file polling', async () => {
Should correctly process the request with data polling setting/Should correctly process the request with file polling setting - хотелось бы синхронизировать названия этого теста и теста выше

2025-01-05 15:39 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          response.set('Content-Disposition', `filename=${fileName}`);
@debabin @MiaInturi как вам идея?

2025-01-05 15:47 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          response.set('Content-Disposition', `filename=${fileName}`);
Мне кажется надо сделать просто показывание по умолчанию, а если пользователь захочет, то в interceptors есть функция attachment. Ну либо сделать настройку для file: attachment | inline. Просто формулировка "показывай или качай" не совсем верная, т.к. inline тоже может качаться, если отображение не поддерживается браузером (например exe файлы)

2025-01-05 16:12 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    expect(thirdResponse.body).toStrictEqual({ name: 'John', surname: 'Doe' });
да и то и то думаю, учитывая что и то и то ставится res.json-ом

2025-01-05 16:14 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          response.set('Content-Disposition', `filename=${fileName}`);
соглы что это не нужно нам делать, это уже отвественость юзера

2025-01-05 16:16 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    expect(thirdResponse.body).toStrictEqual({ name: 'John', surname: 'Doe' });
чот смотрю у нас повсюду чекается статусКод, давай в ишью лучше вынесем. сейчас оч много править

2025-01-05 16:18 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    expect(thirdResponse.body).toStrictEqual({ name: 'John', surname: 'Doe' });
ну оставь тогда онли статус код

2025-01-05 16:20 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +    expect(thirdResponse.body).toStrictEqual({ name: 'John', surname: 'Doe' });
поправил

2025-01-05 16:21 UTC, MiaInturi commented on README.md
> +> Any changes to the data will not affect the file (and the response, respectively).
Это кста не так, response то будет затронут. Тут надо как раз написать, что вернется в ответе тот файл/путь, который придет из interceptor-ов

2025-01-05 16:33 UTC, RiceWithMeat commented on README.md
> +> Any changes to the data will not affect the file (and the response, respectively).
сейчас если чел поменяет в интерцепторе data.file то вернётся изменённая версия, а вот если поменяет data.path, то файл всё равно вернётся первоначальный. Если хотим поддержать, то надо добавить проверку после выполнения callResponseInterceptors `if (resolvedData.path !== data.path) { data.file = fs.readFileSync(path.resolve(data.file)) }`

2025-01-05 16:55 UTC, MiaInturi commented on README.md
> +> Any changes to the data will not affect the file (and the response, respectively).
я имел в виду, что вернется в content-disposition

2025-01-05 17:15 UTC, RiceWithMeat commented on README.md
> +> Any changes to the data will not affect the file (and the response, respectively).
переписал плюс добавил логику если чел поменяет path в интерцепторе. А то получалось data.file можно менять, а data.path нет

2025-01-06 10:52 UTC, MiaInturi requested changes

2025-01-06 10:52 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          if (!isFileDescriptorValid(data)) return next();
Так эта логика же ломает то, о чем мы говорили, когда созванивались. Там были разговоры о том, что пользователь может вернуть что угодно из interceptor-а (например, ошибку). И мы отправляем только файл в случае если это файловый дексриптор, а иначе отправляем обычный ответ

2025-01-06 10:52 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          response.set('Content-Disposition', `filename=${fileName}`);
А по итогу почему тред закрыли? Я думал мы согласились на attachment. Типо если пользователь хочет, то пусть поставит inline

2025-01-06 10:59 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          response.set('Content-Disposition', `filename=${fileName}`);
Выше же ты писал
```
Мне кажется надо сделать просто показывание по умолчанию, а если пользователь захочет, то в interceptors есть функция attachment.
```

Сейчас так и работает, всегда показываем файл в браузере, а если челу надо именно скачать, то пусть юзает .attachment

2025-01-06 11:00 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          response.set('Content-Disposition', `filename=${fileName}`);
я немного неправильно сформулировал свою мысль, имел в виду наоборот, но пофиг

2025-01-06 11:03 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          if (!isFileDescriptorValid(data)) return next();
Ок сделаю, забыл момент

2025-01-06 11:33 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          if (!isFileDescriptorValid(data)) return next();
а если чел вернул дескриптор, но с невалидным path, возвращаем 404 или дескриптор "как есть"?

2025-01-06 11:48 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          if (!isFileDescriptorValid(data)) return next();
сделал чтобы возвращалось 404 если path стал невалидным. имхо так правильнее

2025-01-06 11:48 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          if (!isFileDescriptorValid(data)) return next();
а если file descriptor перестал им быть (.file стал например числом или добавили доп поле, то возвращаем его "как есть")

2025-01-06 11:49 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          if (!isFileDescriptorValid(data)) return next();
в ридми тож дописал

2025-01-06 12:24 UTC, debabin commented on src/utils/helpers/files/isFileDescriptor/isFileDescriptor.ts
> +export const isFileDescriptor = (value: any): value is FileDescriptor =>
использоват зод имба план

2025-01-06 12:28 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +                  response: ({ path }) => ({ path, file: 123 })
123  -> давай сделаем там 'file', чтобы прям не набор цифр был

2025-01-06 13:36 UTC, merged