#22 into release@2.1.0 ☄️ rework file structure, add ts alias, fix husky precommit
siberiacancode/mock-config-server pull request #28
Opened 2023-03-19 09:49 UTC by debabin

2023-03-19 10:27 UTC, MiaInturi commented on tsconfig.dev.json
> +    "baseUrl": "./",
Мб baseUrl + paths тоже отделим переносом строки?

2023-03-19 12:25 UTC, MiaInturi requested changes

2023-03-19 12:25 UTC, MiaInturi commented on tsconfig.dev.json
> +      "@/*": ["./*"],
А есть ли смысл это этого alias? Просто когда будем добавлять новую папку мы так и так сделаем alias до нее. А во-вторых, из-за этого alias нельзя автоматизировать jest.confg: https://kulshekhar.github.io/ts-jest/docs/getting-started/paths-mapping/

2023-03-19 12:25 UTC, MiaInturi commented on tsconfig.json
> +{
А понял, в целом создание tsconfig.json оптимальное решение, но для расширения кругозора - можно еще так: https://youtrack.jetbrains.com/issue/WEB-28091/Support-different-names-for-tsconfig.json#focus=Comments-27-2475101.0-0

2023-03-19 13:37 UTC, RiceWithMeat commented on .husky/pre-commit
> +yarn test
я так понимаю если хоть один тест упадёт, то коммита не будет?

2023-03-19 14:49 UTC, RiceWithMeat commented on jest.config.js
> +    '@/server': '<rootDir>/src/utils/helpers',
ниже уже есть такой алиас `'@/utils/helpers': '<rootDir>/src/utils/helpers'`

2023-03-19 15:37 UTC, debabin commented on tsconfig.dev.json
> +    "baseUrl": "./",
Добавить отступ, просто там нет переносов

2023-03-19 15:38 UTC, debabin commented on tsconfig.json
> +{
в vs code не нашел решения как сделать, а раз трабла есть и в ide от intelij, до думаю лучше так и оставить

2023-03-19 15:40 UTC, debabin commented on src/utils/helpers/index.ts
> +export * from './graphql';
данные функции используется в not found middleware

2023-03-19 15:44 UTC, debabin commented on tsconfig.dev.json
> +      "@/*": ["./*"],
Вообще мы с можем и с ним юзать, но пока уберу alias, его не сложно добавить

2023-03-19 15:44 UTC, debabin commented on .husky/pre-commit
> +yarn test
Абсолютно верно

2023-03-19 15:44 UTC, debabin commented on jest.config.js
> +    '@/server': '<rootDir>/src/utils/helpers',
Тут опечатка, но благодаря @MiaInturi сделали супер круто

2023-03-19 15:48 UTC, debabin commented on src/utils/helpers/index.ts
> +export * from './isPlainObject/isPlainObject';
Я поставил плагин и по факту уже у нас подключен resolver просто он сделан через overrides, а не settings, правило я включил и вроде бы, как я и думал циклов нет

2023-03-19 16:32 UTC, RiceWithMeat commented on src/utils/helpers/isPlainObject/isPlainObject.test.ts
> +  test('All Primitive, array, function values should return false', () => {
Тесты не начинаются с `should`. Но тут такой кейс, что по-английски будет фигово написано и чот теперь кажется, что это правило следует отменить или заменить с "должно начинаться с should" на "должно содержать should". Что думаете?

2023-03-19 16:36 UTC, debabin commented on src/utils/helpers/isPlainObject/isPlainObject.test.ts
> +  test('All Primitive, array, function values should return false', () => {
Ну вообще у нас в моке уже не первый тест начинается не с should

2023-03-20 06:25 UTC, MiaInturi commented on src/utils/helpers/isPlainObject/isPlainObject.test.ts
> +    expect(isPlainObject(Array([]))).toBe(false);
А в чем прикол [] в Array оборачивать?)

2023-03-20 08:04 UTC, RiceWithMeat commented on jest.config.js
> +  },
Зачем этот код нужен? Странная регулярка, она разрешает например такие строки fwafwa\atsx, abc\gtsx, плюс у нас же нет tsx файлов

2023-03-20 08:04 UTC, RiceWithMeat commented on jest.config.js
> +  },
Больше к @MiaInturi вопрос, он добавлял

2023-03-20 08:18 UTC, RiceWithMeat commented on jest.config.js
> +  },
Вижу траблы есть с импортами без этого трансформа, тогда предлагаю заменить на такую регулярку `^.*\.ts$`, мне кажется она правильнее будет

2023-03-20 16:07 UTC, MiaInturi commented on src/utils/helpers/index.ts
> +export * from './isPlainObject/isPlainObject';
![no-error](https://user-images.githubusercontent.com/39031929/226399544-0fd3dd54-25ee-4ef6-9f7e-d4472b4bfc3c.png)
Я проверил и eslint-правило не работает. Вообще, исходя из [описания settings](https://eslint.org/docs/latest/use/configure/configuration-files#adding-shared-settings) - это не замена overrides, а помощь для плагинов, которые берут из settings настройки.

2023-03-20 16:09 UTC, MiaInturi commented on jest.config.js
> +  },
Регулярку я тупо скопировал не проверив - код нужен для того, чтобы ts-jest смотрел не на tsconfig.json, а на tsconfig.dev.json, но т.к. @debabin добавил tsconfig.json, то регулярку вообще можно удалить

2023-03-23 18:58 UTC, debabin commented on src/utils/helpers/isPlainObject/isPlainObject.test.ts
> +    expect(isPlainObject(Array([]))).toBe(false);
Чтобы все через конструкторы было, просто для единообразия сделал, могу везде убрать кроме symbol

2023-03-31 15:01 UTC, MiaInturi commented on bin/mock-config-server.ts
> +console.log('@');
Удалить

2023-03-31 15:03 UTC, MiaInturi commented on tsconfig.production.json
> +    "paths": {
А тут baseUrl поля нет

2023-04-14 11:22 UTC, RiceWithMeat approved these changes

2023-04-15 10:28 UTC, MiaInturi commented on src/utils/helpers/index.ts
> +export * from './isPlainObject/isPlainObject';
@debabin это до сих пор не работает

2023-04-15 16:57 UTC, debabin commented on src/utils/helpers/index.ts
> +export * from './isPlainObject/isPlainObject';
починил

2023-04-16 05:09 UTC, MiaInturi approved these changes

2023-04-17 16:05 UTC, merged