#34 into release@2.1.0 👹 shortcut command for start mock + cli
siberiacancode/mock-config-server pull request #35
Opened 2023-04-04 16:05 UTC by MiaInturi

2023-04-04 16:07 UTC, MiaInturi commented on bin/bin.ts
> +require('please-upgrade-node')(require('../../package.json'));
require нужен для синхронного подтягивания пакетов

2023-04-08 09:20 UTC, RiceWithMeat approved these changes

2023-04-10 18:56 UTC, debabin requested changes

2023-04-10 18:56 UTC, debabin commented on bin/bin.ts
> +const pleaseUpgradeNode = require('please-upgrade-node');
В итоге на сколько это супер полезная тема ?

2023-04-10 18:56 UTC, debabin commented on bin/cli.ts
> +import { start } from './mock-config-server';
Раз теперь название файла не равно cli команде, то мб назовем файл start ?

2023-04-10 18:56 UTC, debabin commented on bin/cli.ts
> +    .alias('help', 'h')
Правильно понимаю, что хелп красиво выведет существующие команды ?

2023-04-10 18:56 UTC, debabin commented on bin/bin.ts
> +parseCli();
Смущает название, там не только парс, но и старт. Как обычно такое именуют ?

2023-04-10 18:56 UTC, debabin commented on bin/mock-config-server.ts
> +export const start = async (argv: MockServerConfigArgv) => {
Я думаю лучше задать не аргв, а что то типо initialConfig, чтобы не было жесткой привязки к cli

2023-04-10 18:56 UTC, debabin commented on bin/mock-config-server.ts
> +    validateMockServerConfig(mockServerConfigExports.default, argv);
Я думаю лучше мержить конфиги на этом уровне, а не в функции валидации

2023-04-10 18:56 UTC, debabin commented on bin/validateMockServerConfig/validateMockServerConfig.ts
> +    const mergedMockServerConfig = {
А еще мерж не супер диип, пока так оставим или сразу сделаем ?

2023-04-13 15:16 UTC, MiaInturi commented on bin/cli.ts
> +    .alias('help', 'h')
да

2023-04-13 15:17 UTC, MiaInturi commented on bin/bin.ts
> +const pleaseUpgradeNode = require('please-upgrade-node');
ну вроде бы выглядит адекватно, но вообще я просто у других моков посмотрел, что они так делают

2023-04-13 15:19 UTC, MiaInturi commented on bin/mock-config-server.ts
> +export const start = async (argv: MockServerConfigArgv) => {
ну это bin файл, то есть он по любому вызовется из cli - мне кажется норм название. В данном случае лучше конкретизировать, нежели обобщать

2023-04-15 10:42 UTC, MiaInturi commented on bin/bin.ts
> +parseCli();
Ну у всех библиотек, что я смотрел, как и у нас, есть некоторый конвейер. Типо файл1 => файл2 => файл3 и т.д.
И предыдущий файл вызывает следующий (что логично). А название дают исходя из текущего шага. Поэтому я так и сделал

2023-04-15 10:43 UTC, MiaInturi commented on bin/bin.ts
> +parseCli();
Мб имеет смысл в таких случаях называть файл той сущностью, с которой они работают. Например вместо parseCli просто cli

2023-04-15 11:03 UTC, MiaInturi commented on bin/mock-config-server.ts
> +    validateMockServerConfig(mockServerConfigExports.default, argv);
Будет сложность в том, что на текущем уровне мы не уверены, что `mockServerConfigExports.default` - это объект и его можно мерджить. Если посмотреть в файл validateMockServerConfig, то можно увидеть, что сперва идет проверка, что `mockServerConfigExports.default` - это объект и у него есть все необходимые св-ва, и только потом мержим.

2023-04-15 17:03 UTC, debabin commented on bin/bin.ts
> +parseCli();
просто cli мне больше нравится

2023-04-17 16:06 UTC, debabin approved these changes

2023-04-22 08:00 UTC, merged