#37 into release@2.2.0 🌵 add 404 view
siberiacancode/mock-config-server pull request #44
Opened 2023-05-01 12:06 UTC by kvelian

2023-05-01 12:40 UTC, RiceWithMeat commented on src/static/views/pages/404/components/tabContent/index.ejs
> +<span>
надо обернуть в ашку get запросы

2023-05-01 12:57 UTC, RiceWithMeat commented on src/static/views/pages/404/components/tabContent/index.ejs
> +    <span>Read this for more information📘</span>
мб на `Read documentation📘 for more information` поменяем? Будет больше соотноситься с другой вьюшкой.  А то так кажется, что `documentation` это наша дока, а какой-то `this` что-то левое

2023-05-01 13:12 UTC, kvelian commented on src/static/views/pages/404/components/tabContent/index.ejs
> +<span>
отказались от этого решения

2023-05-02 17:42 UTC, MiaInturi commented on package.json
> +    "ejs": "^3.1.9",
а поч версия поменялась? Просто или ошибка была какая-то?

2023-05-02 17:43 UTC, MiaInturi commented on src/utils/types/interceptors.ts
> +export type InterceptorResponse<DataType extends any = any> = (
Тут кста Type приписку можно убрать, т.к. теперь нет коллизии имен типов

2023-05-02 17:44 UTC, MiaInturi commented on src/utils/types/interceptors.ts
> +export type InterceptorResponse<DataType extends any = any> = (
Кстати, мб переименуем тип. А то кажется, что это не интерцептор ответа, а ответ интерцептора

2023-05-03 14:04 UTC, kvelian commented on package.json
> +    "ejs": "^3.1.9",
просто, поскольку минорная, оставила

2023-05-05 16:28 UTC, debabin commented on src/core/middlewares/notFoundMiddleware/helpers/getGraphqlUrlSuggestions/getGraphqlUrlSuggestions.test.ts
>          url: new URL('http://localhost:31299/?query=query%20Getdevoper%20{%20developers%20}'),
возможно можно создать query параметр схему с помощью graphql пакет

2023-05-05 17:05 UTC, debabin requested changes

2023-05-05 17:05 UTC, debabin commented on src/static/views/styles/light.css
> +}
так можно же не делать класс тут, а вынести картинку в root или body секцию, я больше за root и уже сделать класс в хедере, что логичнее

2023-05-05 17:05 UTC, debabin commented on src/static/views/styles/light.css
> +body {
body -> .root

2023-05-05 17:05 UTC, debabin commented on src/static/views/styles/light.css
> +  --theme-image: url('/images/theme-light.svg');
я думаю стоит лучше нейминг сделать image- и тут уже название, чтобы все картинки начинались с ключевого слова, как например --background-что-то тут есть

2023-05-05 17:05 UTC, debabin commented on src/static/views/theme/index.js
> +}
данную функцию можно удалить и просто написать вот так 

```js
setScheme(getSavedScheme() ?? 'dark')
```

2023-05-05 17:05 UTC, debabin commented on src/static/views/theme/index.js
> +    saveScheme(scheme);
не думаю что есть смысл выноса этой функции, код тут супер простой

2023-05-05 17:05 UTC, debabin commented on src/static/views/theme/index.js
> +    const darkMedia = (scheme === 'dark') ? 'all' : 'not all';
@kvelian можешь описать как это работает

2023-05-05 17:05 UTC, debabin commented on src/utils/types/interceptors.ts
> +export type InterceptorResponse<DataType extends any = any> = (
изменил тут https://github.com/siberiacancode/mock-config-server/pull/46

2023-05-06 08:59 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/helpers/getGraphqlUrlSuggestions/getGraphqlUrlSuggestions.test.ts
>          url: new URL('http://localhost:31299/?query=query%20Getdevoper%20{%20developers%20}'),
ниче не поняла, потом расскажешь
поставила эмодзи👀, в похожих случаях ниже буду просто ставить этот эмодзи, а не писать

2023-05-06 09:18 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +    expect(response.text).toContain('QUERY  GetPosts');
не лишний
а получилось так, чтобы не склеивались baseurl и operationName (notFoundMiddleware.ts:30), хотелось сделать вариант получше и не громоздко, но не придумалось

2023-05-06 09:19 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +
она используется буквально в каждом тесте

2023-05-06 09:47 UTC, kvelian commented on src/static/views/components/tab/tabContentContainer.ejs
> +</div>
хотела чтобы было единообразно с соседним файлом, + семантически это контейнер для контента таба, а не сам контент таба

2023-05-06 09:50 UTC, kvelian commented on src/static/views/pages/404/index.ejs
> +  <title>404 - mocs</title>
404 - mocs выглядит как-то сексуальнее, Mock Config Server длинно, во вкладке не видно будет нифига это длинное все, а 404 и подавно 
может mocs - 404 хотя бы?

2023-05-06 09:53 UTC, kvelian commented on src/static/views/pages/404/index.ejs
> +  <link rel="stylesheet" href="/styles/light.css" media="(prefers-color-scheme: light)" />
в отдельный файл, в константы внутри этого или чего ты имеешь ввиду? а так то вообще это надо в header.ejs мб унести, так как тема идет вместе с ним

2023-05-06 09:56 UTC, kvelian commented on src/static/views/pages/404/index.ejs
> +  <script defer src="/components/tab/index.js"></script>
теперь та особо и нечего группировать

2023-05-06 10:34 UTC, kvelian commented on src/static/views/components/header/index.css
> +}
стайлинт прикрутила, у нас на работе девочки делали какую группировку? испытываю непреодолимое желание тупо спиздить

2023-05-06 11:16 UTC, kvelian commented on src/static/views/pages/404/index.ejs
> +                    params: {api: api.graphql, requestSuggestions: graphqlRequestSuggestions.map(item => ({method: item.operationType, path: item.operationName}))}}})  %>
есть  плагины (ejs beautify), которые форматируют ejs файлы, как html, но игнорят js внутри, как форматнуть и его не нашла

2023-05-06 11:19 UTC, kvelian commented on src/static/views/pages/404/index.ejs
> +                    {itemVariant: api.rest, children: { path: 'pages/404/components/tabContent/index',
не хочу в 4-6 местах бросать строку и потом руками её менять ходить, поэтому унесла в константу и константу же и использую

2023-05-06 11:21 UTC, kvelian commented on src/static/views/pages/404/index.ejs
> +                    {itemVariant: api.rest, children: { path: 'pages/404/components/tabContent/index',
> itemVariant не до конца понял смысл этого параметра

это пропс для присвоения уникального id и значения для итемов в табе, который тут инклудится - itemVariant

2023-05-07 10:53 UTC, MiaInturi commented
В коммите еще не хватает номера issue

2023-05-07 14:15 UTC, MiaInturi requested changes

2023-05-07 15:03 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/getRestUrlSuggestions.test.ts
> +      { method: 'get', path: '/posts/:postId' },
мне тоже так кажется
@RiceWithMeat, согласен?

2023-05-07 15:05 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/getRestUrlSuggestions.test.ts
> +    ).toEqual([{ method: 'get', path: '/users/5?backurl=someUrl?action=success' }]);
ожидаемый результат одинаковый, но входные значения варьируются, не уверена, что достаточно будет оставить один
Но тогда разумнее разнести по разных тестам по семантике (тип уровнь различий), если возможно
@RiceWithMeat

2023-05-07 15:08 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/helpers/getGraphqlUrlSuggestions/getGraphqlUrlSuggestions.test.ts
>          url: new URL('http://localhost:31299/base/re/pos?query=query%20devel%20{%20developers%20}'),
я подумала да, что можно слить пробелы, но с эстетикой сам html справится, поэтому это нужно по сути только для теста, могу добавить, но надо ли?

2023-05-07 15:12 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
>        if (graphqlQuery) {
склеила в один  if , но мб ты не это имел ввиду

2023-05-07 15:14 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +  server.set('view engine', 'ejs');
а не логичнее наоборот сначала server.set('view engine', 'ejs');, а потом уже подключение контента (фактически ejsного), а далее статики для него, в порядке того, что для чего нужно

2023-05-07 15:17 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +  });
> Тут надо еще content-type ответа проверять, а то вдруг нам просто json пришел

формально да, по факту тест так и так упадет, если придет json ввиду структуры самого toContain содержимого
тоже самое касается и тестов ниже

2023-05-07 15:23 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +describe('notFoundMiddleware: REST', () => {
не совсем, логика для graphql  и rest  в notFoundMiddleware указана отдельно и она друг от друга не зависит, так что одно может разъебаться независимо от другого

2023-05-07 15:25 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +
@MiaInturi @RiceWithMeat Дима тут настаивал на обсуждении

2023-05-07 17:26 UTC, MiaInturi requested changes

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/components/tab/index.css
> +.tab-content {
А в чем смысл этого класса?

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/pages/404/index.ejs
> +<body class="<%= !graphqlRequestSuggestions.length ? api.rest : api.graphql %>">
А почему через отрицание сделано? Не проще ли `graphqlRequestSuggestions.length ? api.graphql : api.rest`?

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/theme/index.js
> +function getSavedScheme() {
А почему мы везде используем `function`, а не стрелочные функции? Для бОльшей совместимости?

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/theme/index.js
> +    localStorage.setItem('color-scheme', scheme);
название ключа в `color-scheme` можно вынести в константу

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/theme/index.js
> +    if (getSavedScheme() === 'light') setScheme("dark");
Можно вот так сделать `setScheme(getSavedScheme() === 'light' ? 'light' : 'dark')`

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/theme/index.js
> +    [...lightStyles].forEach((link) => {
Нет смысла в деструктуризации массивов стилей

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/styles/light.css
> +body {
Ну кстати мне тоже больше нравится завязаться на класс, а не на тег

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/styles/index.css
> +.link {
А должны ли эти стили быть в этом файле? Я думал тут будут только стили "общие"

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/pages/404/index.ejs
> +  <style>
А почему не в css?

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/pages/404/index.ejs
> +  <link rel="stylesheet" href="/components/header/index.css" />
Пусть link будут вместе и script будут вместе

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/pages/404/index.ejs
> +  <% const rootPath = (path) => `../../${path}` %>
А причем тут props drilling?

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/pages/404/index.ejs
> +          <span>Return on main page</span>
Нет смысла в теге span, т.к. тег a уже итак инлайновый

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/pages/404/index.ejs
> +          <span>Return on main page</span>
И в целом тег span не несет в себе никакой семантики и нужен только для стилизации inline частей страницы, так что его удаление ни на чем не отразится

2023-05-07 17:26 UTC, MiaInturi commented on src/static/views/pages/404/index.ejs
> +    <div class="body">
Класс надо обязательно переименовать. Типо класс `.body`, но почему-то он накидывается не на тег `body`. Очень странно. Думаю лучше подойдет тот же `content`

2023-05-07 17:28 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/getRestUrlSuggestions.test.ts
> +    ).toEqual([{ method: 'get', path: '/users/5?backurl=someUrl?action=success' }]);
Так входные значения по сути варьируются чисто синтаксически, а не семантически. Нам в тесте без разницы какой query будет, главное чтобы он просто был

2023-05-07 17:29 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/helpers/getGraphqlUrlSuggestions/getGraphqlUrlSuggestions.test.ts
>          url: new URL('http://localhost:31299/base/re/pos?query=query%20devel%20{%20developers%20}'),
Ну это буквально легче поддерживать и читать. Почему нет?

2023-05-07 17:29 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
>        if (graphqlQuery) {
Именно это имел в виду

2023-05-07 17:31 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +  server.set('view engine', 'ejs');
Ну тут мне уже без разницы) Мне не нравилось, `server.set` для view были разделены `server.use`. А в каком порядке это все будет после фикса - уже неважно

2023-05-07 17:39 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +  });
Не понял. `response.text` будет вполне обычным текстом и для application/json ответа и toContain точно так же отработает.
```
.toContain can also check whether a string is a substring of another string
```
это из документации jest

2023-05-07 17:42 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +describe('notFoundMiddleware: REST', () => {
Не очень понял, мб проще будет голосом

2023-05-17 04:38 UTC, kvelian commented on src/static/views/components/tab/index.js
> +tabInit();
а как же чтобы понятней и явней было, более структурированно и тд
буквы бесплатные опять таки

2023-05-17 04:43 UTC, kvelian commented on src/static/views/components/tab/tabItemContainer.ejs
> +<div class="tab-items-container">
не увидела где написал, контейниер убрала и переименовала малеха

2023-05-17 05:40 UTC, kvelian commented on src/static/views/styles/light.css
> +body {
а чем это оправданно? завязываться на конкретные теги, если это нужно, тоже ок, зачем создавать класс root чтобы получить тот же результат?  рисков использования body нет, информативность тоже не снижается

2023-05-17 05:42 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/getRestUrlSuggestions.test.ts
> +      { method: 'get', path: '/posts/:postId' },
оставила второй, чтобы было проверка, что мы в '/posts/:postId' не упали, вместо '/posts/:postId/comments/:commentId'

2023-05-17 05:47 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/getRestUrlSuggestions.test.ts
> +    ).toEqual([{ method: 'get', path: '/users/5?backurl=someUrl?action=success' }]);
так в синтаксических вариациях и суть проверяемой функции
другое дело, что я чет посмотрела сам тест и не поняла, а что он проверяет в итоге, тип чел ввел штуку, а мы ему говорим "возможно ты ошибся, на тебе тоже самое, что ты ввел"

2023-05-17 05:48 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/helpers/getGraphqlUrlSuggestions/getGraphqlUrlSuggestions.test.ts
>          url: new URL('http://localhost:31299/base/re/pos?query=query%20devel%20{%20developers%20}'),
забей, я почему-то про двойные пробелы тогда подумала

2023-05-17 05:57 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +  });
Добавить можно, но только в угоду явности ожидаемого результата в тесте
![image](https://github.com/siberiacancode/mock-config-server/assets/81089091/17023e12-e245-47bc-8a21-cf6c5bc20234)

2023-05-17 06:07 UTC, kvelian commented on src/static/views/components/tab/index.css
> +.tab-items-container {
оставила вариант ${какое-то название в множественном числе} -> ${какое-то название-item}

2023-05-17 06:21 UTC, kvelian commented on src/static/views/components/tab/index.css
> +.tab-item:not(.tab-item-active):hover {
.tab-item-active это правда, оно нужно было для старой логики
можно попробовать switchTab функцию как-то прозрачнее написать, потому что если там в класс писать id итема, то в разных местах этот tab-item рандомный появится, фиг знает что прозрачнее

2023-05-17 06:23 UTC, kvelian commented on src/static/views/components/tab/index.css
> +.tab-content {
что контент таба по умолчанию скрыт, если не указано иного. Иное, если какой-то таб активен

2023-05-17 06:25 UTC, kvelian commented on src/static/views/theme/index.js
> +function getSavedScheme() {
прост)0
а вообще есть флёр старья, когда пишешь на тупо js, который импортится в html, и как-то неосознанно хочется писать без флекса и хипстоты

2023-05-17 06:26 UTC, kvelian commented on src/static/views/theme/index.js
> +    localStorage.setItem('color-scheme', scheme);
есть смысл выносить это в константу с таким же наименованием, если я её сразу уже вызываю? крч объясните правила игры, тут в константу вынести ок, а функцию объявить в по сути эквивалентном кейсе не ок

2023-05-17 06:28 UTC, kvelian commented on src/static/views/theme/index.js
> +    if (getSavedScheme() === 'light') setScheme("dark");
ну думаю тут два стула, либо function + if или arrowFunction + (я забыла как это пижня называется). Как считаете нужным, так и сделаю

2023-05-17 10:49 UTC, kvelian commented on src/static/views/theme/index.js
> +    [...lightStyles].forEach((link) => {
можно в принципе и foreach убрать, но с ним красивее, чем обращение к 0, и в теории может быть таких styles link-ов более 1, но логичнее добавлять foreach когда оно понадобится

2023-05-17 10:50 UTC, kvelian commented on src/static/views/styles/index.css
> +.link {
а это общий стиль и есть, для всех линков

2023-05-17 10:51 UTC, kvelian commented on src/static/views/pages/404/index.ejs
> +  <style>
можно и в css но конкретно этого page

2023-05-18 14:10 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/helpers/getRestUrlSuggestions/getRestUrlSuggestions.test.ts
> +    ).toEqual([{ method: 'get', path: '/users/5?backurl=someUrl?action=success' }]);
Ну я согласен еще что 1ый expect можно оставить, т.к. он без `:userId`, но второй и третий expect этого теста это же буквально одно и то же, просто `firstParam` заменили на `backurl`, `secondParam` на `action`. С таким же успехом можно написать любые последовательности символов вместо `firstParam` и `secondParam`.

2023-06-06 13:19 UTC, kvelian commented on src/core/middlewares/notFoundMiddleware/helpers/getGraphqlUrlSuggestions/getGraphqlUrlSuggestions.test.ts
>          url: new URL('http://localhost:31299/?query=query%20Getdevoper%20{%20developers%20}'),
для явного соответствия исходных значений и результата + избегания путаницы при падении теста (наша функция упала или нет), зависимость вносить не будем, оставим как есть

2023-06-06 13:31 UTC, debabin commented on src/static/views/pages/404/index.ejs
> +  <title>404 - mocs</title>
Тут хорошо бы еще хлопушку бахнуть и сделать сразу нейминг title для views

2023-06-26 13:59 UTC, MiaInturi commented
Поменяй сообщение в предыдущем коммите плз на отформатированное))))

2023-06-26 16:29 UTC, MiaInturi requested changes

2023-06-26 16:29 UTC, MiaInturi commented on src/static/views/assets/scheme/index.js
> +const switchScheme = () => setScheme(getSavedScheme() === 'light' ? 'light' : 'dark');
Круто 👍

2023-06-26 16:29 UTC, MiaInturi commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.ts
> +    const isHtmlRequest =
Думаю более подходящее название `isRequestSupportHtml`

2023-06-26 16:49 UTC, MiaInturi commented on src/static/views/components/schemeButton/index.js
> +document.getElementById('scheme-switcher').addEventListener('click', () => window.switchScheme());
Думаю не лучшая идея в разные файлы класть listener и логику switchScheme - я думаю switchScheme можно сюда перенести. + сейчас не работает ничего, т.к. js не видит функцию window.switchScheme. И я не знаю почему

2023-06-26 17:03 UTC, kvelian commented on src/static/views/components/schemeButton/index.js
> +document.getElementById('scheme-switcher').addEventListener('click', () => window.switchScheme());
потому что стрелочные функции сосать, уже вернули назад старые добрые функции

2023-06-26 17:12 UTC, kvelian commented on src/static/views/components/schemeButton/index.js
> +document.getElementById('scheme-switcher').addEventListener('click', () => window.switchScheme());
кнопка, на которую навешивается листнер, как и само навешивание листнера, никак не относится к логике смены схемы, где лежит функция switchScheme, поэтому там ей тоже не место
Но растаскивание свич схемы от хэдера отдельно тоже убрали

2023-06-28 15:02 UTC, MiaInturi commented on src/static/views/assets/styles/global.css
> +  color-scheme: light dark;
Короче, данное правило надо сетить динамически (либо в CSS, либо в meta-тег), т.к. возможна след. ситуация. У пользователя в системе стоит темная тема, но на сайте он выбрал светлую тему. Тогда светлым будут все стилизованные части, а нестилизованные (скроллбар, например) будут темными.

2023-07-01 08:32 UTC, debabin approved these changes

2023-07-01 12:08 UTC, merged