#43 into release@2.2.0 🐘 watch mode for restart server on files change
siberiacancode/mock-config-server pull request #45
Opened 2023-05-02 12:47 UTC by RiceWithMeat

2023-05-02 13:11 UTC, MiaInturi commented on package.json
> +    "dev": "nodemon --watch src --watch bin --watch mock-server.config.ts -e js,ts,ejs --exec \"yarn start\"",
И вообще, это же package json. Юзеры не смогут запускать отсюда скрипты без приседаний

2023-05-02 13:11 UTC, RiceWithMeat commented on package.json
> +    "dev": "nodemon --watch src --watch bin --watch mock-server.config.ts -e js,ts,ejs --exec \"yarn start\"",
тру

2023-05-02 13:12 UTC, MiaInturi commented on package.json
> +    "dev": "nodemon --watch src --watch bin --watch mock-server.config.ts -e js,ts,ejs --exec \"yarn start\"",
надо использовать что-то типо этой функции в bin/start https://www.geeksforgeeks.org/node-js-fs-watchfile-method/

2023-05-07 17:44 UTC, MiaInturi commented on tsconfig.dev.json
> +    "newLine": "lf",
Думаю лучше это внести во все  tsconfig файлы

2023-05-08 08:36 UTC, RiceWithMeat commented on tsconfig.dev.json
> +    "newLine": "lf",
это уже есть в других тсконфигах, в дев конфиге не хватало просто

2023-05-08 15:27 UTC, MiaInturi requested changes

2023-05-08 15:27 UTC, MiaInturi commented on bin/configWatcher.ts
> +    name: 'watchPlugin',
Думаю приписка `plugin` не нужна, т.к. и так ясно, что это плагин. Например, в доке esbuild приписки не ставят

2023-05-08 15:27 UTC, MiaInturi commented on bin/configWatcher.ts
> +          server = start(argv, result.outputFiles ?? []);
У нас `write: false` стоит в настройках билда, так что можно написать `result!.outputFiles` (инфа из документации)

2023-05-08 15:27 UTC, MiaInturi commented on bin/configWatcher.ts
> +    setup: (build) => {
Переменную `server` можно объявить внутри `setup`

2023-05-08 15:27 UTC, MiaInturi commented on bin/start.ts
> +import type { OutputFile } from 'esbuild';
Пусть между `import` и `#!usr...` будет пустая строка, как раньше

2023-05-08 15:27 UTC, MiaInturi commented on src/server/startMockServer/startMockServer.ts
> +  const destroy: Server['close'] = (callback) => {
Мне кажется лучше сделать `instance.destroy = ...`. Т.к. сейчас у тебя функции `createMockServer` и `startMockServer` возвращают instance в разных уровнях вложенности. `createMockServer` - возвращает сам instance, `startMockServer` - возвращает объект с полем instance

2023-05-08 15:27 UTC, MiaInturi commented on src/server/startMockServer/startMockServer.ts
> +    return instance;
Не особо понял смысл этого return

2023-05-08 16:12 UTC, RiceWithMeat commented on src/server/startMockServer/startMockServer.ts
> +  const destroy: Server['close'] = (callback) => {
я так сначала и сделал и были траблы с типизацией. мы же не можем просто сделать `instance.destroy = ф-ия`, тк его нет в `Server`, возвращаемом из `.listen()`. Соотвественно надо либо вводить новый тип, в котором будет этот метод, либо писать `instance: Server & {destroy?: ...} = listen()` и после соответственно сетить destroy (а потом ещё в плагине проверять, что метод не undefined). В общем вводить новый тип не оч показалось и с `& { destroy?: ... }` ещё хуже. Если будем вводить новый тайп, то как назовём его?

2023-05-08 16:15 UTC, RiceWithMeat commented on bin/configWatcher.ts
> +          server = start(argv, result.outputFiles ?? []);
сначала так и писал, но мне кажется `?? []` лучше `!`, меньше вопросов вызывает. Плюс если вдруг write будет true, то код сломается, тк. outputFiles станет undefined и приложение упадёт

2023-05-08 16:32 UTC, RiceWithMeat commented on src/server/startMockServer/startMockServer.ts
> +  const destroy: Server['close'] = (callback) => {
можно кстати сделать проще и просто ретёрнить функцию destroy. Сам инстанс нам не пригодится

2023-05-09 13:35 UTC, MiaInturi requested changes

2023-05-09 13:35 UTC, MiaInturi commented on bin/cli.ts
> +export const cli = async () => {
async бесполезный

2023-05-09 13:35 UTC, MiaInturi commented on bin/configWatcher.ts
> +  ctx.watch();
Думаю надо добавить еще флаг в cli, который watch будет отключать (полезно, если, например, раскатывать мок на сервер какой-то или для автотестов, которые открывают много соединений)

2023-05-09 13:35 UTC, MiaInturi commented on src/server/startMockServer/startMockServer.ts
> +  const destroy: Server['close'] = (callback) => {
Ну можно как раз и написать `instance: Server & {destroy: ...}`. Я просто не понимаю, зачем делать `destroy` опциональным? Он же всегда будет инициализирован

2023-05-10 15:58 UTC, MiaInturi requested changes

2023-05-10 15:58 UTC, MiaInturi commented on bin/cli.ts
> +      noWatch: {
я думаю надо alias добавить: `nw например`

2023-05-10 15:58 UTC, MiaInturi commented on bin/cli.ts
> +      noWatch: {
Или вообще сделать наоборот, чтобы был флаг `watch/w`. Как у других моков

2023-05-10 15:58 UTC, MiaInturi commented on bin/configWatcher.ts
> +  }
Мне кажется надо прям две большие отдельные ветки кода создать. Один будет без watch использовать build, второй с watch будет использовать context

2023-05-10 16:16 UTC, RiceWithMeat commented on bin/cli.ts
> +      noWatch: {
nw будет вообще не понятно что и watch режим мне кажется стоит по умолчанию включённым держать, в 99% случаев его захотят включить же

2023-05-10 16:59 UTC, MiaInturi commented on bin/configWatcher.ts
> +  } satisfies BuildOptions;
Прикольно кстати, что вынес, чтобы не дублировать

2023-05-10 17:02 UTC, MiaInturi commented on bin/cli.ts
> +        default: false
Думаю нет смысла от default значения, оно и так falsy будет

2023-05-10 17:21 UTC, RiceWithMeat commented on README.md
> +  --noWatch, --nw       Disables server restart after config file changes
одно тире работает только если одна буква

2023-05-10 17:29 UTC, MiaInturi commented on bin/cli.ts
> +        default: false
ну можно добавить мб, просто у некоторых штук дефолтных значений быть вообще не должно, как например, static path или путь до конфига.

2023-05-10 17:45 UTC, RiceWithMeat commented on bin/cli.ts
> +        default: false
ну путь до конфига есть './mock-server.config.(ts,js...)'

2023-05-10 18:29 UTC, MiaInturi commented on bin/cli.ts
> +        default: './mock-server.config.(?:ts|mts|cts|js|mjs|cjs)'
Тут надо убрать,  т.к. ты в строке пытаешься сделать regex. default значение же не только для команды `--help`. Они еще и передаются в код через argv

2023-05-10 18:29 UTC, MiaInturi approved these changes

2023-05-10 18:31 UTC, RiceWithMeat commented on bin/cli.ts
> +        default: './mock-server.config.(?:ts|mts|cts|js|mjs|cjs)'
тру

2023-05-11 15:11 UTC, debabin commented on bin/configWatcher.ts
> +    start(argv, outputFiles ?? []);
давай сделаем сразу передачу только конфига, а не массива

2023-05-11 15:49 UTC, RiceWithMeat commented on bin/configWatcher.ts
> +    start(argv, outputFiles ?? []);
имеешь ввиду вынести из start() работу с парсом outputFiles[0].text в отдельную функцию и вызывать её заранее?

2023-05-11 15:59 UTC, RiceWithMeat commented on .gitignore
> +mock-server.config.mjs
regexp в гитигноре не поддерживается, можно эти строки сократить до двух так: mock-server.config.[jt]s
mock-server.config.[cm][jt]s. норм?

2023-05-11 16:22 UTC, RiceWithMeat commented on bin/configWatcher.ts
> +  }
чот думаю и кажется не очень хорошая идея разделять функцию, запускающую сервер на две функции. смысл разделять ответственность если мы уже в этом файле можем решить в зависимости от argv.watch флага в каком режиме сер запустить. можно более понятно переименовать функцию тогда, а то сейчас configWatch фактически только в одном кейсе из двух имеет смысл. что думаешь?

2023-05-11 16:27 UTC, debabin commented on .gitignore
> +mock-server.config.mjs
mock-server.config.* ? не будет работать ?

2023-05-11 16:28 UTC, debabin commented on bin/configWatcher.ts
> +  }
> да, можно разделить на две функции startServer и startServerWithWatch, но тогда надо решить куда вынести buildOptions, они же общие

я думаю вынести можно выше и прокидывать уже мок конфиг в функции

2023-05-11 16:29 UTC, debabin commented on bin/configWatcher.ts
> +  }
> чот думаю и кажется не очень хорошая идея разделять функцию, запускающую сервер на две функции. смысл разделять ответственность если мы уже в этом файле можем решить в зависимости от argv.watch флага в каком режиме сер запустить. можно более понятно переименовать функцию тогда, а то сейчас configWatch фактически только в одном кейсе из двух имеет смысл. что думаешь?

да нормальный вариант, наверное мне больше не нравилось построение функции

2023-05-11 16:30 UTC, debabin commented on bin/configWatcher.ts
> +    start(argv, outputFiles ?? []);
start(argv, outputFiles ?? []); -> mockConfig = outputFiles[0] start(argv, mockConfig);

2023-05-11 16:46 UTC, RiceWithMeat commented on .gitignore
> +mock-server.config.mjs
будет, но тогда любые расширения запрещены будут (что на самом деле логично). сделаю

2023-05-12 16:20 UTC, MiaInturi commented on bin/start.ts
> +import type { BuildOptions, Plugin } from 'esbuild';
Чет немного запутанно, что у нас два файла - `start` и `runServer`. Мб этот файл будет типо `build`? А финальный файл будет называться уже `start` как раз

2023-05-12 16:58 UTC, debabin requested changes

2023-05-13 10:36 UTC, debabin approved these changes

2023-05-13 13:04 UTC, MiaInturi commented on bin/run.ts
> +export const run = (mockConfig: MockServerConfig, argv: MockServerConfigArgv, ) => {
Тут запятая лишняя. Как будто для 3-его агрумента

2023-05-13 14:19 UTC, MiaInturi approved these changes

2023-05-14 08:05 UTC, merged