#41 into relese@2.2.0 ☄️ add api level interceptros for rest, graphql
siberiacancode/mock-config-server pull request #46
Opened 2023-05-05 12:05 UTC by debabin

2023-05-05 12:13 UTC, RiceWithMeat approved these changes

2023-05-07 10:45 UTC, MiaInturi requested changes

2023-05-07 10:45 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.test.ts
> +      mockServerConfig.graphql ?? { configs: [] },
По сути это тесты на graphql, то есть по любому graphql конфиг будет. Мб тут стоит использовать либо `!` оператор, либо (что мне нравится больше) для функции createServer сделать параметр `graphql` обязательным

2023-05-07 10:45 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +      mockServerConfig.rest ?? { configs: [] },
Ну тут то же самое, только с обязательностью `rest`

2023-05-07 10:45 UTC, MiaInturi commented on src/utils/types/interceptors.ts
> +export type ResponseInterceptor<DataType extends any = any> = (
Приписку `type` можно убрать, она была раньше добавлена, т.к. была коллизия имен

2023-05-07 10:45 UTC, MiaInturi commented on src/utils/helpers/interceptors/callRequestInterceptors/callRequestInterceptors.test.ts
> +  test('Should call all passed request interceptors in order: route -> api -> request -> server', () => {
Надо убрать route из этой цепочки + `api` идет после `request`

2023-05-07 10:45 UTC, MiaInturi commented on src/utils/helpers/interceptors/callRequestInterceptors/callRequestInterceptors.test.ts
> +    const apiInterceptor = jest.fn();
Немного режет глаз, что переменные объявлены не в "иерархическом" порядке. Но мб это мои тараканы))

2023-05-07 10:45 UTC, MiaInturi commented on src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.test.ts
> +  test('Should call all passed response interceptors in order: route -> api -> request -> server', () => {
`api` после `request`

2023-05-07 10:45 UTC, MiaInturi commented on src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.test.ts
> +    const apiInterceptor = jest.fn((data) => `${data}apiInterceptor;`);
Ну тут то же самое про "иерархичность" объявления переменных

2023-05-07 10:45 UTC, MiaInturi commented on src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.test.ts
> +      apiInterceptor.mock.invocationCallOrder[0]
тут должен быть request

2023-05-07 10:45 UTC, MiaInturi commented on src/utils/helpers/interceptors/callResponseInterceptors/callResponseInterceptors.test.ts
> +      apiInterceptor.mock.invocationCallOrder[0]
А то сейчас два разных интерцептора сравнивают свой порядок вызова с `apiInterceptor`

2023-05-07 14:33 UTC, debabin commented on src/utils/helpers/interceptors/callRequestInterceptors/callRequestInterceptors.test.ts
> +    const apiInterceptor = jest.fn();
нет, я везде старался сделать иерархию, так что мне тоже режет, просто походу пропусти

2023-05-07 17:50 UTC, MiaInturi commented on src/utils/helpers/interceptors/callRequestInterceptors/callRequestInterceptors.test.ts
> +        apiInterceptor,
сперва request)

2023-05-08 13:43 UTC, MiaInturi approved these changes

2023-05-08 16:00 UTC, merged