#49 ☄️ rework request interceptor
siberiacancode/mock-config-server pull request #50
Opened 2023-05-09 06:09 UTC by debabin

2023-05-09 14:50 UTC, MiaInturi requested changes

2023-05-09 14:50 UTC, MiaInturi commented on README.md
> +  - `setCookie` (name) => string | undefined;
лишние `;` в конце строк

2023-05-09 14:50 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
>      expect(requestInterceptor.mock.calls.length).toBe(1);
По сути тут второй запрос теперь не нужен теперь, т.к. раньше он был нужен для проверки совместной работы interceptor-ов, который  сейчас проверяется в единственном экземпляре

2023-05-09 14:50 UTC, MiaInturi commented on src/utils/helpers/parseCookie/parseCookie.ts
> +  const array = cookie.split(';');
Я думаю `array` надо назвать более осмысленно. Например `cookiePairs`

2023-05-09 14:50 UTC, MiaInturi commented on src/utils/helpers/parseCookie/parseCookie.ts
> +export const parseCookie = (cookie: string) => {
Я думаю аргумент лучше назвать cookieHeader, чтобы было понятно, почему его делим

2023-05-09 18:16 UTC, debabin commented on src/utils/helpers/interceptors/index.ts
> +export * from './callRequestInterceptor/callRequestInterceptor';
на export import/order не работает, а для eslint такого правила нет

2023-05-10 16:02 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
>      expect(requestInterceptor.mock.calls.length).toBe(1);
Понял

2023-05-10 16:57 UTC, MiaInturi approved these changes

2023-05-11 15:21 UTC, debabin commented on src/utils/helpers/parseCookie/parseCookie.ts
> +    cookies[key] = value;
Сразу тут отвечу, в хедере из типипазиции это field, с кукой согласен тут можно сделать name, а не key

![image](https://github.com/siberiacancode/mock-config-server/assets/45297354/476b92c1-501f-46bc-955d-0075f6918dea)

2023-05-11 15:22 UTC, debabin commented on src/utils/helpers/parseCookie/parseCookie.ts
> +    cookies[key] = value;
а еще я забыл написать тесты на данную функцию, сейчас добавлю

2023-05-11 15:24 UTC, debabin commented on src/utils/helpers/parseCookie/parseCookie.ts
> +    cookies[key] = value;
А для кук в типизации вот такой нейминг 
![image](https://github.com/siberiacancode/mock-config-server/assets/45297354/cabde55d-7f5a-4c89-8871-bbd3e45f9ca8)

2023-05-13 12:39 UTC, merged