#57 into release@2.3.0 🐘 add cookies support
siberiacancode/mock-config-server pull request #58
Opened 2023-05-18 06:45 UTC by RiceWithMeat

2023-05-18 08:23 UTC, debabin commented on src/core/middlewares/cookiesMiddleware/cookiesMiddleware.ts
> +export const cookiesMiddleware = (server: Express) => {
переименовать в cookieParseMiddleware + тесты

2023-05-18 08:25 UTC, debabin commented on src/utils/helpers/parseCookie/parseCookie.ts
> +export const parseCookie = (cookieHeader: string | string[]) => {
оставить только string вариант для функции и добавить вышел проверку на typeof string для header cookie

2023-05-18 12:11 UTC, MiaInturi requested changes

2023-05-18 12:11 UTC, MiaInturi commented on src/core/middlewares/cookieParseMiddleware/cookieParseMiddleware.test.ts
> +    expect(parsedCookies).toMatchObject({ cookieName: 'cookieValue' });
Думаю toEqual тут больше подойдет, т.к. toMatchObject сравнивает по логике подмножества

2023-05-18 12:11 UTC, MiaInturi commented on src/utils/types/rest.ts
>  export type RestEntitiesValue = BodyValue | QueryValue | HeadersValue | ParamsValue;
Сюда не добавлен CookiesValue

2023-05-18 12:11 UTC, MiaInturi commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
>  const validateHeadersOrParams = (headersOrParams: unknown, entity: string) => {
HeadersOrParamsOrCookies по сути должно быть. Крч нет валидации cookies. +Тесты на это нужны. То же самое для graphql

2023-05-18 12:17 UTC, RiceWithMeat commented on src/utils/helpers/parseCookie/parseCookie.ts
> +  const cookiePairs = cookieHeader.split('; ');
в cookieHeader приходит с пробелом после ;. и у cookiePairs после сплита все значения кроме первого имеют пробел в начала. хотя там на самом деле идёт trim() и он как раз это пофиксит. так что я фигню сделал, пофикшу

2023-05-18 13:49 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +  test('Should correctly handle cookies entity only with correct type', () => {
Тот тест проверяет все типы для поля entities, этот тест проверяет типы для поля entities[cookie] - по сути это разные вещи

2023-05-18 13:49 UTC, MiaInturi approved these changes

2023-05-18 14:35 UTC, debabin requested changes

2023-05-18 14:35 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +    const correctEntitiesValues = [{}, { headers: { key: 'value' } }, { cookies: { cookieName: 'cookieValue' } }, undefined];
а разве тут не лишний кейс с куки, мне кажется он или тут не нужен или надо в кейсе с хедером сразу все дописать

2023-05-18 14:35 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +    const correctEntitiesValues = [{}, { headers: { key: 'value' } }, { cookies: { cookieName: 'cookieValue' } }, { params: { paramKey: 'paramValue' } }, undefined];
тут также я вот думаю, может просто в 1 объект все ?

2023-05-18 14:35 UTC, debabin commented on src/core/middlewares/cookieParseMiddleware/cookieParseMiddleware.test.ts
> +    await request(server).get('/').set({ cookie: 'cookieName=cookieValue' });
мб сделаем похожий нейминг, в прошлых тестах мы чот писали key value или типо того

2023-05-19 05:07 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +    const correctEntitiesValues = [{}, { headers: { key: 'value' } }, { cookies: { cookieName: 'cookieValue' } }, undefined];
это я дописал когда ещё не добавил отдельный тест для куки. здесь можно убрать

2023-05-19 05:07 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +    const correctEntitiesValues = [{}, { headers: { key: 'value' } }, { cookies: { cookieName: 'cookieValue' } }, { params: { paramKey: 'paramValue' } }, undefined];
это я дописал когда ещё не добавил отдельный тест для куки. здесь можно убрать

2023-05-21 09:15 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> -  test('Should correctly handle headers entity only with correct type', () => {
забыл вернуть

2023-05-21 14:51 UTC, debabin approved these changes

2023-05-21 19:22 UTC, merged