#63 into release@2.3.1 ☄ rework not cors middleware, add case for request with credentials
siberiacancode/mock-config-server pull request #64
Opened 2023-05-24 16:06 UTC by debabin

2023-05-24 16:35 UTC, RiceWithMeat commented on index.js
> +const { startMockServer } = require('./dist');
удаляем файл

2023-05-28 15:05 UTC, MiaInturi commented on src/core/middlewares/noCorsMiddleware/noCorsMiddleware.ts
> +    response.setHeader('Access-Control-Expose-Headers', exposedHeaders);
А зачем хэдеры делать специфичными? И вообще мне кажется не нужно делать по умолчанию credentials: true. В продакшене юзер это будет отдельно настраивать, так пусть и здесь настраивает

2023-05-28 15:05 UTC, MiaInturi commented on src/core/middlewares/noCorsMiddleware/noCorsMiddleware.test.ts
> +        'host, accept-encoding, access-control-request-method, access-control-request-headers, origin, connection',
Так тесты же становятся буквально зависимыми от библиотеки supertest. И я все еще не понимаю зачем ограничивать headers?

2023-05-28 15:10 UTC, MiaInturi commented on src/core/middlewares/noCorsMiddleware/noCorsMiddleware.ts
> +    response.setHeader('Access-Control-Expose-Headers', exposedHeaders);
Переформулирую, а то не понятно сказал, почему бы не брать headers из `access-control-request-headers`?

2024-06-30 10:40 UTC, MiaInturi requested changes

2024-06-30 10:40 UTC, MiaInturi commented on src/core/middlewares/noCorsMiddleware/noCorsMiddleware.ts
> +    const exposedHeaders = Object.keys(request.headers).join(', ');
1. exposed-headers это хэдеры ответа, так что брать их из запроса нет смысла. Думаю просто не имеет смысла сетить exposed-headers если пользователь явно их не задал через конфиг.
2. allowed-headers можно вычислять только внути условия `isPreflightRequest` и брать из заголовка `access-control-request-headers` (как собственно и allow-methods)

2024-06-30 10:40 UTC, MiaInturi commented on src/core/middlewares/noCorsMiddleware/noCorsMiddleware.ts
> +    const exposedHeaders = Object.keys(request.headers).join(', ');
Ну и оба эти пункта должны относиться и к corsMiddleware ИМХО

2024-11-19 19:39 UTC, MiaInturi commented
Надо бы решить, что делать с issue. Мб просто вырубить credentials в CORS по умолчанию? Имхо нормальный вариант, т.к. если пользователь захочет передавать куки и т.п., то пусть сделает это явно

2024-11-20 09:21 UTC, closed without merging