#59 into release@3.0.0 🐘 entity conditions support
siberiacancode/mock-config-server pull request #68
Opened 2023-06-03 12:57 UTC by RiceWithMeat

2023-06-11 06:23 UTC, debabin requested changes

2023-06-11 06:23 UTC, debabin commented on src/utils/types/rest.ts
> +export type RestHeaderOrCookieOrQueryOrParamEntityValue = string | number | boolean;
Думаю такие типы или надо придумать как называть или не делать export

2023-06-11 06:23 UTC, debabin commented on src/utils/types/rest.ts
> +  EntityName extends 'headers'
extends 'headers' | 'cookies' | 'query' | 'params' ... так не будет работать ?

2023-06-11 06:23 UTC, debabin commented on src/utils/types/rest.ts
> +};
Вариант конечно получился ниже круче, но менее читаемый, я за оставить как было

2023-06-11 06:23 UTC, debabin commented on src/utils/types/rest.ts
> +export type RestEntityNameByMethod<Methods extends RestMethod = RestMethod> = {
RestEntityNameByMethod зачем такой нейминг делать, когда можно было опять же оставить как было RestMethodsEntities

2023-06-11 06:23 UTC, debabin commented on src/utils/types/rest.ts
> +export type RestEntityByName = {
А разве тут не должно быть, что-то типо RestEntities просто ?

2023-06-11 06:23 UTC, debabin commented on src/utils/types/graphql.ts
>  import type { Request } from 'express';
Те же замечания для этого файла из rest типов

2023-06-11 06:23 UTC, debabin commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  const firstValueString = `${firstValue}`;
может сделаем в явном фомате, new String(firstValue) ?

2023-06-11 06:23 UTC, debabin commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  if (checkMode === 'isString') return true;
Про данные проверки писал выше, не считаю, что они нужны

2023-06-11 06:23 UTC, debabin commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  if (checkMode === 'notEquals') return secondValuesArray.every((value: any) => `${value}` !== firstValueString);
А может сделаем, что если человек пишет массив, что это может быть только примитивы или так и есть, можно ли в массив будет еще один массив бахнуть или обьект ?

2023-06-11 06:23 UTC, debabin commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  if (checkMode === 'notEquals') return secondValuesArray.every((value: any) => `${value}` !== firstValueString);
Или как сейчас это будет работать, например если пользователь захочет написать вот так 

```js
body: {
   entities: 'notStartsWith',
   value: [{ 'user.phone': '9' }, { 'user.phone': '8' }]
}
```

2023-06-11 06:23 UTC, debabin commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.test.ts
> +// TODO: add tests for all checkModes
Такие тесты я думаю лучше будет делить прям на блоки

2023-06-11 06:23 UTC, debabin commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
> +  if (body) routeConfigWeight += isPlainObject(body.value) ? Object.keys(body.value).length : 1;
Да опять же вопрос, почему боди такой у нас уникальный

2023-06-11 06:23 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +          return (descriptors).every(([entityKey, entityDescriptor]) => {
(descriptors) -> descriptors

2023-06-11 06:23 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            return isEntityValuesEqual(checkMode, request[entityName][entityKey], expectedValue);
Я возможно понял, проблема в боди, что он вложенный и поэтому тут будет проблема с entityKey ? Хотя в примерах, что я описывал ниже вроде бы такой проблем не должно быть

2023-06-11 06:23 UTC, debabin commented on src/core/middlewares/notFoundMiddleware/notFoundMiddleware.test.ts
> +              }
если поддержим формат, equals дефалт

2023-06-11 06:23 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/helpers/prepareGraphQLRequestConfigs/prepareGraphQLRequestConfigs.ts
> +  if (variables) routeConfigWeight += isPlainObject(variables.value) ? Object.keys(variables.value).length : 1;
Тоже самое замечание

2023-06-11 06:23 UTC, debabin commented on package.json
> +    "pretty": "yarn type && yarn format && yarn lint --fix && yarn type"
2 раза type, так и должно быть ?

2023-06-11 06:23 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +];
не хотим вынести в константы это, на это уровне

2023-06-11 06:23 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +const isHeadersOrCookiesOrQueryOrParamsDescriptorValid = (checkMode: unknown, value: unknown) => {
Очень много логики из-за того, что боди не в этой тусовке

2023-06-11 06:35 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +        }
тесты пока не писал, мб какие-то моды уберём и зря время не тратил

2023-06-11 06:38 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +  EntityName extends 'headers'
тру

2023-06-11 06:43 UTC, RiceWithMeat commented on package.json
> +    "pretty": "yarn type && yarn format && yarn lint --fix && yarn type"
это я добавил потому что на работе было пару раз что претир добавлял переносы и ts-ignore с eslint-disable-next-line переставали работать. сборка падала соответственно. для больших проектов офк билдить вторйо раз не надо, но здесь пару секунд лишних сделать тайпчек думаю норм идея

2023-06-11 06:45 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +];
ты про regExp и function? думал тоже вынести, но не придумал как их обозвать (по сути они входят в группу TWO_VALUES_CHECK_MODES, но для них нужна особенная логика ниже, вот отдельно и вписал)

2023-06-11 06:48 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +export type RestBodyEntity = RestEntityDescriptor<'body'>;
не, body буквально чем угодно может быть. если и делать чекмод для боди то для всего body сразу

2023-06-11 06:56 UTC, RiceWithMeat commented on README.md
> +`checkModes` from the second group, except `function` can be arrays, so you can write more complex logic. For example "does not contain these values" or "must be equal to one of these values". You ca
просто `mode` мне кажется не слишком информативно, будут вопросы "какой mode может быть например у header-а?", а с просто `type` будут неправильные ассоциации с типизацией. Слово checkMode я думаю норм потому что это буквально "способ/режим проверки". Раньше он назывался compareMethod, но с добавлением модов, для которых не нужно value (exists например), compare-ить стало не с чем, вот и поменял на более общий check

2023-06-11 07:12 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +export type RestHeaderOrCookieOrQueryOrParamsName = string;
этот тип используется ещё в createRoutes, тут и там хардкодить string не оч я думаю. в двух местах придётся менять тип в будущем

2023-06-11 07:12 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +  EntityName extends 'headers'
будет

2023-06-11 07:24 UTC, RiceWithMeat commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  if (checkMode === 'notEquals') return secondValuesArray.every((value: any) => `${value}` !== firstValueString);
в таком случае будет кейс isValuesAreArrays в функции isEntityValuesEqual. каждый элемент массива будет приведён к строке и сравнен notStartsWith с соответствующим actual элементом. Сам по себе кейс странный, ему нет применения, но упасть вроде как ничего не должно

2023-06-11 07:28 UTC, debabin commented on src/utils/types/rest.ts
> +export type RestBodyEntity = RestEntityDescriptor<'body'>;
А есть вариант, сделать всю типизацию для всего кроме боди и для боди прям отдельно ?

2023-06-11 07:28 UTC, debabin commented on src/utils/types/rest.ts
> +export type RestHeaderOrCookieOrQueryOrParamsName = string;
Мне не очень нравится нейминг и вся ситацию для боди, думаю может раз боди особенный то и типы вынести для него конкретно отдельно

2023-06-11 07:30 UTC, debabin commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  if (checkMode === 'notEquals') return secondValuesArray.every((value: any) => `${value}` !== firstValueString);
почему, я же написал довольно реалистичный кейс, мы не хотим обрабатывать номер телефонов с 8 и 9, вот у нас может быть такой кейс, и если я пришлю body { user: { phone: '99****' } }, то все ок будет ?

2023-06-11 07:31 UTC, debabin commented on package.json
> +    "pretty": "yarn type && yarn format && yarn lint --fix && yarn type"
Давай тогда назад просто перенесем в самый конец проверку типов, а с началу удалим

2023-06-11 07:32 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +];
нет я про все, что тут я выделил, сейчас это в файле с валидацией, мб вынесем в constants

2023-06-12 13:07 UTC, MiaInturi commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  if (checkMode === 'isString') return true;
Ну не знаю, лишними не будут, типо ну есть и есть. Кому надо, те воспользуются

2023-06-12 13:08 UTC, MiaInturi commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  if (checkMode === 'isNumber') return /^-?[1-9]\d*(\.\d+)?$/.test(firstValueString) && !Number.isNaN(Number.parseFloat(firstValueString));
А для каких кейсов нужно первое условие?

2023-06-12 13:14 UTC, MiaInturi commented on README.md
>  ##### Rest example
+, не надо делать акцент, что можно писать только так. А лучше вынести в отдельную секцию, мол если нужно больше функционала, то "библиотека умеет еще и вот так"

2023-06-12 13:15 UTC, MiaInturi commented on README.md
>  ##### Rest example
А то пользователь придет, посмотрит на первые примеры и увидит, что очень сложно

2023-06-12 15:23 UTC, MiaInturi commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
> +  if (body) routeConfigWeight += isPlainObject(body.value) ? Object.keys(body.value).length : 1;
ну боди же буквально что угодно

2023-06-12 15:23 UTC, MiaInturi commented on src/utils/constants/checkModes.ts
> +  'function'
А почему это не two values?

2023-06-12 15:23 UTC, MiaInturi commented on src/utils/types/values.ts
> +  | 'isString';
Не очень понял тебя. Типо убрать, чтобы код легче был? Мне кажется нет особо смысла, т.к. он и так довольно таки тяжелый и это особо разницы не сыграет

2023-06-13 18:24 UTC, RiceWithMeat commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  if (checkMode === 'isNumber') return /^-?[1-9]\d*(\.\d+)?$/.test(firstValueString) && !Number.isNaN(Number.parseFloat(firstValueString));
это для запрета странных написаний чисел, которые parseFloat может распарсить, например строка '00-2001' будет нулём, но это же явно не валидное число. все кейсы офк не учесть, но хотя бы так. ([1-9] кстати надо убрать, потому что так запрещены все числа от -1 до 0 и от 0 до 1)

2023-06-13 18:39 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +      return entries.every(([entityName, entities]) => {
тут да, слов буквально не хватает, надо продумать нейминг для каждой сущности. есть entities, это объект с ключами headers, query и тд. (entityName), значения это "одно" entity (). Но все entity кроме body и variables сами являются объектами, в которых ключи это entityKey, а значения entity? (entityKeyValue?, entityElementValue?). надо придумать название для конкретного одного из многих значений хедера, квери, и тд. проще схему на самом деле нарисовать и обсудить

2023-06-17 09:08 UTC, RiceWithMeat commented on src/utils/helpers/config/isEntitiesEqual/isEntityValuesEqual.ts
> +  if (checkMode === 'isNumber') return /^-?[1-9]\d*(\.\d+)?$/.test(firstValueString) && !Number.isNaN(Number.parseFloat(firstValueString));
не придумал когда эти проверки действительно пригодятся. выпилил

2023-06-17 09:11 UTC, RiceWithMeat commented on README.md
> +`checkFunction` has the following signature `(checkMode, firstValue, secondValue?) => boolean`.
думаю можно actualValue и descriptorValue использовать. descriptorValue буквально "значение которое лежит в "описаторе"" (ай лав рашн)

2023-06-25 14:32 UTC, debabin commented on src/utils/types/values.ts
> +export type CheckFunction = <ActualValue extends any = any, DescriptorValue extends any = any>
CheckModeFunction возможно ?

2023-06-25 15:06 UTC, debabin requested changes

2023-06-25 15:06 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +  [`${checkMode}4`]: { checkMode, value: [true, 123, 'string'] }
может вместо 1-4, добавить нейминг ${checkMode}-boolean, ${checkMode}-string, ${checkMode}-number, ${checkMode}-array

2023-06-25 15:06 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +      equals03: 'string',
для данных типов тоже можно сделать функциюю и генерировать выше

2023-06-25 15:06 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +                  value: '123'
123 -> value

2023-06-25 15:06 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +                  key1: incorrectObjectEntityDescriptor
везде есть только key1, можно переименовать в key

2023-06-27 14:38 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +    : RestObjectEntityValue;
да, RestPlainEntityValue разрешает быть строкой, любым массивом и любым объектом (если только в нём нет ключей checkMode или call)

2023-06-27 14:48 UTC, RiceWithMeat commented on src/utils/helpers/isPrimitive/isPrimitive.ts
> +export const isPrimitive = (value: any): value is boolean | number | bigint | string | null | undefined | symbol =>
это более правильная запись. если можно сказать тайпскрипту более точный тип то почему бы нет. Такая же тема в isPlainObject есть и там это роляет в validateGraphQLConfig, если isPlainObject(graphqlConfig) === false, то мы не сможем обращаться к полям graphqlConfig, т.к. тс понимает, что это не объект

2023-06-27 15:13 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +  if (checkMode === 'function') return descriptorValue(actualValue, checkFunction);
в checkFunction есть кейс с checkMode === 'function' чтобы мы могли использовать function checkMode в функции из второго аргумента checkFunction. вот так например можно любую вложенность из функций делать: 
`
authToken: {
                  checkMode: 'function',
                  value: (actualValue, checkFunction) => {

                    const condition1 = checkFunction('function', actualValue, (actualValue) => actualValue === true);
                    const condition2 = checkFunction('function', actualValue, (actualValue) => actualValue === false);

                    return condition1 && condition2;
                  }
                },
`

2023-06-27 15:20 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.test.ts
> +                  headers: {
на всякий случай второй вариант записи тестовых данных. думаю не повредит

2023-06-27 15:50 UTC, RiceWithMeat commented on src/utils/types/values.ts
> +// todo: string or object
это туду я не туда записал, оно к RestPlainEntityValue относилось

2023-06-27 15:52 UTC, RiceWithMeat commented on src/utils/types/values.ts
> +export type CheckFunction = <ActualValue extends any = any, DescriptorValue extends any = any>
а мб ResolveByCheckMode даже? и функцию соответственно также

2023-06-27 16:20 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +  }
здесь собственно я и скипаю по сути кейс primitive-object. то есть ни один примитив не является частью, началом, концом и тд объекта. надо точно оставить кейс object-array, чтобы можно было перечислять возможные вариации объекта (ты сам приводил кейс объектами, в которых телефоны есть). тогда получается удаляем кейсы array-primitive, array-object? (тогда теряем логику "содержит ли фактический массив такой элемент/объект?")

2023-06-27 16:26 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.test.ts
> +      equals03: 'string',
для exists и notExists нет других кейсов, для них value нельзя использовать. а equals особенный тем, что помимо дескриптора (который генерится в функции выше), можно не писать дескриптор, тк это чекмод не умолчанию. убрал цифры-приписки у ключей ещё

2023-06-27 17:10 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
> +    routeConfigWeight += isPlainObject(descriptorValue) ? Object.keys(descriptorValue).length : 1;
чот такое себе выходит, if в if-е, так ещё и с else. или ты другое имел ввиду?
![image](https://github.com/siberiacancode/mock-config-server/assets/47690223/6be0ed5e-adf5-4ad2-966a-4502176bb38b)

2023-06-27 17:11 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.ts
> +    routeConfigWeight += isPlainObject(descriptorValue) ? Object.keys(descriptorValue).length : 1;
хотя можно return-ом выйти из первого if-а и убрать else

2023-06-27 17:27 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/helpers/prepareGraphQLRequestConfigs/prepareGraphQLRequestConfigs.ts
> +    routeConfigWeight += isPlainObject(descriptorValue) ? Object.keys(descriptorValue).length : 1;
выше отписал

2023-06-28 16:04 UTC, MiaInturi requested changes

2023-06-28 16:12 UTC, RiceWithMeat commented on src/utils/constants/checkModes.ts
> +export const CALCULATE_BY_EXPECTED_VALUE_CHECK_MODES: CalculateByExpectedValueCheckMode[] = [
тут вместо expected надо descriptor писать. забыл поменять

2023-06-28 16:13 UTC, RiceWithMeat commented on src/utils/types/values.ts
> +export type Data = boolean | number | string | any[] | Record<any, any>;
чтобы работали data functions, если написать Data = any; то не будет подсказок что можно функцию написать в поле data

2023-06-29 12:05 UTC, MiaInturi requested changes

2023-06-30 14:20 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/helpers/prepareGraphQLRequestConfigs/prepareGraphQLRequestConfigs.test.ts
> -  test('Should set not object variables weight equals to one', () => {
потому что variables теперь может быть только объектом

2023-06-30 15:02 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +  | { checkMode?: undefined; call?: undefined; [key: string]: any; }
На самом деле string тоже надо удалить потому что сейчас нас сервер поддерживает только json в body. Когда в будущем добавим bodyParser.text можно будет вернуть boolean | number | string

2023-06-30 15:15 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +export type RestEntityByEntityName<Method extends RestMethod> = {
потому что ключи у объекта это EntityName

2023-06-30 15:43 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +              entities: { [correctEntity]: generateAllCorrectCompareWithExpectedValueObjectEntities() },
соглы

2023-06-30 15:48 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +      exists: { checkMode: 'exists' },
так не не получится делать потому что тип value неотрывно связан с конкретным checkMode-ом, что я в этом тесте и проверяю. например для `exists` values не должно быть, для `function` value должен быть функцией и тд.  не зная чекмода, мы не сможем решить какие типы value правильные, а какие нет. Поэтому дескрипторы в одном этом тесте и проверяются во всех комбинациях. Насчёт describe соглы

2023-06-30 15:56 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +  }
здесь мы проверяем тип для чекмодов, у которых есть value, с которым нужно сравнить actual ("equals" | "notEquals" | "includes" | "notIncludes" | "startsWith" | "notStartsWith" | "endsWith" | "notEndsWith"). (для variables и body кстати нужно убрать разрешение быть boolean | number | string)

2023-06-30 18:07 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            const { checkMode, value: descriptorValue } = (entityDescriptorOrValue && typeof entityDescriptorOrValue === 'object' && 'checkMode' in entityDescriptorOrValue ? entityDescriptorOrValue :
ты выше предлагал вынести это в переменную. можно вынести `descriptor && typeof descriptor === 'object' && 'checkMode' in descriptor` в хелпер `isEntityDescriptor`, а логику `isEntityDescriptor ? descriptor : { checkMode: 'equals', value: descriptor }` в хелпер `getEntityDescriptor`. хелпер isEntityDescriptor отдельный потому что этот флаг нужен ниже для подстановки `.value` если это дескриптор. что думаешь?

2023-07-01 06:18 UTC, MiaInturi commented on src/utils/constants/checkModes.ts
> +  !COMPARE_WITH_DESCRIPTOR_STRING_VALUE_CHECK_MODES.includes(checkMode as CompareWithDescriptorStringValueCheckMode) && checkMode !== 'regExp' );
Ниже отписал про Object/Plain нейминг

2023-07-01 06:18 UTC, MiaInturi commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            const { checkMode, value: descriptorValue } = (entityDescriptorOrValue && typeof entityDescriptorOrValue === 'object' && 'checkMode' in entityDescriptorOrValue ? entityDescriptorOrValue :
Думаю нормальная идея с созданием двух хэлперов, а по поводу нейминга `resolveEntityDescriptor` - мб `convertToEntityDesctriptor`?

2023-07-01 06:18 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
> +      exists: { checkMode: 'exists' },
Понял 👍

2023-07-02 07:33 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
>    }
у нас оказывается format скрипт не проходился по всем файлам из-за того что путь до файлов не был в кавычки обёрнут, поправил

2023-07-02 07:45 UTC, RiceWithMeat commented on src/utils/types/values.ts
> +
тоже думал над KeyValue когда придумывал нейминг, но отказался потому что тогда будут названия KeyValueKey и KeyValueValue. Мб MapEntity назвать? Тоже соотношение каких-то значений к ключам. А PlainEntity думаю не плохо, потому что буквально "просто значение, любое" (по аналогии с нашими типами PlainObject и PlainFunction). Что думаешь?

2023-07-02 08:32 UTC, RiceWithMeat commented on src/utils/constants/checkModes.ts
> +  !COMPARE_WITH_DESCRIPTOR_STRING_VALUE_CHECK_MODES.includes(checkMode as CompareWithDescriptorStringValueCheckMode) && checkMode !== 'regExp' );
Выше отписал)

2023-07-02 09:32 UTC, MiaInturi commented on src/utils/types/values.ts
> +
В целом согласен со всем, что ты написал, только думаю больше подходит не Map, а Mapped, чтобы подчеркнуть, что это не именно мапа, а структура, похожая на мапу

2023-07-02 09:33 UTC, MiaInturi approved these changes

2023-07-02 11:35 UTC, MiaInturi approved these changes

2023-07-05 13:59 UTC, debabin requested changes

2023-07-05 13:59 UTC, debabin commented on src/utils/helpers/entities/isEntityDescriptor/isEntityDescriptor.test.ts
> +    expect(isEntityDescriptor({ checkMode: 'equals', value: 'string' })).toEqual(true);
expect(isEntityDescriptor(1)).toEqual(false);
    expect(isEntityDescriptor('string')).toEqual(false);
    expect(isEntityDescriptor([])).toEqual(false);
    expect(isEntityDescriptor({ key: 'value' })).toEqual(false);
    expect(isEntityDescriptor({ checkMode: 'exists' })).toEqual(true);
    expect(isEntityDescriptor({ checkMode: 'equals', value: 'string' })).toEqual(true);
    
    я думаю можно вот так оставить

2023-07-05 13:59 UTC, debabin commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +      );
а вообще есть смысл позволять regexp в таких кейсах или мы предполагаем, что человек будет rexexp для объекта писать ?

2023-07-05 13:59 UTC, debabin commented on src/utils/helpers/entities/convertToEntityDescriptor/convertToEntityDescriptor.test.ts
> +    expect(convertToEntityDescriptor(123)).toEqual({ checkMode: 'equals', value: 123 });
123 -> 1

2023-07-05 13:59 UTC, debabin commented on src/utils/helpers/entities/convertToEntityDescriptor/convertToEntityDescriptor.test.ts
> +    expect(convertToEntityDescriptor([false, 123, 'string'])).toEqual({
[false, 123, 'string'] -> []

2023-07-05 13:59 UTC, debabin commented on src/utils/constants/checkModes.ts
> +);
а разве мы не можем тут сделать [
  ...CHECK_ACTUAL_VALUE_CHECK_MODES,
 function
]

2023-07-05 13:59 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +              Object.keys(request[entityName]).length ? request[entityName] : undefined,
body parser делает {}, вопрос, а разве у нас что-то поломается если будет {} а не undefined ? а может тут мы будем писать прям request.body, чтобы было легче глазам и вообще в таких кейсах так делать, что если мы задаем конкретику писать сразу с конкретикой

2023-07-05 13:59 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +              Object.keys(request[entityName]).length ? request[entityName] : undefined,
не до конца понял, а мы поддерживаем кейс body: {phone: {checkMode: exist}} например, просто ниже я вижу, что мы проходимся по всем ключам, а тут такого нет

2023-07-05 13:59 UTC, debabin commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
>          }
same вопросы как и к боди

2023-07-05 13:59 UTC, debabin commented on package.json
> +    "format": "prettier --write \"{src,bin}/**/*.ts\"",
добавить еще и js файлы сюда бы надо

2023-07-05 13:59 UTC, debabin commented on package.json
> +    "format": "prettier --write \"{src,bin}/**/*.ts\"",
или у нас нет js файлов

2023-07-05 13:59 UTC, debabin commented on src/utils/types/values.ts
> -import type { ParsedQs } from 'qs';
а файл не стоит назвать entitites или checkModes, ну я к тому, что это именно entities история

2023-07-05 13:59 UTC, debabin commented on src/utils/types/values.ts
> +export type Data = boolean | number | string | any[] | Record<any, any>;
а разве дату пользователь не сможет написать null или undefined ?

2023-07-12 08:17 UTC, RiceWithMeat commented on package.json
> +    "format": "prettier --write \"{src,bin}/**/*.ts\"",
нет смылсла добавлять, тк нет js файлов

2023-07-12 08:22 UTC, RiceWithMeat commented on src/utils/types/values.ts
> +export type Data = boolean | number | string | any[] | Record<any, any>;
помню что-то сломалось у меня из-за этого, удалил, а вернуть забыл после фикса. вернул

2023-07-12 08:34 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +  }
сейчас так написано чтобы был такой же порядок как у checkFunction, у неё сначала идёт actual значение, а потом descriptor значение. я считаю так логичнее. допишу в комментах просто что есть actual, а что есть descriptor

2023-07-12 08:49 UTC, RiceWithMeat commented on src/utils/constants/checkModes.ts
> +);
соглы, здесь по сути скопирована логика вычленения нужных чекмодов из общего списка у самого типа PlainEntityCheckMode. Проще конечно просто их перечислить, да

2023-07-12 08:53 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +              Object.keys(request[entityName]).length ? request[entityName] : undefined,
сломается, потому что у object-like entities (хедеры например), если какого-то хедера нет, то он undefined, а вот если body нет, то он будет {}. Логика у exists и notExists чекмодов завязана как раз на undefined

2023-07-12 09:28 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +      );
соглы, я же запретил писать regExp для body и variables, а только у них по сути может быть объект в actual

2023-07-12 10:40 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +  if (isActualValueArray && isDescriptorValuePrimitive) return isNegativeCheckMode;
не получится потому что для некоторых кейсов где мы скипаем проверку нам нужна ещё логика для regExp (как в случае actual: array, descriptor: object например, когда мы проверяем массив на соответствие регулярке). Да и выносить это не очень красиво, потому что сейчас всё структурировано, все 9 комбинаций actualValue и descriptorValue подряд идут

2023-07-12 10:43 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +  if (isActualValueArray && isDescriptorValuePrimitive) return isNegativeCheckMode;
добавил коммент, что такие кейсы не имеют смысла, поэтому скип

2023-07-12 12:44 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +              Object.keys(request[entityName]).length ? request[entityName] : undefined,
не поддерживаем, мы проверяем body полностью на соответствие одному чекмоду, а не каждое поле отдельно. я так понимаю ты предлагаешь поддержать вложенные чекмоды для body и variables как здесь 
![image](https://github.com/siberiacancode/mock-config-server/assets/47690223/b41e8631-40b2-4a84-8583-6d813633a7b2)

2023-07-12 12:44 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
>          }
выше отписал

2023-07-18 13:38 UTC, MiaInturi commented on src/utils/types/rest.ts
> +  ? Check extends RestMappedBodyCheckModes
В этой проверке нет смысла же, можно сразу проверять `extends function... и т.д.`

2023-07-18 13:38 UTC, MiaInturi commented on src/utils/types/rest.ts
> +  | (RestPlainEntityInnerValue | Primitive | RestEntityDescriptor)[];
А в каких случаях `RestEntityDescriptor` нужен внутри массива?

2023-07-18 13:38 UTC, MiaInturi commented on src/utils/types/rest.ts
> +>;
бесполезный тип

2023-07-18 13:38 UTC, MiaInturi commented on src/utils/types/rest.ts
> +  : never;
То, как сама IDE расставляет пробелы мне нравится больше, нежели такая запись, но тут уже как тебе хочется делай

2023-07-18 13:38 UTC, MiaInturi commented on src/utils/types/rest.ts
> +      >;
Я так и не понял, а разве body не стал как все остальные entities? Типо объектом простым?

2023-07-19 13:48 UTC, MiaInturi commented on README.md
> +All `checkModes` except `function` can be arrays, so you can write even more complex logic. For example "does not contain these values" or "must be match to one of these regExp".
еще массивами не могут быть `exists`, 'notExists' - разве нет?

2023-07-19 13:50 UTC, MiaInturi commented on README.md
> +##### Using descriptors for part of body or variables
for part of **REST** body or **GRAPHQL** variables?

2023-07-19 14:10 UTC, MiaInturi commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +      const { checkMode, value } = convertToEntityDescriptor(valueOrDescriptor);
Это не исправление, а больше совет. Тут переменная `isDescriptor` инициализирована довольно далеко от места ее использования и я заметил в твоем коде, что это часто встречается.
Как я понимаю ты хотел вместе держать вызовы функций `isEntityDescriptor` и `convertToEntityDescriptor`, но мне кажется, что писать переменные ближе к месту их использования все же правильнее, т.к. чтение кода (по опыту данного ревью) становится полегче

2023-07-19 14:10 UTC, MiaInturi commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +    return PLAIN_ENTITY_CHECK_MODES.includes(checkMode as PlainEntityCheckMode);
Кстати, я как раз из-за таких кейсов перестал писать `if` в одну строку)

2023-07-19 14:10 UTC, MiaInturi commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +          );
А кейс, когда variables является массивом, обработан?

2023-07-19 14:36 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +          );
variables не может быть массивом, поэтому нет. хорошо что спросил, потому что забыл в типизации массив запретил, а в валидации запретить забыл, поправлю

2023-07-19 14:38 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +      >;
нет, если бы он полностью стал как остальные MappedEntity, то тогда мы бы потеряли возможность писать просто любой объект и в будущем сделать body строкой. Отдельный тайп энивей нужен

2023-07-24 12:56 UTC, debabin requested changes

2023-07-24 12:56 UTC, debabin commented on src/utils/helpers/entities/isEntityDescriptor/isEntityDescriptor.ts
> +export const isEntityDescriptor = (value: any) => isPlainObject(value) && 'checkMode' in value;
Кстати хороший тейк, думаю проверка, что checkMode равен значению была бы не лишней, с другой стороны мы можем такое валидировать во время старта приложения, а тут не перегружать

2023-07-24 12:56 UTC, debabin commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +  const isActualValueUndefined = typeof actualValue === 'undefined';
добавь тут пробелов, между кейсами

2023-07-24 12:56 UTC, debabin commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +      );
не до конца понял данный кейс, у нас же array, array. Зачем flatten для массива делать, разве мы не должны пройтись тут по всем элементам массива + еще сверху сразу проверить а длина вообще совпадает, токгда и regexp можно не проверять

2023-07-24 12:56 UTC, debabin commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +      );
или тут получается flatten формата 0.key1.key2 и так далее ?

2023-07-24 12:56 UTC, debabin commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.test.ts
> +    expect(() => resolveEntityValues('wrongCheckMode' as CheckMode, '123', '123')).toThrow(
'123', '123' -> может просто 1 и 1 или тип того

2023-07-24 12:56 UTC, debabin commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.test.ts
> +        expect(resolveEntityValues('equals', 'string2', 'string')).toBe(false);
а это хорошо, что мы не учитываем типы ? просто, а что если человеку нужно будет такое поведение ?

2023-07-24 12:56 UTC, debabin commented on src/core/rest/createRestRoutes/helpers/prepareRestRequestConfigs/prepareRestRequestConfigs.test.ts
> +                }
вот тут вопрос, а почему бы не оставить просто кейс с header1: 'value', все же будет работать

2023-07-24 12:56 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            );
не понял данного кода, body = { phone: "8193" }, почему проверка идет не для всего боди, а для его ключей ? 

body = { user.phone: "8193" }, что если у меня будет вот так

2023-07-24 12:56 UTC, debabin commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +              Object.keys(request[entityName]).length ? request[entityName] : undefined,
request[entityName] -> request.body

2023-07-24 12:56 UTC, debabin commented on src/utils/types/rest.ts
> +  : Check extends 'function'
давай вынесем funtion и regexp тоже в типы, короче сделаем 2 типы обертки

2023-07-24 12:56 UTC, debabin commented on src/utils/types/rest.ts
> +        | RestEntityValue<EntityName>[]
а разве массив тут возможен ? тип это будет equals массивом ? Если да я бы вынес RestEntityValue<EntityName>
        | RestEntityValue<EntityName>[] это в отдельный тип

2023-07-24 14:38 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +  | (RestPlainEntityInnerValue | Primitive | RestEntityDescriptor)[];
это чтобы body мог быть массивом, тс почему то жаловался когда я писал массив в body, хотя массив это же частный случай объекта. Сейчас убрал `| (RestPlainEntityInnerValue | Primitive | RestEntityDescriptor)[];` и всё работает)

2023-07-24 14:48 UTC, RiceWithMeat commented on src/utils/helpers/entities/isEntityDescriptor/isEntityDescriptor.ts
> +export const isEntityDescriptor = (value: any) => isPlainObject(value) && 'checkMode' in value;
так и есть, при валидации конфига проводится проверка чекмодов

2023-07-24 14:49 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +  ? Check extends RestMappedBodyCheckModes
тру

2023-07-24 15:19 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +  | (RestPlainEntityInnerValue | Primitive | RestEntityDescriptor)[];
короче я понял, я для теста в своём конфиге использовал кучу разных версий body и проверенные я комментил, и среди 70 строк комментов тс-игнор притаился и поэтому на body мне не кидалась ошибка. `| (RestPlainEntityInnerValue | Primitive | RestEntityDescriptor)[];` нужен чтобы была возможность писать в body массив

2023-07-24 15:22 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +  : never;
мне тоже такие одноэтажные кондишены не нравятся, но притир энивей плоскими их делает

2023-07-24 16:11 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +    return PLAIN_ENTITY_CHECK_MODES.includes(checkMode as PlainEntityCheckMode);
полностью отказываться от однострочности думаю избыточно, а добавлять скобки если вдруг претир перенос добавил такое себе. Предлагаю смириться либо вообще везде писать {}, но тогда код страшным станет когда таких ретёрнов много

2023-07-24 16:19 UTC, RiceWithMeat commented on src/core/graphql/createGraphQLRoutes/createGraphQLRoutes.ts
> +          );
добавил проверку

2023-07-24 16:25 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.test.ts
> +        expect(resolveEntityValues('equals', 'string2', 'string')).toBe(false);
это точно. в другой таске надо обсуждать. мб сделаем эту фичу переключаемой в конфиге параметром по типу `strictEntityTyping`

2023-07-24 16:49 UTC, RiceWithMeat commented on src/core/rest/createRestRoutes/createRestRoutes.ts
> +            );
Не понял вопроса, мы же отказались от вложенных дескрипторов в пользу записи ключей через точку, в таком случае вложенность только одна у объекта будет, поэтому ключи и проверяю.

если body = { phone: "8193" }, то он считается plain, тк в нём нет точек в ключах и дескрипторов в значениях. Поэтому прокидываем body целиком в функцию resolveEntityValues.

Если body = { user.phone: "8193" }, то мы начинаем проверять в actual body именно это одно поле.
Если например будет body = { user.phone: { checkMode: "startsWith", value: '111' } }, то проверится на startsWith именно поле user.phone.
Всё работает

2023-07-24 16:58 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +      );
да, у нас же могут быть объекты в массивах и если не flat-ить их, то элементы массивов всегда будут разными, тк ссылки разные

2023-07-24 17:03 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +      );
логику для regExp можно вообще здесь убрать, потому что по сути от того, что мы заflatten-им массив и пройдёмся по его ключам вместо прохода при помощи every ничего не изменится

2023-07-24 17:17 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +        | RestEntityValue<EntityName>[]
да, если например для хедера указать [1, 2, 3], то мы разрешим ему быть от 1, 2 или 3 (тоже самое если бы написали { checkMode: equals, value [1,2,3] }). Вынес тип для реста и графкл

2023-07-24 17:30 UTC, RiceWithMeat commented on src/utils/types/rest.ts
> +export type RestPlainEntityValue =
1. не понял в чём смысл дженерика здесь будет, куда мы его дальше прокидывать будем?
2. поправил

2023-07-27 05:39 UTC, debabin requested changes

2023-07-27 05:39 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +const validateMappedEntity = (mappedEntity: unknown, entityName: string) => {
не хотим все хелперы вынести в helpers папку, а то мы везде выносим, а тут чот скип

2023-07-27 05:39 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +};
этот код дублируется ?

2023-07-27 05:39 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +};
я думаю точно стоит вынести

2023-07-30 17:48 UTC, debabin requested changes

2023-07-30 17:48 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +      const errorMessage = `body${isTopLevelDescriptor ? '.value' : ''}`;
в данном участке кода всегда будет isTopLevelDescriptor равен true, не зачем писать проверку

2023-07-30 17:48 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +      const errorMessage = `body${isTopLevelDescriptor ? '.value' : ''}`;
данные комментарии актуальны и для графкл

2023-07-30 17:48 UTC, debabin commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +  checkObjectKeysCount: boolean = false
Вообще не понял, зачем данный параметр, если надо просто ниже если кейс array array сделать проврку на длину массива

2023-07-30 18:02 UTC, RiceWithMeat commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +  checkObjectKeysCount: boolean = false
массивы и так проверяются на длину, этот параметр заставляет проверять количество ключей для объектов (кейс когда указан дескриптор для всего body/variables), что по сути делает strict проверку. В кейсе когда этот дескриптор не указан, проверка будет только перечисленных ключей и проверка на количество ключей не нужна

2023-07-30 18:09 UTC, RiceWithMeat commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.ts
> +) => {
эта функция проверяет конкретно value в зависимости от чекмода и entityName. Если я в ней вызову isCheckModeValid и чекмод вдруг будет не валидный, функция вернёт false и будет не понятно, это чекмод неправильный или value. Смешивать не надо

2023-07-30 18:25 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +      throw new Error('body.checkMode');
сначала так и хотел сделать но потом понял, что тогда мы себя свяжем тем, что entities для реста и графкл должны быть одинаковыми. Как только мы захотим изменить только например rest entity (например поддержка строки для body, если мы это поддержим, то тогда и variables будет разрешён быть строкой, что неправильно). Нурсултан не зря разделил валидацию роутов на рестовый и графкловский. Раз createRoutes у нас два для реста и графкл, значит и валидация должна быть для каждого своя же. @debabin @MiaInturi что думаете?

2023-07-30 18:57 UTC, debabin commented on src/utils/helpers/config/resolveEntityValues/resolveEntityValues.ts
> +  checkObjectKeysCount: boolean = false
просто я не понимаю зачем данный ключ нужен, ты просто до flat должен проверить длинну массивов, а после еще и можно проверить количесвто ключей в некоторых кейсах

2023-07-30 18:58 UTC, debabin commented on bin/validateMockServerConfig/validateRestConfig/validateRoutes/validateRoutes.ts
> +      throw new Error('body.checkMode');
Звучит адекватно, думаю все норм

2023-07-31 11:07 UTC, debabin requested changes

2023-07-31 11:07 UTC, debabin commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.ts
> +  const isEntitiesObject = isPlainObject(entities) && !(entities instanceof RegExp);
а мы можем добавить проверку на regexp в функцию, чтобы не дублировать везде данный кейс

2023-07-31 13:18 UTC, RiceWithMeat commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.test.ts
> +    test('Should correctly validate descriptor value for plain entity', () => {
У нас везде внутри forEach используется только expect, есть только один такой тест для corsMiddleware. Если переписывать, то всё сразу и в отдельной таске. Обсудим потом все вместе как делаем.

2023-07-31 13:21 UTC, RiceWithMeat commented on bin/validateMockServerConfig/validateGraphqlConfig/validateRoutes/validateRoutes.test.ts
>  describe('validateRoutes (graphql)', () => {
все верхнеуровневые describe-ы соответствуют названиям файла, у нас нет ни одного такого дескрайба с большой буквы

2023-08-01 04:06 UTC, debabin commented on bin/validateMockServerConfig/helpers/isDescriptorValueValid/isDescriptorValueValid.test.ts
> +    test('Should correctly validate descriptor value for plain entity', () => {
Я думаю лучше сделать таску тогда

2023-08-01 04:06 UTC, debabin approved these changes

2023-08-01 04:35 UTC, merged