#53 into release@3.0.0 👹 database config
siberiacancode/mock-config-server pull request #69
Opened 2023-06-04 15:05 UTC by MiaInturi

2023-06-04 15:06 UTC, MiaInturi commented on package.json
> +    "uuid": "^9.0.0",
Надо не забыть удалить, т.к. добавлял для проверки функциональности одной

2023-06-05 14:43 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
> +  createNestedDatabase(router, nestedDatabase, new MemoryStorage(nestedDatabase));
мб добавим приписку `Routes` в конце названий этих функций? просто получается тогда `createDatabaseRoutes` не вызывает внутри себя ничего связанного с путями, но фактически `createShallowDatabase` и `createNestedDatabase` создают именно новые роуты в роутере

2023-06-05 14:43 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabase/createNestedDatabase.ts
> +      response.status(201).json(newResource);
не хватает `response.set('Location', request.url);` как в createShallowDatabase?

2023-06-05 14:43 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabase/createNestedDatabase.ts
> +      currentResourceArray.splice(currentResourceIndex, 1);
мб логику с удалением в сам класс MemoryStorage вынести? так будет правильнее я думаю, просто тут идёт мутация данных класса в обход нужных для этого методов (write), ооп  солид паттерны ууух). по итогу здесь будет просто метод .delete(id), который удалит внутри этот элемент

2023-06-05 14:43 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabase/createShallowDatabase.ts
> +    router.route(`/${key}`).get((_request, response) => {
можно константу `path` объявить для `/${key}`

2023-06-05 14:43 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabase/createShallowDatabase.test.ts
> +      const newJohnInfo = { age: 26, standName: 'The World' };
вот так дио и находил стендоюзеров по таким базам, араки и это продумал 🤙

2023-06-05 14:47 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +  it('Should return correct data for read with valid single key', () => {
Да, случайно написал

2023-06-05 14:47 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabase/createShallowDatabase.test.ts
> +    test('Should return correct data for valid key', async () => {
Да, везде должно быть test - с `it` это опечатка

2023-06-05 14:58 UTC, MiaInturi commented on src/utils/types/database.ts
> +export type NestedDatabase = Record<string, Record<string, unknown>[]>;
Мне кажется так будет не очень правильно с точки зрения семантики. Все таки NestedDatabase это отдельная сущность, а не объект из массивов ShallowDatabase

2023-06-11 07:26 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabase/createNestedDatabase.ts
> +      const newResource = { ...request.body, id: resourceLastIndex };
Если сделать map, то было бы круто

2023-06-11 07:26 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabase/createNestedDatabase.ts
> +        .findIndex((resource) => resource.id === request.params.id);
Опять же если мы сделаем все через Map, а не массив будет мега, но тогда будет проблема с записью, если пользователь будет кидать путь до файла

2023-06-11 07:26 UTC, debabin commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
> +  createNestedDatabase(router, nestedDatabase, new MemoryStorage(nestedDatabase));
Shallow и Nested это по факту Object и Array куски базы, точно ли подходит первый нейминг

2023-06-11 07:37 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +import { isPlainObject } from '@/utils/helpers';
Всм?

2023-06-11 07:39 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabase/createNestedDatabase.ts
> +  nestedDatabase: NestedDatabase,
а в чем разница?

2023-06-11 07:47 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +import { isPlainObject } from '@/utils/helpers';
с маленькой буквы memory

2023-06-11 12:05 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +import { isPlainObject } from '@/utils/helpers';
Ну и делал большую букву исходя из того, что MemoryStorage это класс

2023-06-13 15:18 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
> +  createNestedDatabase(router, nestedDatabase, new MemoryStorage(nestedDatabase));
Object и Array мне кажется не отражают основной смысл разделения - как вариант могу предложить singular и plural - мне кажется как раз идеально описаывает смысл разделения. Одна часть для сущностей в единственном числе, другая часть для сущностей в множественном числе

2023-06-13 15:19 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabase/createNestedDatabase.ts
> +      const newResource = { ...request.body, id: resourceLastIndex };
Решили, что делать через Map не будем - слишком сложная сериализация

2023-06-13 18:02 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabase/createNestedDatabase.ts
> +  nestedDatabase: NestedDatabase,
Увидел)

2023-08-05 11:58 UTC, debabin requested changes

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +    let writable: any = this.data;
не понял зачем тут делаем переменную с ссылкой на this.data, почему бы не использовать сразу this.data + вопрос такие же как и к read

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +  }
аналогичные вопросы из пунктов выше

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +  describe('MemoryStorage: read', () => {
мы ранее так не делали, думаю стоит пока придерживаться старой политики написание тестов и просто убрать верних describe и оставить нижние, на это уже таски

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +      expect(memoryStorage.read()).toStrictEqual(initialData);
данный тест не совсем корректные, потому что ты используешь в MemoryStorage теже самые данные, по хорошему надо здесь использовать данные описанные вручную не связанные с функцией createInitialData

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +    test('Should return correct FULL data for read without keys', () => {
я бы не стал выделить full, это слово не такое как REST или GET method

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +      expect(memoryStorage.read()).toStrictEqual(initialData);
Возможно не прав, уточнить у @kvelian

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +      expect(memoryStorage.read('john')).toStrictEqual({ name: initialData.john.name });
логичнее в тесте проверить, что нет именно age после удаления, что он был а после не стало, в тест выше думаю также стоит проверить, что сначало john был, а потом не стало

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +    delete deletable[key[index]];
не до конца понял, когда вообзе этот кейс сработает, например 

```ts
const users = [[ { name: '123' } ]]
delete([users, 0])
```

я дойду из условий выше до [ { name: '123' } ] и потом пойдет данное условие и мы удалим { name: '123' }
и я чот не понимаю смысл данной логики, возможно я не понял просто

2023-08-05 11:58 UTC, debabin commented on src/utils/helpers/array/isIndex/isIndex.ts
> +export const isIndex = (value: any): value is number => Number.isInteger(value) && value >= 0;
Не уверен, что стоит выносить данную функцию и покрывать ее тестами, мне кажется, ничего плохо не будет если ты укажешь это в классах 2 раза, слишком простая функция

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/File/FileStorage.ts
> +    const filePath = path.resolve(process.cwd(), fileName);
вроде бы уже есть где-то app path в константах, которые делает тоже самое export const APP_PATH = process.cwd();

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/File/FileStorage.ts
> +  }
Вопрос, можем ли мы создать абстрфктный класс и там описать методы read, write, delete, они довольно очень похожи или это не возможно и не стоит так делать ?

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/File/FileStorage.ts
> +    this.data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
а мы не хотим сделать метод в FileWriter, который вернет дату и после вызывать его тут, например this.data = this.fileWriter.read(), чтобы в это была ответсвенность данного класса

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/File/FileWriter.ts
> +  }
из кода выше, уже был крокинут file path, но тут fileName, опять же предлагаю данную логику оставить здесь и не нагружать тот класс, ведь мне видится, что вообще для memory storage и file storege можно сделать 1 общий класс

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createRewrittenDatabaseRoutes/createRewrittenDatabaseRoutes.ts
> +};
=> router.use(rewrite(key, value)); можно убрать { }

2023-08-05 11:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
> +  const storage = typeof data === 'string' ? new FileStorage(data) : new MemoryStorage(data);
думаю было бы круто для ясности еще добавить, как и в валидации data.endsWith('.json');

2023-08-05 11:58 UTC, debabin commented on bin/validateMockServerConfig/validateDatabaseConfig/validateDatabaseConfig.test.ts
> +    });
это. мелочь, но я бы заменил на file.json, а не string.json

2023-08-06 09:21 UTC, debabin requested changes

2023-08-06 09:21 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +      }
мне кажется мы тут попали в ловушку реализации response.json(storage.read([key, currentResourceIndex])), мне кажется можно после строчки const currentResourceCollection = storage.read(key);, сделать просто find, тогде не нужна ни функция findIndexByI, так же код  response.json(storage.read([key, currentResourceIndex])); не нужно будет выполнять. Тоесть вместо вызоыва еще раз storage read и поиска индекса, можно сразу искать элемент и вернуть его

2023-08-06 09:21 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +      const newResourceId = createNewId(collection);
А как id формируется в json server, не должен ли сам юзер его кидать ?

2023-08-06 09:21 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +      }
Касается всего кода ниже

2023-08-06 17:42 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +    // stop iterate for one element before end of key for get access to writable object property
этот импортант кажется выше должен быть

2023-08-06 17:42 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +      deletable.splice(key[index] as number, 1);
если надо удалить только первый элемент массива, можно заменить splice на shift

2023-08-06 17:42 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +    });
для read тестов нет beforeEach логики, понятно, что чтение никак не мутирует initial объект, но можно вынести эти строки в общий дескрайб и минус копипаст будет

2023-08-06 17:42 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +      const newAgeJohn = { ...initialData.john, age: 26 };
вкусовщина: `johnWithNewAge` понятнее звучит

2023-08-06 17:42 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +      expect(memoryStorage.read('john')).toStrictEqual({ name: initialData.john.name });
1) strictEqual и так проверит отсутствие age + проверит, что остальные поля не пострадали, что лучше
2) с проверкой наличия age до удаления соглы, потому что если сделать delete несуществующего поля, ошибки не будет и если мы уберём из initial все age-ы, тест не упадёт, а должен

2023-08-06 17:42 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/storages/File/FileWriter.ts
> +import * as fs from 'fs';
можно убрать * as

2023-08-08 07:32 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +      const newResourceId = createNewId(collection);
В json-server id формирует сам сервер, что логично. Мы же на реальном API не кидаем id в POST, т.к. не знаем, сколько сущностей записано в бд

2023-08-08 07:32 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +      }
А почему бы и не сделать? Логика не сложная, а если пользователь закинет не object в бд, то потом при каком-нибудь spread сервер вообще упадет.

2023-08-08 07:32 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/File/FileWriter.test.ts
> +    }
не понял, можно пример кода?

2023-08-08 07:32 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +      deletable.splice(key[index] as number, 1);
Не только первый. Любой, который будет записан в key[index]

2023-08-08 07:32 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +    delete deletable[key[index]];
Потому что если вызвать оператор delete для массива, то внутренняя инфа о массиве (length) не будет обновлена

2023-08-08 07:32 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/File/FileStorage.ts
> +    this.data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
А зачем классу FileWriter отвечать еще и за чтение из файла. Для этого как раз и существует класс FileStorage. Единственная ответственность класса FileWriter - это асинхронно записывать актуальные данные в файл

2023-08-08 07:32 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createNestedDatabaseRoutes/createNestedDatabaseRoutes.ts
> +      }
А как быть, если нужно изменить элемент? Типо доставать collection и потом мутировать? Мне такой подход вообще не нравится, т.к. это прям очень неочевидное поведение

2023-08-08 07:58 UTC, RiceWithMeat commented on src/core/database/createDatabaseRoutes/storages/File/FileWriter.test.ts
> +    }
это я поплыл ночью, забей. writeOperationCount же число и так нельзя написать. (если конечно Array(writeOperationCount).fill() не делать, но это кринж)
```
const writePromises = writeOperationCount.map((_, index) => fileWriter.write(JSON.stringify({ index })))
```

2023-08-08 08:18 UTC, MiaInturi commented on src/utils/helpers/array/createNewId/createNewId.ts
> +};
1. Мне не нравится идея, что reduce используется не по назначению (взять некоторую инфу из каждого элемента массива), а вместо цикла. Ничего плохого в обычном `for цикле` не вижу, если он достаточно описывает происходящее
2. `+ 1` в конце нельзя убрать, т.к. нужно прибавлять 1, если нашли какой-то элемент с численным id в массиве

2023-08-08 08:51 UTC, debabin commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.ts
> +    let writable: any = this.data;
Так же ссылка всегда будет одна и та же ? или я не прав, я к тому что let writable: any = this.data это тоже самое, что просто this.data работать

2023-08-08 10:36 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +      }
Global hanlder (?)

2023-08-08 16:41 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/File/FileStorage.ts
> +  }
Реализации методов read, write и delete чуть-чуть все таки различаются, так что абстрактный класс не сделать, но можно сделать интерфейс `Storage` для `FileStorage` и `MemoryStorage`

2023-08-09 06:08 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +    });
Я все таки за тот вариант, когда каждый дескрайб сам описывает ровно ту логику, которая ему нужна. + в будущем мы будем убираться самый высокий describe-обертку.

2023-08-09 06:14 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +      expect(memoryStorage.read('john')).toStrictEqual({ name: initialData.john.name });
В целом со всем согласен, кроме того, что надо проверять именно age. Мне кажется, что strictEqual лучше бля этого подходит, т.к. он чувствителен даже к undefined.
`keys with undefined properties are checked, e.g. {a: undefined, b: 2} will not equal {b: 2};`

2023-08-09 06:15 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/storages/Memory/MemoryStorage.test.ts
> +      expect(memoryStorage.read('john')).toStrictEqual({ name: initialData.john.name });
В целом со всем согласен, кроме того, что надо проверять именно age. Мне кажется, что strictEqual лучше для этого подходит, т.к. он чувствителен даже к undefined.
`keys with undefined properties are checked, e.g. {a: undefined, b: 2} will not equal {b: 2};`

2023-08-10 14:55 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
> +  const storage = typeof data === 'string' ? new FileStorage(data) : new MemoryStorage(data);
Не вижу в этом смысла, т.к. данная проверка и так будет, когда будет происходить валидация конфига

2023-08-10 14:58 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +      response.set('Location', request.url);
А почему нет? Header показывает по какому урлу можно получить ресурс, созданный с помощью POST

2023-08-11 03:43 UTC, MiaInturi commented on bin/build.ts
> +    };
Проходит, но я не знаю, почему тут не было исправлено

2023-08-11 03:44 UTC, MiaInturi commented on bin/build.ts
> +    };
А, это вообще уже неактуально. Этих изменений даже нет в ветке

2023-08-15 13:58 UTC, debabin requested changes

2023-08-15 13:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
> +  const isDataJsonFile = typeof data === 'string';
Все таки считаю, что нужно добавить сюда еще && includes('json'), как было сделано в валидации, сделать это для добавления контекста, а то со временем, может стать не понятно почему string это json file

2023-08-15 13:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +      const newResource = { ...currentResource, ...request.body };
const resource = storage.read(key); 
const updatedResource = { ...currentResource, ...request.body };

все таки считаю, что тут не новый, а обновленный

2023-08-15 13:58 UTC, debabin commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +    });
А мы не хотим сделать put, как patch ? А то я боюсь, что может получится ситуация, что пользователь хотел просто обновить, а у него прям заменилось, но тогда будет put и patch 1 в 1, но я думаю ничего страшного. Ведь мы в первую очередь делаем это для мокующих людей и часто put это именно изменения, а не фул замена

2023-08-15 13:58 UTC, debabin commented on package.json
> +    "pretty-global": "yarn format && yarn lint --fix"
Не нравится, что из-за по факту stylelint мы к каждой команде добавили global, мне кажется или нужено придумать название только для stylelintа либо придумать другую приписку, предлагаю вообще 3 вариант и сделать команду lint = eslint + stylelint

2023-08-20 04:56 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/helpers/createShallowDatabaseRoutes/createShallowDatabaseRoutes.ts
> +    });
Но PUT - это изменение всей сущности, а не части, как в случае с PATCH. Так что не согласен с предложением

2023-08-20 05:05 UTC, MiaInturi commented on src/core/database/createDatabaseRoutes/createDatabaseRoutes.ts
> +  const isDataJsonFile = typeof data === 'string';
Добавил + сделал для этого функцию, чтобы по типизации все было четко

2023-08-20 08:36 UTC, debabin approved these changes

2023-08-20 09:08 UTC, merged