#90 into release@3.2.0 ☄ rest api examples
siberiacancode/mock-config-server pull request #91
Opened 2023-08-21 15:58 UTC by debabin

2023-08-21 17:00 UTC, RiceWithMeat commented on examples/rest-api/delete/path-regex.ts
> +        path: '/users/:id([\\s\\S]*)',
какой смысл от этой регекспины? Пути `/users/:id` `/users/:ids` `/users/:idssSss` полезной нагрузки не несут. `/users?/:id` поинтереснее и понятнее будет. Разрешает `/user/:id` и `/users/:id`

2023-08-21 17:00 UTC, RiceWithMeat commented on examples/rest-api/get/path-regex.ts
> +        path: '/users/:id([\\s\\S]*)',
в некоторых файлах два роута с path в виде строки и regExp, а в некоторых только в виде строки

2023-08-21 17:00 UTC, RiceWithMeat commented on examples/rest-api/get/path-regex.ts
> +startMockServer(mockServerConfig);
в некоторых файлах нет запуска сервера

2023-08-21 17:01 UTC, RiceWithMeat commented
можно в комментах в каждом файле написать как отправить соответствующий запрос (фетчем например) и написать что вернётся

2023-08-21 17:11 UTC, debabin commented on examples/rest-api/get/path-regex.ts
> +        path: '/users/:id([\\s\\S]*)',
не нашел такие

2023-09-23 10:50 UTC, RiceWithMeat approved these changes

2023-10-01 06:56 UTC, anv296 commented on examples/rest-api/base-url/api-layer.ts
> +import type { MockServerConfig } from 'mock-config-server';
я вспомнил, какой вопрос меня интересовал)) почему библа называется mock **config server** а тип mock **server config**?

2023-10-01 06:57 UTC, anv296 approved these changes

2023-12-13 16:08 UTC, MiaInturi requested changes

2023-12-13 16:08 UTC, MiaInturi commented on examples/rest-api/delete/path-regex.ts
> +        path: '/users?/:id',
Это же не regexp (в некоторых файлах ниже то же самое)

2023-12-16 10:10 UTC, debabin commented on examples/rest-api/base-url/api-layer.ts
> +import type { MockServerConfig } from 'mock-config-server';
Потому-что тип говорит, что это конфиг для мок сервера, а библа говорит что мы мокаем конфигом сервер

2023-12-16 10:24 UTC, debabin commented on examples/rest-api/delete/path-regex.ts
> +        path: '/users?/:id',
https://expressjs.com/en/guide/routing.html в express они используют под капотом библу path to regexp. Тоесть по факту это regexp для express, просто если сделать например /\/users?\/:id/ это не будет работать, он будет ждать id как строку, потому-что это правило для роутов именно про :id. Но мы можем скинуть /\/users?\/ и так будет работать

2023-12-16 10:30 UTC, debabin commented on examples/rest-api/delete/path-regex.ts
> +        path: '/users?/:id',
я добавил в каждый пример и regexp и express regexp строковый

2023-12-17 06:59 UTC, MiaInturi approved these changes

2023-12-17 09:31 UTC, merged