#92 into release@3.2.0 ☄ graphql api examples
siberiacancode/mock-config-server pull request #93
Opened 2023-08-22 15:26 UTC by debabin

2023-09-23 10:55 UTC, RiceWithMeat approved these changes

2023-10-01 06:58 UTC, anv296 approved these changes

2023-12-17 07:03 UTC, MiaInturi requested changes

2023-12-17 07:03 UTC, MiaInturi commented on examples/graphql-api/mutation/operationName-string.ts
> +            data: { succes: false },
опечатка в слове success (в других файлах тоже есть)

2023-12-17 07:03 UTC, MiaInturi commented on tsconfig.dev.json
> +      "mock-config-server/*": ["./dist"],
лишний path

2023-12-17 07:42 UTC, debabin commented on tsconfig.dev.json
> +      "mock-config-server/*": ["./dist"],
он удалится другим мр,я надеюсь не упущу этот момент

2023-12-17 08:11 UTC, merged